### ISSUE TITLE
[FR] C++20 bit-twiddling functions

### ISSUE THREAD

**Issue by truboxl** [android/ndk#1664] opened 2022-02-01 01:29 UTC
### Description

https://github.com/rui314/mold/issues/308

It seems like NDK r24 and r23 not yet support all the C++20 bit-twiddling functions even after adding `#include <bit>`

Example:
`std::has_single_bit`
`std::bit_ceil`

**Comment by DanAlbert** [comment] 2022-02-01 09:24
Duplicate of #1530

**Closed by DanAlbert** 2022-02-01 09:24 UTC
Labels: enhancement
