### ISSUE TITLE
[question] How to disable fortify in CMake build?

### ISSUE THREAD

**Issue by peterdk** [android/ndk#1243] opened 2020-04-26 20:59 UTC
I have a app that uses C/C++ code using a NDK built library. I still support Android 4.1 users, and they had some so file loading issues lately. (`cannot locate __vsprintf_chk`) , which turn out to be caused by fortify. I managed to get it loading again by sprinkling `-D_FORTIFY_SOURCE=0` in the `set(CMAKE_C_FLAGS [..]`.  
I do get a lot of `_FORTIFY_SOURCE' macro redefined [-Wmacro-redefined]` that point to `#define _FORTIFY_SOURCE 2`.

I was wondering: what is the proper way to disable fortify with a single define/command? Now I need to change it in all cmake sub projects flags.

And yes, I know android 4.1 is old. :) Still, I want to release a final working version for these users, before moving on.

**Comment by DanAlbert** [comment] 2020-04-26 23:23
Fortify is supported on all API levels. The individual checks may very, but it won't use functions that aren't available.

It sounds like your minSdkVersion is higher than 16 (which is 4.1). Could be that the problem is in one of your dependencies.

Alternatively, you're setting your minSdkVersion correctly but the build system you're using isn't honoring it.

**Comment by enh-google** [comment] 2020-04-27 17:27
just in case we'd screwed up here, i did check, and it looks like we shouldn't emit references to `__vsprintf_chk` unless you're targeting API level 17 or later:
```
#if __ANDROID_API__ >= 17 && __BIONIC_FORTIFY_RUNTIME_CHECKS_ENABLED
/* No diag -- clang diagnoses misuses of this on its own.  */
__BIONIC_FORTIFY_INLINE __printflike(3, 0)
int vsnprintf(char* const __pass_object_size dest, size_t size, const char* format, va_list ap)
        __overloadable {
    return __builtin___vsnprintf_chk(dest, size, 0, __bos(dest), format, ap);
}

__BIONIC_FORTIFY_INLINE __printflike(2, 0)
int vsprintf(char* const __pass_object_size dest, const char* format, va_list ap) __overloadable {
    return __builtin___vsprintf_chk(dest, 0, __bos(dest), format, ap);
}
#endif
```

**Comment by peterdk** [comment] 2020-04-27 17:31
Ok, thanks for the info. Somehow the app would crash immediately without a stack trace when setting target to 16. I was assuming this was the same error. Cause with the fortify 0 everything works as it should. Will look into that crash a bit more.

**Comment by DanAlbert** [comment] 2020-04-28 21:35
Closing because I don't think there's a bug on our side here, but we're still paying attention if you have more questions :)

**Closed** 2020-04-28 21:35 UTC
Labels: question

**Comment by alexcohn** [comment] 2020-05-08 07:23
> the app would crash immediately without a stack trace when setting target to 16

Note that the setting that impacts your NDK behavior is not the target, but minSdkVersion.

**Comment by darksylinc** [comment] 2024-12-04 17:46
For anyone having the same problem, **the proper solution** (not a workaround) is to replace the flag:

```cpp
string( REPLACE "-D_FORTIFY_SOURCE=2" "-D_FORTIFY_SOURCE=1" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" )
string( REPLACE "-D_FORTIFY_SOURCE=2" "-D_FORTIFY_SOURCE=1" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" )
```

In this example I'm replacing NDK's default _FORTIFY_SOURCE=2 with _FORTIFY_SOURCE=1. Set it to the level that best suits your problem.

This will disable Fortify AND prevent the compiler from spamming the macro redefinition warning.
