### ISSUE TITLE
[BUG] not working -fmodules  ( and module.modulemap ) 

### ISSUE THREAD

**Issue by kaizer1** [android/ndk#1796] opened 2022-10-26 19:31 UTC
### Description

if you set "-fmodules" in the column cppFlags in gradle files android project, then we get these errors:
  
In file included from Q:/AndroidSDK/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/chrono:827:
In file included from Q:/AndroidSDK/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/ctime:49:
Q:/AndroidSDK/ndk/25.0.8775105/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/time.h:80:71: error: missing '#include <xlocale.h>'; 'locale_t' must be declared before it is used

and 

 Q:\AndroidSDK\ndk\25.0.8775105\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\xlocale.h:49:28: note: declaration here is not visible

Q:\AndroidSDK\ndk\25.0.8775105\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\bits\pthread_types.h:72:9: note: definition here is not reachable
Q:\AndroidSDK\ndk\25.0.8775105\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\bits\pthread_types.h:104:14: note: declaration here is not visible
Q:\AndroidSDK\ndk\25.0.8775105\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\bits\pthread_types.h:60:9: error: missing '#include <bits/pthread_types.h>'; 

 That is, the modules are not connected? Although there is the same file module.modulemap  in the c++ root folder ( version ndk 25... )

### Affected versions

r25

### Host OS

Windows

### Host OS version

11

### Affected ABIs

arm64-v8a

### Build system

CMake

### minSdkVersion

24

### Device API level

30

**Comment by DanAlbert** [comment] 2022-10-26 21:50
Duplicate of #1161

**Closed by DanAlbert** 2022-10-26 21:50 UTC
Labels: bug
