### ISSUE TITLE
[BUG] #include_next in C standard headers conflicts with headers in LOCAL_PATH with the same names

### ISSUE THREAD

**Issue by Triang3l** [android/ndk#1582] opened 2021-09-11 17:51 UTC
#### Description

The `c++` STL in ndk-build uses directives such as `#include_next <math.h>` to include some modifications to the C standard library headers inside of the main C standard library headers (as well as the `cstddef` C++ header).

However, if you have headers with the same names (but possibly unrelated contents, such as when you're naming your own utility library `math.h`) in your `LOCAL_PATH`, the `#include_next` in the STL header will eventually locate _your own_ `math.h`.

For reproduction, a file named `math.h` can be created in `LOCAL_PATH` of a module, with the following contents:

```cpp
#ifndef CUSTOM_MATH_H
#define CUSTOM_MATH_H
#include <cmath>
#endif
```

It then can be included in any C++ source file in the module (in "quotation marks").

Normally, this should cause no issues — this will be just a local header file with the meaning that you put into it, any contents you want (you can write helper functions for vector normalization, rotation matrices, quaternions, etc. in it), and should be the one that will be found if included as `"math.h"` in files in the same folder (as opposed to `<math.h>`).

However, due to this bug, including that file results in a massive amount of error messages like `cmath:317:9: error: no member named 'signbit' in the global namespace; did you mean 'sigwait'?` for `using ::signbit;` in `cmath`.

The issue appears to be caused by the order of the `-I` options passed to the compiler, though this needs verification as I'm not entirely sure about that. In my `app/build/intermediates/ndkBuild/$(variant)/obj/local/arm64-v8a/android_gradle_generate_ndk_build_json_arm64-v8a.stdout.txt`, I saw that the order in which the include directories are specified in the compiler arguments is:

1. `LOCAL_C_INCLUDES`
2. STL include directories
3. `LOCAL_PATH`

It appears that `LOCAL_PATH` is treated as an even more of a "system" directory than the actual system include directories. The order of local paths versus system paths is inconsistent overall. It should likely be:

1. `LOCAL_PATH`
2. `LOCAL_C_INCLUDES`
3. `LOCAL_EXPORT_C_INCLUDES` of dependencies (whether it should be depth-first or breadth-first is debatable, but I'd expect depth-first to be simpler and more predictable with a complex dependency structure as the same modules may appear at different depths — though breadth-first is possibly more correct when that's not the case, but anyway, here it probably shouldn't be significant as these paths are controlled by the application developer)
4. STL include directories

I haven't been able to find, however, where exactly the order is specified. I've tried flipping the `$$(LOCAL_C_INCLUDES) $$(LOCAL_PATH)` encounters in `build/core/definitions.mk`, but the issue was still present.

It was a surprise though to see `LOCAL_PATH` having any effect on compiler invocation — my initial expectation was that it was used only as the base for relative paths inside the makefile, not for `#include` search paths. It seems redundant to add `LOCAL_PATH` to the `#include` path list — if source files are placed directly in `LOCAL_PATH`, they will be including headers relative to the same directory anyway, while for subdirectories it seems like doing what the user did not ask for — unless this is the standard practice in build systems, however I can't say if it is as I never relied on this edge case previously. However, if it's safe to do so (as ndk-build updates are often not fully backward compatible already), maybe it would be good to remove this unobvious addition completely.

#### Environment Details

* NDK Version: 23.0.7599858
* Build system: ndk-build
* Host OS: Windows
* ABI: arm64-v8a
* NDK API level: 24
* STL: c++_shared

**Comment by DanAlbert** [comment] 2021-09-13 20:37
Hmm. I'm pretty nervous about altering behavior that has been shipping for so long (I traced git blame all the way back to the initial commit of the NDK). The most correct fix would be dropping the `-I$(LOCAL_PATH)` entirely, but that changes the behavior of `#include <name>`, and people could be relying on that. Fixing it to at least be the _first_ path, while it still introduces a behavior changes, probably introduces the expected behavior anywhere it's symptomatic.

Far too risky to be fixed in an LTS point release, and could very well end up being reverted, but I'll give it a shot.

The STL includes are handled no differently than every other `LOCAL_EXPORT_C_INCLUDES`, btw. Includes from dependencies are searched in topological order. Any dependencies that depend on the STL (because every build has exactly one chosen STL, this decision is made for all dependencies by your Application.mk) will have their includes listed before the STL because of this. That part already works correctly, but the `LOCAL_PATH` is explicitly included after dependencies.

As an aside, I couldn't find anything in the spec that says the standard header names are reserved, but it's probably safer to assume they are.

**Comment by enh-google** [comment] 2021-09-13 20:56
> As an aside, I couldn't find anything in the spec that says the standard header names are reserved, but it's probably safer to assume they are.

since the specific example is `<math.h>`, both ISO C and POSIX say "not yours; don't touch" even if C++ doesn't...

**Comment by enh-google** [comment] 2021-09-13 22:10
"ours first" seems closer to the ISO and POSIX intent anyway. this seems WAI?

**Comment by DanAlbert** [comment] 2021-09-13 23:16
https://android-review.googlesource.com/c/platform/ndk/+/1825104 is the fix, but we're all in agreement that this would risk breaking too much existing code and it's not a regression so it won't be submitted.

The language in the standard doesn't precisely rule this out. It says (C11 7.1.2.3):

> If a file with the same name as one of the above < and > delimited sequences, not provided as part of the implementation, is placed in any of the standard places that are searched for included source files, the behavior is undefined.

But "any of the standard places that are searched for included source files" is not defined. ndk-build adds `$(LOCAL_PATH)` to that list which is the cause of the bug, but that's not a normal thing for a build system to do (CMake doesn't).

That decision is not final though. Given that this _isn't_ a regression, we're confused how you got here.

Do you have an ndk-build project and you're trying to import some new third-party code that has its own math.h? If so we maybe need to do this after all.

Do you have a math.h in your existing project that you're porting to Android and you're using ndk-build? If so you should probably use CMake instead.

Do you have an existing project in ndk-build and you're adding a math.h? If so you should just pick a different name since, although not specifically forbidden by the standard, does seem like a potential problem best avoided.

**Closed by DanAlbert** 2021-09-13 23:16 UTC
Labels: bug

**Comment by Triang3l** [comment] 2021-09-17 16:16
> Do you have a math.h in your existing project that you're porting to Android and you're using ndk-build? If so you should probably use CMake instead.

Yes, the file is on the application's side, which previously used MSBuild. Though I'm not sure if the issue is present in third-party libraries as I've implemented a workaround before trying to compile any of them.

CMake may probably be an option, ndk-build was just a more straightforward (due to being designed for multi-ABI builds for Android from the beginning) and less scary build system (which I also had prior experience with), so it was my first choice, however, I don't think there are any constraints preventing the usage of it.

We use Premake (with a custom Android.mk generator that I'm currently working on) for project generation though, so we have a separate directory for Android.mk files. So, I've changed LOCAL_PATH to point to that directory rather than the source files. We still have one header file (called "version.h") in that directory, but I hope it won't be colliding with anything as, if I understand correctly, new C standard library versions only add headers prefixed with "std" :)

**Comment by Triang3l** [comment] 2021-10-30 17:36
@DanAlbert Since this is a closed issue, I'm not sure if you've received the notification — but what do you think about my idea of allowing the user to toggle this behavior with an additional variable?

On a side note, I've just finished the [Premake Android.mk generator that I mentioned](https://github.com/Triang3l/premake-androidndk) if that may be interesting. It's highly advanced and comprehensive — exposes `TARGET_ARCH_ABI` conditionals through separate Premake `platforms` with different `architecture` settings (allowing the user to select multiple platforms to build, so the entire workspace is built by one ndk-build invocation for all needed ABIs at once as designed) providing the ability to use `architecture` filters, supports all languages available in ndk-build (C, C++, GAS, Yasm, RenderScript) with the possibility to specify some of the settings for each language separately via file extension filtering in Premake, provides transitivity of `-l`, `-u`, `-flto=` linker options from and between static library dependencies (though that's handled manually via breadth-first search, for more consistency with the way Visual Studio works, instead of using `LOCAL_EXPORT_LDFLAGS/LDLIBS` as the latter don't terminate the chain of exporting at shared libraries — but this behavior is usually fine too), validates paths provided by the user and escapes shell characters (including after `$` expansion, at build time) where needed, supports different kinds of projects — built libraries and executables, prebuilt libraries, external Android.mk files.

**Comment by DanAlbert** [comment] 2021-11-01 17:41
It could be considered but I don't think it will ever be a priority.
