### ISSUE TITLE
clang++ exception performance with multi-threading

### ISSUE THREAD

**Issue by dxin2015** [android/ndk#825] opened 2018-10-18 02:14 UTC
Hi, everyone,
I have a android project that heavily uses exceptions.
After upgrading from armeabi-v7a to arm64-v8a I have observed severe performance regression related to exception handling.
Demo here:
https://github.com/dxin2015/clang_eh_threading.git

On my test device(SDM630)
armeabi-v7a mode:
threads=1 average_time=8us
threads=2 average_time=8us
threads=4 average_time=9us
threads=8 average_time=36us
threads=16 average_time=88us
threads=32 average_time=189us
threads=64 average_time=340us

arm64-v8a mode:
threads=1 average_time=10us
threads=2 average_time=12us
threads=4 average_time=33us
threads=8 average_time=75us
threads=16 average_time=153us
threads=32 average_time=274us
threads=64 average_time=535us

It seems like there is some kind of locking contention in the exception handler or stack unwinder that is hurting the performance.

In my project where there are many threads running, arm64-v8a runs at 400us per exception compared armeabi-v7a's around 20us.

I'm suspecting the exception handler isn't the source of the contention, but maybe something like the allocater, because in my project even though there are many threads, only one throws exception in a high frequency.

At same time, on my x86-64 ubuntu machine, the performance doesn't scale well either,
threads=1 average_time=1us
threads=2 average_time=1us
threads=4 average_time=6us
threads=8 average_time=16us
threads=16 average_time=33us
threads=32 average_time=66us
threads=64 average_time=128us

* NDK Version: 18.1.5063045
* Build system: ndk-build
* Host OS: Ubuntu 18.04, x86-64
* Compiler: clang++
* ABI: armeabi-v7a, arm64-v8a
* STL: libc++_shared
* NDK API level: 28
* Device API level: 26

**Comment by DanAlbert** [comment] 2018-10-18 03:31
A few things that could be the cause here:

1. 32-bit ARM and 64-bit ARM use different exception handling methods (the 32-bit ARM ABI has a unique exception handling format not used elsewhere).
2. 32-bit ARM gets its exception handling implementation from LLVM's libunwind, whereas the rest of the ABIs use libgcc.
3. Like you say, maybe it's not specifically the unwinder that's the problem but the performance of something else that's being ruined as a result of the unwind.

If the problem is option 1, this may just be the expected behavior (though maybe there's some optimization that could be done).

If it's option 2, there's not a ton to be done in the short term. One of these days the new unwinder will be available for the NDK, but we'd be blocked on that.

> At same time, on my x86-64 ubuntu machine, the performance doesn't scale well either

Given this, it could still be either 1 or 2. x86-64 GNU systems and 64-bit Android systems use the same unwind method and both use libgcc.

Should hopefully be able to get some info from simpleperf. @dxin2015: if you're interested in debugging further, that'd be the first step. Otherwise, we'll get to this at some point but probably not this release cycle.

**Comment by DanAlbert** [comment] 2019-09-19 18:07
Looks very similar to https://github.com/android/ndk/issues/1062, and @rprichard did some analysis there that it is a difference between the arm32 and arm64 unwind ABIs. Closing this as the other has the analysis. He has some ideas about how we can improve it, but the fixes will unfortunately be OS fixes, so they can't affect current devices.

**Closed by DanAlbert** 2019-09-19 18:07 UTC
