### ISSUE TITLE
[FR] clang driver should default to gnu hashes if the target api level is >= 23?

### ISSUE THREAD

**Issue by enh-google** [android/ndk#2005] opened 2024-03-18 19:42 UTC
### Description

currently we have this in the android build system:
```
// TODO: sysv hashes are the default for other architectures because gnu
// hashes weren't supported until api level 23, but riscv64 didn't exist
// back then, and could move today...
// https://android.googlesource.com/platform/bionic/+/main/android-changes-for-ndk-developers.md#gnu-hashes-availible-in-api-level-23
"-Wl,--hash-style=gnu",
```
and presumably similar stuff elsewhere. seems like that should just be the driver's problem instead?

@pirama-arumuga-nainar

**Comment by rprichard** [comment] 2024-03-18 21:11
I think we already have this enhancement:

https://github.com/llvm/llvm-project/blob/ea72c082bc29fdceca33f37477b7588f31630a5f/clang/lib/Driver/ToolChains/Linux.cpp#L277-L290

```c++
  if (!IsMips && !IsHexagon) {
    if (Distro.IsOpenSUSE() || Distro == Distro::UbuntuLucid ||
        Distro == Distro::UbuntuJaunty || Distro == Distro::UbuntuKarmic ||
        (IsAndroid && Triple.isAndroidVersionLT(23)))
      ExtraOpts.push_back("--hash-style=both");
    else
      ExtraOpts.push_back("--hash-style=gnu");
  }
```

**Comment by rprichard** [comment] 2024-03-18 21:14
It looks like @DanAlbert added it in 2018, https://reviews.llvm.org/D53118.

**Comment by pirama-arumuga-nainar** [comment] 2024-03-18 23:09
Nice - it covers non-Android triples as well.  I think we can remove all cases in https://cs.android.com/search?q=hash-style%3Dgnu%20file:build%2Fsoong&sq=&ss=android.

**Comment by enh-google** [comment] 2024-03-19 00:47
awesome! i'll just update the docs, remove the cruft from our build system (once my outstanding comment cl is in, anyway), and call this "done"...

**Comment by enh-google** [comment] 2024-03-19 00:51
https://android-review.googlesource.com/c/platform/bionic/+/3004376 is the doc update.

**Comment by DanAlbert** [comment] 2024-03-19 19:57
Duplicate of https://github.com/android/ndk/issues/883.

**Closed by DanAlbert** 2024-03-19 19:57 UTC
Labels: enhancement

**Comment by enh-google** [comment] 2024-03-19 20:22
https://android-review.googlesource.com/c/platform/build/soong/+/3007713 removes the obsolete workarounds from the build system.
