### ISSUE TITLE
[BUG] `surface_control.h` and `*font*.h` contains C++ constructs

### ISSUE THREAD

**Issue by MarijnS95** [android/ndk#1920] opened 2023-08-16 12:38 UTC
### Description

I maintain the [Rust `ndk` and `ndk-sys` crates](https://github.com/rust-mobile/ndk), and they rely on `bindgen` to parse _C_ headers.

Unfortunately, while attempting to generate these for [the font headers](https://github.com/rust-mobile/ndk/pull/397) and later `surface_control.h` Rust's `bindgen` utility complains that the headers are not valid C (these things only work in C++):

```
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font.h:102:18: error: must use 'struct' tag to refer to type 'AFont'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font.h:124:50: error: must use 'struct' tag to refer to type 'AFont'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font.h:194:32: error: must use 'struct' tag to refer to type 'AFont'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font.h:204:27: error: must use 'struct' tag to refer to type 'AFont'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font.h:218:45: error: must use 'struct' tag to refer to type 'AFont'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font.h:232:39: error: must use 'struct' tag to refer to type 'AFont'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font.h:265:33: error: must use 'struct' tag to refer to type 'AFont'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font.h:280:33: error: must use 'struct' tag to refer to type 'AFont'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font.h:295:32: error: must use 'struct' tag to refer to type 'AFont'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font_matcher.h:135:1: error: must use 'struct' tag to refer to type 'AFontMatcher'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font_matcher.h:144:27: error: must use 'struct' tag to refer to type 'AFontMatcher'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font_matcher.h:159:9: error: must use 'struct' tag to refer to type 'AFontMatcher'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font_matcher.h:175:9: error: must use 'struct' tag to refer to type 'AFontMatcher'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font_matcher.h:190:9: error: must use 'struct' tag to refer to type 'AFontMatcher'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font_matcher.h:211:1: error: must use 'struct' tag to refer to type 'AFont'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/font_matcher.h:212:15: error: must use 'struct' tag to refer to type 'AFontMatcher'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/surface_control.h:343:57: error: C does not support default arguments
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/surface_control.h:355:48: error: must use 'enum' tag to refer to type 'ADataSpace'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/surface_control.h:379:83: error: expected ')'
~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/surface_control.h:378:37: note: to match this '('
```

### Missing `struct` and `enum` tags

These are easy enough (but ugly) to work around with `typedef`s:

```c
typedef enum ADataSpace ADataSpace;
typedef struct AFont AFont;
typedef struct AFontMatcher AFontMatcher;
typedef struct ASystemFontIterator ASystemFontIterator;
```

#### Default function arguments

`~/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/surface_control.h:343:57`:

```cpp
void ASurfaceTransaction_setBuffer(ASurfaceTransaction* transaction,
                                   ASurfaceControl* surface_control, AHardwareBuffer* buffer,
                                   int acquire_fence_fd = -1) __INTRODUCED_IN(29);
```

### C++ references instead of pointers

`/home/marijn/Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/surface_control.h:379:83` (and at more places):

```cpp
void ASurfaceTransaction_setGeometry(ASurfaceTransaction* transaction,
                                     ASurfaceControl* surface_control, const ARect& source,
                                     const ARect& destination, int32_t transform)
                                     __INTRODUCED_IN(29);
```

### Affected versions

r25, r26

### Host OS

Linux

### Host OS version

Arch Linux

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

Other (specify below)

### Other build system

`bindgen` on headers only

### minSdkVersion

Irrelevant for header codegen

**Comment by DanAlbert** [comment] 2023-08-16 18:29
Hmm. I'd like to fix this in r26 but that particular component has gotten tricky to update now that rv64 is in the development branch. It isn't a regression in r26, so this may slip to r27. I don't think that would be a problem for your use case because you could just update those projects from the canary anyway. Really you probably don't even need an NDK and could just pull the sysroot from ci.android.com.

**Comment by enh-google** [comment] 2023-08-16 18:45
(and i guess this is another vote for "we really should get around to setting up the 'check that every header can be included in .c files' test" that comes up every year or so...)

**Comment by MarijnS95** [comment] 2023-08-16 18:48
I could even fix the signatures locally to get it to build. Generating from canary might be more worrisome if that includes possibly unstabilized/unfinished APIs?

**Comment by DanAlbert** [comment] 2023-08-16 18:50
> Generating from canary might be more worrisome if that includes possibly unstabilized/unfinished APIs?

The data needed to avoid those is there... but you're probably right that cbindgen doesn't read it.

**Comment by MarijnS95** [comment] 2023-08-16 18:52
I don't think we get those passed on, neither do we see the `__INTRODUCED_IN(29)` even though those would be super useful to automatically generate `#[cfg(feature = "api-level-{}")]` on the Rust side.

Maybe we can with a custom `bindgen` callback though.

**Comment by DanAlbert** [comment] 2023-08-16 18:54
For most APIs (doesn't work for libc/libm because reasons) you need https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Weak-symbols-for-API-definitions or the decl will be hidden from cbindgen.

**Comment by MarijnS95** [comment] 2023-08-16 18:56
> This is not enabled by default because, unless used cautiously, this method is prone to deferring build failures to run-time (and only on older devices, since newer devices will have the API).

It would be helpful for us for similar reasons: if we build-test our NDK high-level wrapper crate against every API version, we can very easily spot mismatches (when a symbol is used in the high-level wrapper without the appropriate `cfg`-guard).

**Comment by MarijnS95** [comment] 2023-10-19 07:14
Note that the same issue appears in the thermal headers as well:

```
/opt/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/thermal.h:114:53: error: must use 'enum' tag to refer to type 'AThermalStatus'
/opt/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/thermal.h:146:1: error: must use 'enum' tag to refer to type 'AThermalStatus'
panicked at 'Unable to generate bindings: ClangDiagnostic("/opt/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/thermal.h:114:53: error: must use 'enum' tag to refer to type 'AThermalStatus'\n/opt/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/thermal.h:146:1: error: must use 'enum' tag to refer to type 'AThermalStatus'\n")', bindgen-cli/main.rs:52:36
```

Not sure if you're aware and/or adding a CI process to check that all headers are C-compliant, so mentioning it here.

**Comment by DanAlbert** [comment] 2023-10-19 18:42
> Not sure if you're aware and/or adding a CI process to check that all headers are C-compliant, so mentioning it here.

We tried, but the build systems we have to work made it quite difficult.

**Comment by MarijnS95** [comment] 2023-12-23 12:52
> Really you probably don't even need an NDK and could just pull the sysroot from ci.android.com.

On this note, without spawning a totally new issue for a simple question, where can I find what is scheduled to be included in the next (`r26c`) release? Android 14 added `AImageReader_newWithDataSpace()` which is necessary to create an `ImageReader` for an `RGB10A2` format. This format is only available in `AHARDWAREBUFFER_FORMAT` and not in `AIMAGE_FORMAT`, and only the new API function allows `AHARDWAREBUFFER_FORMAT` (together with a data space).

I tried looking at cs.android.com but I only only see tags/branches for past releases such as:
https://cs.android.com/android/platform/superproject/+/ndk-r26b:prebuilts/ndk/platform/sysroot/usr/include/media/NdkImageReader.h

Can you point me in the right direction?

**Comment by MarijnS95** [comment] 2024-01-04 09:50
Looks like the font headers have been fixed, but `surface_control.h` is still broken even on the latest CI builds. Can I contribute these changes upstream? I have decided to need and write a wrapper for `SurfaceControl` _now_, and continuously need to make trivial fixes to this header if I wish to regenerate/update our bindings.

On that note I'm very much inclined to follow @DanAlbert's advice and migrate [the `ndk-sys` crate](https://github.com/rust-mobile/ndk) to NDK CI builds because of all the missing API from the published NDK as pointed out above.

---

@appujee what is your plan for the https://github.com/android/ndk/labels/rust label? While this issue primarily impacts our ecosystem, the effect is global (headers aren't usable in plain C) and not limited to Rust.

**Comment by MarijnS95** [comment] 2024-01-04 13:38
Also notice that while this API takes an `ADataSpace` (should be `enum ADataSpace` to be valid C), all other APIs take an `int dataSpace`.

Which of the two is correct?

**Comment by enh-google** [comment] 2024-01-04 16:51
> Can I contribute these changes upstream? 

yes, of course. (whether the owners will _take_ them is of course a slightly different question, but at least at that point you'd be talking to the api owners!)

> Which of the two is correct?

i don't think we have any idea. i've forwarded your question to the person who added the api though.

**Comment by MarijnS95** [comment] 2024-01-04 23:01
@enh-google thanks! After some fighting with `repo` all changes are uploaded and live at https://android-review.googlesource.com/c/platform/frameworks/native/+/2897863!

In general I'm struggling a bit with the NDK here. First reported at https://issuetracker.google.com/issues/300602767, there are quite a few inconsistencies in the documentation, and I'd like to have (more) complete (non-)nullability annotations as well as thread safety/threading guarantees for both structures/pointers and callbacks (i.e. is an object internally synchronized? Can it be "moved" to another thread as long as it is not accessed concurrently? Will a callback be called on the current thread, or on _one_ other thread? Or on _multiple_ threads, possibly concurrently, hence requiring synchronization)? There was some activity and response initially, but as I started reporting more inconsistencies (with a general "please check the whole file as I cannot report every line"), activity died down.

**Comment by enh-google** [comment] 2024-01-04 23:41
> In general I'm struggling a bit with the NDK here. 

it's a classic "your org chart is showing" problem... you want to talk to a person/group that doesn't exist. what _does_ exist is "us", who _own_ the toolchain and _include_ a sysroot, and then a multitude of teams who own different parts of the sysroot (including us for the basic libc headers!). but if you have an issue with a camera header and an issue with a storage header and an issue with an input event header, well, those are going to have to go to completely different people on completely different teams. (so, in practice "file a separate [buganizer, not github!] bug for each one, and if it doesn't end up assigned to an appropriate adult, you can try letting us know and we can see if we can find the right person". tbh, if you use `git log` you can probably tell the person doing the triage who they should be talking to. they don't tend to have `git log` skills.)

> I'd like to have (more) complete (non-)nullability annotations as well as thread safety/threading guarantees for both structures/pointers and callbacks (i.e. is an object internally synchronized? Can it be "moved" to another thread as long as it is not accessed concurrently? Will a callback be called on the current thread, or on one other thread? Or on multiple threads, possibly concurrently, hence requiring synchronization)? There was some activity and response initially, but as I started reporting more inconsistencies (with a general "please check the whole file as I cannot report every line"), activity died down.

going forward, there _is_ a group of people who do look at every _new_ api added to the ndk, and these are probably things that should go on their checklist. (meanwhile _our_ team [specifically @ZijunZhaoCCK] has recently retconned nullability annotations for the entirety of libc, even if that wasn't the part of the sysroot you were actually talking about :-) )

**Comment by MarijnS95** [comment] 2024-01-06 20:58
@enh-google sure, I understand why this is the case, but wanted to report these issues as a whole and have a team of Googlers pick this up, rather than me painstakingly going through every API and requesting clarification everywhere, effectively picking up that job. Which I'm already doing to a significant extent, by using my free time to map NDK APIs into Rust, parsing the documentation, and finding various inconsistencies or general lack of clear and consistent documentation.

Sounds like I'll either have to leave it be, or file many separate issues on https://issuetracker.google.com/issues/new?component=192763&template=1032811 (assuming the NDK component is correct).

Notice that I'm trying to be helpful by pointing out lacking or inconsistent documentation, rather than figuring it out myself from the codebase and moving on with my day (with the added benefit of the semantics being locked in place). Asking a contributor to also take over part of someones job of triaging via `git log`, at that point I might as well end up on a payroll and submit documentation fixes upstream immediately (as already done once shown above).

**Comment by DanAlbert** [comment] 2024-01-09 22:42
> without spawning a totally new issue for a simple question

Don't hesitate to use the "discussions" tab. That's what it's there for :)

> where can I find what is scheduled to be included in the next (r26c) release?

Specifically in the context of sysroot updates, you don't. It's extremely rare that we update the sysroot in a minor release. When we do, because it comes in as a prebuilt, you won't see it happen until we do the update, at which point you'll see it in the CI builds. For this release in particular, it'd be a rather large amount of work to update the sysroot without causing problems (since the source I pull from now includes rv64 stuff, and we very much are not ready to put that in the NDK), so I don't expect any sysroot updates for any r26 minor releases.

More generally, "what's going to be in the next release?" is answered in the projects tab. There's no secret internal planning board; that board is the real one.

> On that note I'm very much inclined to follow @DanAlbert's advice and migrate [the ndk-sys crate](https://github.com/rust-mobile/ndk) to NDK CI builds because of all the missing API from the published NDK as pointed out above.

SGTM, but beware all the usual problems of living at HEAD. There will be non-final stuff in there. All the finalized APIs should be 100% stable (and if they aren't, that's a major bug and we'd want to fix it asap), and the non-final stuff probably isn't of interest to you anwyay.

> Also notice that while this API takes an ADataSpace (should be enum ADataSpace to be valid C), all other APIs take an int dataSpace.
>
> Which of the two is correct?

The enum. Older APIs use `int` (usually `int32_t`) because we used to support GCC, which didn't support specifying the backing type of an enum in C. We only support Clang now, which does allow that. We previously couldn't use `enum` directly in the ABI because without the specified backing type, we couldn't defend against the size/alignment of the enum changing. Now that we can, we prefer that for type safety (as well as improving self-documentation and IDE behavior).

We haven't retroactively updated all the older APIs (no bandwidth to do so, and in some cases it's actually not possible because the real API is `union { the_enum, some_other_crap }`), so you'll see a mix.

> wanted to report these issues as a whole and have a team of Googlers pick this up

Sadly there's no team to do that. It's never really worked in my experience anyway. I could convert your mega-bug into a dozen better scoped bugs, but you'll need to be there for the follow up questions anyway. Plus, you, as a real person, are more likely to be listened to than I am.

> (assuming the NDK component is correct).

It isn't. That's not even supposed to be open 😩

See the "documentation bug" listed on our "new issue" page:
![image](https://github.com/android/ndk/assets/315852/34dc6827-507b-469f-8b30-5bf412491888)

> Notice that I'm trying to be helpful by pointing out lacking or inconsistent documentation, rather than figuring it out myself from the codebase and moving on with my day

We do appreciate that, fwiw.

> Asking a contributor to also take over part of someones job of triaging via git log, at that point I might as well end up on a payroll and submit documentation fixes upstream immediately (as already done once shown above).

Agreed that it sucks, but I assume you're rather us be honest about how much it sucks than pretend it doesn't.

**Comment by MarijnS95** [comment] 2024-01-09 23:44
> More generally, "what's going to be in the next release?" is answered in the projects tab. There's no secret internal planning board; that board is the real one.

Unless I'm looking in the wrong place, https://github.com/orgs/android/projects/7/views/1 doesn't really have a clear "you'll get the new JNI functions for `SurfaceControl` and `SurfaceTransaction`, a binding for `AImageReader_newWithDataSpace()` from Android 14, etc".

> SGTM, but beware all the usual problems of living at HEAD. There will be non-final stuff in there. All the finalized APIs should be 100% stable (and if they aren't, that's a major bug and we'd want to fix it asap), and the non-final stuff probably isn't of interest to you anwyay.

Tbh it's looking great, and I'll only use APIs that have a clear `Available since XX` (or APIs that were forgotten when someone ported it long ago). Not sure what to do with enum variants though, and if it makes sense to gate them.

See the changes for yourself: https://github.com/rust-mobile/ndk/commit/11f350dda0c56bebb46f6619220c06be89f2fe2c

---

> The enum. Older APIs use `int` (usually `int32_t`) because we used to support GCC, which didn't support specifying the backing type of an enum in C. We only support Clang now, which does allow that. We previously couldn't use `enum` directly in the ABI because without the specified backing type, we couldn't defend against the size/alignment of the enum changing. Now that we can, we prefer that for type safety (as well as improving self-documentation and IDE behavior).
> 
> We haven't retroactively updated all the older APIs (no bandwidth to do so, and in some cases it's actually not possible because the real API is `union { the_enum, some_other_crap }`), so you'll see a mix.

Good stuff. I might even submit some fixes for this upstream as it greatly helps our cause too.

Note that `enum ADataSpace` here doesn't actually have a storage specifier (https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/libs/nativewindow/include/android/data_space.h;l=40?q=adataspace) so I'm not sure if it can be used like that in the `SurfaceControl` APIs yet.

> > wanted to report these issues as a whole and have a team of Googlers pick this up
> 
> Sadly there's no team to do that. It's never really worked in my experience anyway. I could convert your mega-bug into a dozen better scoped bugs, but you'll need to be there for the follow up questions anyway. Plus, you, as a real person, are more likely to be listened to than I am.

Perhaps individual teams could pick this up on their own, rather than there being a high-level team coordinating fixes. However, having a high-level team coordinating consistent API and documentation (the "group of people" mentioned in https://github.com/android/ndk/issues/1920#issuecomment-1877911064) but I might be dreaming at this point.

Also, hello robot? I thought I was talking to a real Googler :grimacing:. Regardless, my experience as non-Googler (when it came to outsider AOSP contributions) wasn't too great.

---

> > (assuming the NDK component is correct).
> 
> It isn't. That's not even supposed to be open 😩
> 
> See the "documentation bug" listed on our "new issue" page: ![image](https://private-user-images.githubusercontent.com/315852/295359675-34dc6827-507b-469f-8b30-5bf412491888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NDM3NzEsIm5iZiI6MTcwNDg0MzQ3MSwicGF0aCI6Ii8zMTU4NTIvMjk1MzU5Njc1LTM0ZGM2ODI3LTUwN2ItNDY5Zi04YjMwLTViZjQxMjQ5MTg4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQyMzM3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjAzN2FmZGIxYWJlNzUyOWNlNDI1YWJmNjdmODVjNjA2MDFjOGQzMTc5NGY5ZTI5ZTE1MjMwMTAyYjllZDRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cEMw6y9IMq1t2J1MhKDQ3I8iqFMyCEttWvlsxHZiVy4)

The "NDK component" is referring to the issuetracker, your screenshot is from GitHub.

Following [that link](https://source.android.com/docs/setup/contribute/report-bugs) though, I'm supposed to end up in framework (that's where most of the headers come from anyway): https://issuetracker.google.com/issues?q=componentid:192705%2B

Please let me know if there are any of my open issues here that I should better migrate (I believe the answer will be "yes").

Can I update the existing reports to Framework too?

> > Notice that I'm trying to be helpful by pointing out lacking or inconsistent documentation, rather than figuring it out myself from the codebase and moving on with my day
> 
> We do appreciate that, fwiw.

It's not something I'd hope to keep doing forward, but I guess API-completeness and correctness (of the Rust crate, and the NDK C bindings as a result) just lies close to my heart.

> > Asking a contributor to also take over part of someones job of triaging via git log, at that point I might as well end up on a payroll and submit documentation fixes upstream immediately (as already done once shown above).
> 
> Agreed that it sucks, but I assume you're rather us be honest about how much it sucks than pretend it doesn't.

Fair enough. I'll file a few and see how it goes.

**Comment by DanAlbert** [comment] 2024-01-10 00:43
>> More generally, "what's going to be in the next release?" is answered in the projects tab. There's no secret internal planning board; that board is the real one.
>
> Unless I'm looking in the wrong place, https://github.com/orgs/android/projects/7/views/1 doesn't really have a clear "you'll get the new JNI functions for SurfaceControl and SurfaceTransaction, a binding for AImageReader_newWithDataSpace() from Android 14, etc".

We don't know if there will be a sysroot update in r27 yet or not.

You're right though, I was leaning a bit too heavily on the phrase "generally". The changelog tells you when the sysroot gets updated, but there's rarely a tracking bug for it.

> Good stuff. I might even submit some fixes for [int -> enum migration] upstream as it greatly helps our cause too.

And the good news there is that I'm one of the reviewers you'll need for that anyway. Like I said there are a couple very hairy cases, but I expect _most_ of them are straightforward.

> Note that enum ADataSpace here doesn't actually have a storage specifier (https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/libs/nativewindow/include/android/data_space.h;l=40?q=adataspace) so I'm not sure if it can be used like that in the SurfaceControl APIs yet.

😱 

Okay, that's something we missed in review. https://android-review.googlesource.com/c/platform/frameworks/native/+/2902242.

> Also, hello robot? I thought I was talking to a real Googler 😬. Regardless, my experience as non-Googler (when it came to outsider AOSP contributions) wasn't too great.

"Real person" as in "an actual user" :)

I'll have better luck finding someone if triage fails, but problems reported by an actual user should always be more interesting than whatever I think :)

> The "NDK component" is referring to the issuetracker, your screenshot is from GitHub.

Yeah, there isn't supposed to be an open NDK component in issuetracker. That's /dev/null 😞 There shouldn't be anything pointing you there though. b.android.com shouldn't mention it (and I don't think it does?), and neither does our github page. It should only be discoverable by searching within issuetracker, but I wouldn't recommend doing that. Different teams have different triage processes and if you file in an arbitrary component it may never been seen by anyone. Always follow b.android.com unless someone tells you otherwise. (Yes, I can hear how stupid that is as I type it, but that is how it works)

**Comment by DanAlbert** [comment] 2024-01-18 20:11
> the one I've uploaded at https://android-review.googlesource.com/c/platform/frameworks/native/+/2897863 remains untouched for 2 weeks 👎

You've added no reviewer. Doubtful anyone was notified (subscribing to all new changes in frameworks/base would probably generate thousands of emails a day, so even if anyone is doing that, there's no way they'd have seen it). There's an "add owners" or "suggest owners" button on the page you need to click to add a reviewer:
![image](https://github.com/android/ndk/assets/315852/6af0c127-d8ab-4b9d-ba46-0e51338660da)

I've gone ahead and done that.

**Comment by MarijnS95** [comment] 2024-01-18 20:15
Thanks, I wouldn't have expected there to be even more manual action. The system should really be based on code owners.

Is this documented somewhere? At least this is what I expected Gerrit to do: https://source.android.com/docs/setup/contribute/life-of-a-patch

**Comment by DanAlbert** [comment] 2024-01-18 20:17
![image](https://github.com/android/ndk/assets/315852/1b264318-3f49-49e4-aa9b-efe032cf675d)

**Comment by MarijnS95** [comment] 2024-01-18 22:12
Sure, the flowchart goes two-ways and I had hoped Gerrit would pick up codeowners (without really paying attention to explicitly-assigned reviewers), and pinging you as reviewer here would have implicitly held for the left branch :)

**Comment by DanAlbert** [comment] 2024-01-19 00:31
Oh, indeed it does. That's... misleading.

And yes. When in doubt, bothering whatever droid you happen to know usually works.

**Comment by DanAlbert** [comment] 2024-01-19 00:32
https://source.android.com/docs/setup/contribute/submit-patches#request-review is more explicit, fwiw. That's the "full instructions" link at the top of the flow chart.

**Comment by MarijnS95** [comment] 2024-01-19 08:24
Thanks :)

When submitting new patches, would I just select all of the codeowners?

**Comment by DanAlbert** [comment] 2024-01-19 22:17
I find it's better to pick one at first. If a CL has ten reviewers assigned, everyone thinks someone else will do it, and so no one thinks it's their job. I usually start with one, then add more if it doesn't get any attention (yes, Googlers have this problem too).

**Comment by enh-google** [comment] 2024-01-19 22:32
> I find it's better to pick one at first. If a CL has ten reviewers assigned, everyone thinks someone else will do it, and so no one thinks it's their job. I usually start with one, then add more if it doesn't get any attention (yes, Googlers have this problem too).

(yep, another googler here, saying "me too" to both this problem and this tactic.)

**Comment by MarijnS95** [comment] 2024-01-22 23:09
Sounds good, thanks for thinking with me :)

Have submitted a bunch of new CLs with additional type improvements, let's hope we can push these through...

**Comment by MarijnS95** [comment] 2024-03-31 11:18
> Really you probably don't even need an NDK and could just pull the sysroot from ci.android.com.

@DanAlbert one more question regarding this: how can one consume NDKs from this page in a CI? Constructing a download URL like `https://ci.android.com/builds/submitted/11651052/ndk/latest/ndk_platform.tar.bz2` (based on the NDK build number) directs to a page that starts a download via JavaScript, is there a direct link available I can feed into `curl` without regex'ing the redirect link out?

**Comment by DanAlbert** [comment] 2024-04-02 18:40
See https://cs.android.com/android/platform/superproject/main/+/main:development/python-packages/fetchartifact/fetchartifact/__init__.py. I've got no idea if the URL pattern that uses is guaranteed to be stable, but I copied it from the golang implementation of the same thing that was written by someone that knows a bit more about it than I do.

**Comment by MarijnS95** [comment] 2024-04-02 21:24
@DanAlbert Thanks (and sorry for the off-topic), `https://androidbuildinternal.googleapis.com/android/internal/build/v3/builds/11651052/ndk/attempts/latest/artifacts/ndk_platform.tar.bz2/url` (with redirects) does it!

**Comment by DanAlbert** [comment] 2024-04-02 21:26
Don't hesitate to use https://github.com/android/ndk/discussions for questions.

**Comment by DanAlbert** [comment] 2024-06-04 20:04
Still a work in progress. It's going to take a while still. Moving to r28.

**Comment by DanAlbert** [comment] 2024-08-01 20:48
Most of the issues have been cleaned up. The reference arguments are definitely still there though. I'd been saving those for last because it'd be a safety regression to do that without also adding `_Nonnull`, but now that the rest of the file is annotated we should be able to do that. I'll see how much more of this we can manage for r28, but this work has been extremely slow for infrastructural reasons, and I'm unfortunately spread very thin right now.

**Comment by MarijnS95** [comment] 2024-08-01 20:51
Understood; I've been spread equally thin (thinner than individual atoms, how is that possible) with no time to set up an AOSP tree to help you out. Either way thank you for pushing parts of my commits forward! I do hope that I can one day land the `SurfaceControl` APIs to our Rust `ndk` crate, with our without manually patching the headers :)

**Comment by DanAlbert** [comment] 2024-08-01 21:04
The problems aren't thing a non-googler could help with anyway, unfortunately :( Making the change isn't the hard part, it's getting it past all the presubmit crap we have.

**Comment by DanAlbert** [comment] 2024-08-01 22:28
Actually we are _way_ closer on this than I'd expected. At least for the set of headers you mentioned, it really is just the C++ references left in `surface_control.h`. There's also something in `thermal.h` (missing `struct` and `enum` tags) and `performance_hint.h` (missing `#include <stdbool.h>`). If the list is that short I'm somewhat optimistic that we can get this cleaned up for r28.

https://r.android.com/q/topic:%22surface_control-c-compat%22 fixes the rest of the originally filed problems. Getting that merged will probably take a few days since downstream branches always cause headaches.

**Comment by DanAlbert** [comment] 2024-08-01 22:40
https://r.android.com/3205058 fixes `performance_hint.h` and https://r.android.com/3205910 for `thermal.h`. Those two should get through easily since they don't impact the ABI dumps.

We'll probably regress on this again. I'll take another stab at enforcing C compatibility at build time, but the last few times I tried it proved very difficult. I might be able to do something stupid but good enough instead.

**Comment by DanAlbert** [comment] 2024-08-05 21:25
https://ci.android.com/builds/branches/aosp-master-ndk/grid?head=12185972&tail=12185972&legacy=1 and newer should be fixed. If it's not too much work for you to test the canary, want to do that and let me know if I missed anything bindgen needs?

**Closed by DanAlbert** 2024-08-05 21:25 UTC
Labels: bug, rust

**Comment by MarijnS95** [comment] 2024-08-05 21:35
Thanks @DanAlbert, that's awesome! Works flawlessly as demonstrated at https://github.com/rust-mobile/ndk/commit/6175ea0.

Forgot to mention but your fix for `thermal.h` got me to [bind `AThermal`](https://github.com/rust-mobile/ndk/pull/481) over the weekend. `performance_hint.h` was already compiling for us (we pull in all the headers and one somewhat earlier must've already included `stdbool.h`) so that [got bound as well](https://github.com/rust-mobile/ndk/pull/480). All that remains is an inhumane amount of source-code diving to understand and describe the semantics of the API (in particular around callbacks).

**Comment by DanAlbert** [comment] 2024-08-05 21:43
Great, thanks for confirming.

I'll keep working on adding some validation to make sure we don't regress. Adding it in the right place to catch it early is the hard part, but if that doesn't pan out I suppose I can add something to the NDK tests themselves. If we catch it then, the mistake has already been made in the OS so it'll delay a release (potentially for a long time, seeing how long it took us to fix this) as opposed to preventing the broken change from landing in the first place, but that's better than shipping it broken.

> All that remains is an inhumane amount of source-code diving to understand and describe the semantics of the API (in particular around callbacks).

File doc bugs anywhere the docs aren't clear and I'll see what I can do. The newer APIs should have somewhat okay docs (they go through fairly thorough review, but a lot of the wtfs aren't apparent until they start getting used in the wild), and I've been trying to improve some of the older docs. I expect there are several months of full time work fixing all the old stuff though, so some direction toward the worst offenders would help.

**Comment by MarijnS95** [comment] 2024-08-05 21:58
The [doc bug I've filed thus far](https://issuetracker.google.com/issues/318944941) is probably too generic to gain any traction (likewise reporting general formatting and spelling mistakes is a dead end beyond contributing them myself, but that's a full-time job: https://issuetracker.google.com/issues/300602767).

Specifically, and perhaps this should be driven generically, it'd be nice to know when objects are expected to be externally synchronized, hence making them thread-safe. Specifically, in Rust this applies to the whole object, not just a few functions (though there are ways to represent such interactions too).

For callbacks the main issue I've been debugging a while back (and am a bit fuzzy on the details) is race conditions regarding when a callback is registered, replaced, removed, and the entire object being removed/destroyed, versus the callback being triggered. Unfortunately I've only vaguely recollected my thoughts in https://github.com/rust-mobile/ndk/issues/464, and will need to run some experiments again.
The callback in `Thermal` is exceptionally nice because it's fully internally synchronized, _and its lifetime is tied to that of `AThermalManager` (if we release our object, the callbacks are removed as well).
`ImageReader` and perhaps also `MediaCodec` where the worst, where I could easily trigger race conditions.
