### ISSUE TITLE
[BUG] Possible misbehavior of __compressed_pair

### ISSUE THREAD

**Issue by pendyalasyam** [android/ndk#1197] opened 2020-03-02 07:33 UTC
Hi Team,

we have a unique_ptr defined like below

std::unique_ptr<Messaging::RequestResponseBroker, std::function<void(Messaging::RequestResponseBroker *)>> m_msgBroker;

When we are std::move'ing this member to some other variable of same type, we are observing crash. I did little investigation around this and suspecting compressed_pair is misbehaving.

As you can see from __compressed_pair code in function header file, __compressed_pair is inheriting two __compressed_pair_elems which are templatized by arguments given to unique_ptr.

1)I am printing the value of "this" when __compressed_pair_elem is constructed for std::function<void(Messaging::RequestResponseBroker *)>. 

2) Once entire __compressed_pair is constructed, from inside its constructor definition, I am calling first(); second();  to see whether type casting inside __compressed_pair is properly working. when second() function is called, __compressed_pair is type casting its *this  to _Base2& and calling _get(). Inside _get() I am printing this value.

As per my understanding the value printed in 1) and the value printed in 2) must be same. But it is printing two different values.

Isnt this wrong? Please help me understand.

**Here are the log snippets:**
```
SyamDebug:Count86532 0x7fdd48b201b0 //this value when __compressed_pair_elem is called for Messaging::RequestResponseBroker. Printing this value from __compressed_pair_elem constructor
SyamDebug:Count86535 0x7fdd48b201b0 0x7fdd48b201b0 //called _get() from constructor again to see what _get() is printing 
SyamDebug:Count86531 0x7fdd48b201c0 //this value when __compressed_pair_elem is called for Messaging::RequestResponseBroker. Printing this value from __compressed_pair_elem constructor
SyamDebug:Count86535 0x7fdd48b201c0 0x7fdd48b201c0 //called _get() from constructor again to see what _get() is printing 
SyamDebug: compressed pair constructed1 0x7fdd48b201b0 
SyamDebug:Count86535 0x7fdd48b201b0 0x7fdd48b201b0 //On first() called from __compressed_pair. This is same as this value printed while consturcting first element
SyamDebug:Count86535 0x7fdd48b201b8 0x7fdd48b201b8 //On second() called from __compressed_pair. This seems to be wrong. Should not this 0x7fdd48b201c0

```

I am guessing this is wrong behavior. Could somebody please confirm. If this is indeed wrong behavior, any guess what can be going wrong here.

#### Environment Details
* NDK Version: R21
* Build system: Custom
* Host OS: Windows
* ABI: droidx64

**Comment by DanAlbert** [comment] 2020-03-02 08:14
Can you provide your repro case?

> ABI: droidx64

Which ABI?

**Comment by pendyalasyam** [comment] 2020-03-02 08:29
We are seeing this on android x64 emulators.

**Comment by pendyalasyam** [comment] 2020-03-02 08:33
I need to separate that code out from our project. I will bring that out and provide you the repro.

Meanwhile could you pls confirm if that is indeed suspicious behavior.

**Comment by DanAlbert** [comment] 2020-03-03 01:12
Not asking for a full repro case (yet), I just want to see whatever you did to libc++ to cause those logs because I don't understand which logs are coming from which lines. A patch file for your changes to `memory` would be fine.

**Comment by pendyalasyam** [comment] 2020-03-03 05:11
[ToGoogle.zip](https://github.com/android/ndk/files/4279345/ToGoogle.zip)


Attached both functional and memory header files

**Comment by pendyalasyam** [comment] 2020-03-17 14:10
Hi @DanAlbert , any update on this please.

**Comment by DanAlbert** [comment] 2020-03-17 18:04
Haven't had time to look yet.

**Comment by pendyalasyam** [comment] 2020-03-25 11:40
@DanAlbert ,

when we create unique_ptr like below

std::unique_ptr<Messaging::RequestResponseBroker, std::function<void(Messaging::RequestResponseBroker *)>> m_msgBroker;

compressed_pair's entire memory can be divided as  compressed_pair_elem<Messaging::RequestResponseBroker*> and compressed_pair_elem<std::function<void(Messaging::RequestResponseBroker *)>>

if compressed_pair_elem<Messaging::RequestResponseBroker*> starts at 0x0,  compressed_pair_elem<std::function<void(Messaging::RequestResponseBroker *)>> should start at 0x8 because the size of compressed_pair_elem<Messaging::RequestResponseBroker*> is 8, 

But it is starting at 0xF. I guess this is because of default 16byte packing applied for std::function.

If that is the case, then on calling second() which executes "static_cast<_Base2&>(*this)" should also return 0xF. But it is returning 0x8. This is wrong. 

To confirm the same, I tested unique_ptr with one other simple structure and here is the assembly code of compressed_pair destructor which seems to be correct

libmotif.nativeunittesthost.so`std::__ndk1::__compressed_pair<MyStruct*, std::__ndk1::function<void (MyStruct*)> >::~__compressed_pair:
    0x7f8a0de63f70 <+0>:  pushq  %rbp
    0x7f8a0de63f71 <+1>:  movq   %rsp, %rbp
    0x7f8a0de63f74 <+4>:  andq   $-0x10, %rsp
    0x7f8a0de63f78 <+8>:  subq   $0x10, %rsp
    0x7f8a0de63f7c <+12>: movq   %rdi, 0x8(%rsp)
    0x7f8a0de63f81 <+17>: movq   0x8(%rsp), %rax
**->  0x7f8a0de63f86 <+22>: addq   $0x10, %rax**
    0x7f8a0de63f8c <+28>: movq   %rax, %rdi
    0x7f8a0de63f8f <+31>: callq  0x7f8a0de63270            ; std::__ndk1::__compressed_pair_elem<std::__ndk1::function<void (MyStruct*)>, 1, false>::~__compressed_pair_elem at memory:2135
    0x7f8a0de63f94 <+36>: movq   %rbp, %rsp
    0x7f8a0de63f97 <+39>: popq   %rbp
    0x7f8a0de63f98 <+40>: retq   


But with only RequestResponseBroker only this is adding 0x8. See the assembly code of compressed_pair destructor

libmotif.nativeunittesthost.so`std::__ndk1::__compressed_pair<Grf::Messaging::RequestResponseBroker*, std::__ndk1::function<void (Grf::Messaging::RequestResponseBroker*)> >::~__compressed_pair:
    0x7f8a0de1ca20 <+0>:  pushq  %rbp
    0x7f8a0de1ca21 <+1>:  movq   %rsp, %rbp
    0x7f8a0de1ca24 <+4>:  andq   $-0x10, %rsp
    0x7f8a0de1ca28 <+8>:  subq   $0x10, %rsp
    0x7f8a0de1ca2c <+12>: movq   %rdi, 0x8(%rsp)
    0x7f8a0de1ca31 <+17>: movq   0x8(%rsp), %rax
**->  0x7f8a0de1ca36 <+22>: addq   $0x8, %rax**
    0x7f8a0de1ca3c <+28>: movq   %rax, %rdi
    0x7f8a0de1ca3f <+31>: callq  0x7f8a0de1caf0            ; std::__ndk1::__compressed_pair_elem<std::__ndk1::function<void (Grf::Messaging::RequestResponseBroker*)>, 1, false>::~__compressed_pair_elem at memory:2135
    0x7f8a0de1ca44 <+36>: movq   %rbp, %rsp
    0x7f8a0de1ca47 <+39>: popq   %rbp
    0x7f8a0de1ca48 <+40>: retq 


I am not understand what is so special about our RequestResponseBroker which makes compiler generate code to add only 8 for getting Base2 object. Any guesses? Could you please help take up this with clang team if possible.

**Comment by DanAlbert** [comment] 2020-06-09 20:53
Okay, I think I at least understand what's being asked here now. To rephrase it just to make sure I'm understanding correctly: you have a struct (or class, whatever) `RequestResponseBroker` that is being used in `__compressed_pair` (via `unique_ptr`), and it's crashing at some point because the offset is being calculated as 8 rather than 16. Is that right?

One thing I'm not following though: where does the crash happen? In the original post it sounds like you're saying it's crashing _during_ `std::move`, but in the most recent one it sounds like you're saying it's during deletion of the `std::move`'d pointer (I may be misunderstanding when the `__compressed_pointer` destructor gets called).

> I am not able to understand what is so special about our RequestResponseBroker which makes compiler generate code to add only 8 for getting Base2 object. Any guesses?

Any attributes that alter alignment or packing? Any zero-length-arrays? I'm just blindly guessing at things that are edge cases here. Without knowing what that structure is I don't think I can be much more help.

> Could you please help take up this with clang team if possible.

If you can provide a test case that demonstrates the crash then sure, but I doubt I could get anyone to investigate this as-is. For that matter, I'm not sure how to proceed without a repro case either. Nothing here looks wrong, but the code is also incomprehensible template soup.

FWIW, it does look like much of this code has been rewritten. You should probably see if the problem reproduces with the NDK r22 canary before trying to reduce that test case.

**Comment by DanAlbert** [comment] 2020-06-25 20:10
Closing for lack of info. Will reopen if there's more we can do, but nothing is jumping out at me so we'll need more info to go further.

**Closed by DanAlbert** 2020-06-25 20:10 UTC
Labels: bug, needs-info

**Comment by loganblevins** [comment] 2020-07-17 19:30
We're also observing a strange crash in this area.

**Comment by DanAlbert** [comment] 2020-07-17 19:31
Can you provide a repro case?

**Comment by loganblevins** [comment] 2020-07-17 20:14
@DanAlbert Might not be able to come up with a more complete example until next week. This just recently cropped up for us today.

So far, we've only observed the crash on 32 bit builds. We can identify this because our App Bundle is using the split APK with armeabi-v7a and arm64-v8a. Our crashes seem to come exclusively from 32 bit. The only device I have to reproduce on is a moto g6. It's a 64 bit CPU with Android 9 32 bit OS. According to logs, it does use the 32 bit build variant, making it consistent with our crash reports. It's not reproducible on 64 bit builds to our knowledge.

We're using NDK 20b, C++ 14, libc++ shared STL. 

Specifically:
We are creating a `std::unique_ptr` and using move semantics to pass it on to a few other callers down the line. It appears that the instance in question of the `std::unique_ptr` is invalid at some point in this passing around via `std::move`. At the tail end of the stepping to the point of crash, we end up with: `__cxa_free_exception`. My guess is that because I observed - by stepping through prior points of this call chain - the invalid instance of this smart pointer, that it must be trying to get freed and thus cannot be freed because it wasn't properly allocated when we tried to instantiate it.
