### ISSUE TITLE
[BUG] Failed to build Android native tutorial project in macOS Catalina

### ISSUE THREAD

**Issue by sinfere** [android/ndk#1104] opened 2019-10-18 15:32 UTC
#### Description

After upgrade to macOS Catalina, I found my android studio NDK project build failed, I've tried many ways but failed, then I created a native Android c++ project from the Android tutorials. I get the following compile errors: (similar to my own projects)
```
> Task :app:javaPreCompileDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Volumes/DATA/android-sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/dd/tmp/ndk-test/app/.cxx/cmake/debug/armeabi-v7a native-lib}
  ninja: Entering directory `/Users/dd/tmp/ndk-test/app/.cxx/cmake/debug/armeabi-v7a'
  [1/2] Building CXX object CMakeFiles/native-lib.dir/native-lib.cpp.o
  FAILED: CMakeFiles/native-lib.dir/native-lib.cpp.o 
  /Volumes/DATA/android-sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi26 --gcc-toolchain=/Volumes/DATA/android-sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Volumes/DATA/android-sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -Dnative_lib_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/native-lib.cpp.o -MF CMakeFiles/native-lib.dir/native-lib.cpp.o.d -o CMakeFiles/native-lib.dir/native-lib.cpp.o -c /Users/dd/tmp/ndk-test/app/src/main/cpp/native-lib.cpp
  In file included from /Users/dd/tmp/ndk-test/app/src/main/cpp/native-lib.cpp:1:
  In file included from /Volumes/DATA/android-sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h:28:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h:52:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types.h:32:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
  #error Unsupported architecture
   ^
  In file included from /Users/dd/tmp/ndk-test/app/src/main/cpp/native-lib.cpp:1:
  In file included from /Volumes/DATA/android-sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h:28:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h:52:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types.h:33:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
  #error architecture not supported
   ^
  In file included from /Users/dd/tmp/ndk-test/app/src/main/cpp/native-lib.cpp:1:
  In file included from /Volumes/DATA/android-sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h:28:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h:52:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
  typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
          ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'
  typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
          ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'
  typedef __int32_t       __darwin_dev_t;         /* dev_t */
          ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean 'uint32_t'?
  typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
          ^
  ......
          ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'
  typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
          ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean 'uint32_t'?
  typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
          ^
  ......
          ^
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
  ninja: build stopped: subcommand failed.
```

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 20.0.5594570.
* Build system: CMake
* Host OS: Mac
* ABI: 'armeabi-v7a', 'arm64-v8a'
* NDK API level:
* Device API level:
* Xcode version: Version 11.0 (11A420a)

**Comment by rkeniger** [comment] 2019-10-26 05:09
I'm having exactly the same issue with Xcode 11.1.

**Comment by POTION4** [comment] 2019-11-18 05:07
Er, has this been fixed? I still got this issue.

**Comment by DanAlbert** [comment] 2019-11-18 05:43
Haven't had a chance to look yet.

**Comment by POTION4** [comment] 2019-11-18 08:11
@DanAlbert Please look into it if you had chance, thanks!! I need it for my homework :P

Also here's a temp solution for everyone (even though I don't really know how my changes will impact the code):

For some reason, overriding Xcode's default include path is impossible (maybe this is also the reason why this broke?). So first we need to move the Xcode include directory away (so clang could not find that directory): 

```sh
cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr
sudo mv include include.bak
```

Then modify ~/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/bits/signal_types.h as follows (because this fails my compilation): 

```c
94| struct sigaction { /* __SIGACTION_BODY */ };
95| struct sigaction64 { /* __SIGACTION_BODY */ };
```

And finally, in the CMakeLists.txt of your android project, add the include directory in whatever way you wish.

```cmake
include_directories(BEFORE SYSTEM "/Users/$USER/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include")
```

(I used `BEFORE SYSTEM`, however it does not work at all. So you may as well remove it.)

**Comment by DanAlbert** [comment] 2019-11-18 08:54
> For some reason, overriding Xcode's default include path is impossible (maybe this is also the reason why this broke?). So first we need to move the Xcode include directory away (so clang could not find that directory):

Any idea if that's caused by cmake or by clang? We haven't seen this elsewhere, so I wonder if it's maybe caused by the version of CMake being used? OP is using 3.10 from the SDK. Which version are you using?

> And finally, in the CMakeLists.txt of your android project, add the include directory in whatever way you wish.

That definitely shouldn't be required, and definitely points to CMake being the cause of the bug rather than Clang.

**Comment by POTION4** [comment] 2019-11-18 09:15
@DanAlbert Sorry, that was not required. That was just my desperate attempt to override the default system include search path. I must've forgotten about that...

Also, I use CMake version 3.4.1. I think it's been caused by clang, because for some reason, header overriding in clang does not work anymore. Even adding

```cmake
include_directories(BEFORE SYSTEM "/Users/$USER/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include")
```

in cmake doesn't work:

<img width="572" alt="Capture d’écran 2019-11-18 à 5 14 07 PM" src="https://user-images.githubusercontent.com/4988733/69039458-ea0d5a00-0a26-11ea-8a82-96ce3ba9b44e.png">

**Comment by DanAlbert** [comment] 2019-11-18 18:04
What's the actual clang command line being used here? Any includes that are on the command line should be taking precedence over those that clang adds automatically, so it looks more like CMake it just ignoring your "before system", or maybe an `include_next` is misbehaving.

**Comment by 42yeah** [comment] 2019-11-19 07:44
@DanAlbert Here's the build command of mine:

```sh
/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi16 --gcc-toolchain=/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -Dnative_lib_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -std=c++11 -I /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/files.cpp.o -MF CMakeFiles/native-lib.dir/files.cpp.o.d -o CMakeFiles/native-lib.dir/files.cpp.o -c /Users/apple/Projects/3DSnooker/app/src/main/cpp/files.cpp
```

Even with the -I, clang chose Xcode toolchain first. That's weird, because I tested it with a file: 

```c
#include <sys/cdefs.h>

#ifndef __RENAME_IF_FILE_OFFSET64
#error Nope not the right header
#endif

int main() {
    return 0;
}
```

And compiled it with: 

```sh
clang include.c -I /Users/$USER/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include
```

Nothing's wrong.

**Comment by 42yeah** [comment] 2019-11-19 07:52
Also is cmake ignoring `include_directories`? Here's my CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.4.1)
include_directories(BEFORE SYSTEM "/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
add_library( 
        native-lib
        SHARED
        native-lib.cpp
        files.cpp
        gl_helpers.cpp
        model.cpp)
find_library( 
        log-lib
        log)
target_link_libraries(
        native-lib
        GLESv2
        EGL
        android
        ${log-lib})
```

And here's the output: 

```sh
/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi16 --gcc-toolchain=/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -Dnative_lib_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -std=c++11 -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/files.cpp.o -MF CMakeFiles/native-lib.dir/files.cpp.o.d -o CMakeFiles/native-lib.dir/files.cpp.o -c /Users/apple/Projects/3DSnooker/app/src/main/cpp/files.cpp
```

There is no `-I` whatsoever. The reason -I appeared in my previous comment is I added it manually in `CMAKE_CXX_FLAGS`.

**Comment by 42yeah** [comment] 2019-11-19 08:06
@DanAlbert Seems like the problem is `--target=armv7-none-linux-androideabi16`:

```sh
/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -std=c++11 -I /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include -O0 -fno-limit-debug-info include.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]

❯
```

```sh
/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi16  -std=c++11 -I /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include -O0 -fno-limit-debug-info include.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
In file included from include.c:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:807:2: error:
      Unsupported architecture
#error Unsupported architecture
 ^
include.c:4:2: error: Nope not the right header
#error Nope not the right header
 ^
2 errors generated.

❯
```

**Comment by DanAlbert** [comment] 2019-11-19 08:31
Without the `-target` flag you're building for Mac, not Android.

That sure looks like a Clang bug. Strange that we didn't see it in our own testing (maybe none of the machines we tested with had xcode installed, or maybe it's something new with Catalina?).

Have you (or anyone else seeing this) tried with the r21 beta?

**Comment by 42yeah** [comment] 2019-11-19 10:09
@DanAlbert Yeah, so that's nasty. I haven't tried yet, and will let you know ASAP.

**Comment by 42yeah** [comment] 2019-11-19 10:52
Nope, didn't work. Using NDK (Side by side) 21.0.5935234 (revision: 21.0.5935234):

- build command: 

```sh
/Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi16 --gcc-toolchain=/Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -Dnative_lib_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -std=c++11 -I /Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/files.cpp.o -MF CMakeFiles/native-lib.dir/files.cpp.o.d -o CMakeFiles/native-lib.dir/files.cpp.o -c /Users/apple/Projects/3DSnooker/app/src/main/cpp/files.cpp
```

- error: Unsupported Architecture
- partial cmake file:

```cmake
cmake_minimum_required(VERSION 3.4.1)
include_directories(BEFORE SYSTEM "/Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -I /Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include")
```

**Comment by pirama-arumuga-nainar** [comment] 2019-11-19 17:46
> ```shell
> /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi16  -std=c++11 -I /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include -O0 -fno-limit-debug-info include.c

Can you run this with `-v`?  Clang is definitely adding the XCode include paths but finding the exact invocation may help narrow down the issue in the driver.

Does `-nostdinc` help by any chance?  My guess is that it may skip adding the XCode headers but will also skip the NDK system headers.

**Comment by 42yeah** [comment] 2019-11-20 00:15
@pirama-arumuga-nainar Here's the output with `-v`: 

```sh
Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: armv7-none-linux-android16
Thread model: posix
InstalledDir: /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin
Found candidate GCC installation: /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x
Selected GCC installation: /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x
Candidate multilib: thumb;@mthumb
Candidate multilib: armv7-a;@march=armv7-a
Candidate multilib: armv7-a/thumb;@march=armv7-a@mthumb
Candidate multilib: .;
Selected multilib: armv7-a;@march=armv7-a
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
 "/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++" -cc1 -triple armv7-none-linux-android16 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name include.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +soft-float-abi -target-feature -fp-only-sp -target-feature +d16 -target-feature +vfp3 -target-feature -fp16 -target-feature -vfp4 -target-feature -fp-armv8 -target-feature -neon -target-feature -crypto -target-abi aapcs-linux -mfloat-abi soft -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -target-linker-version 241.9 -v -resource-dir /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/8.0.7 -I /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -internal-isystem /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1 -internal-isystem /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/local/include -internal-isystem /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/8.0.7/include -internal-externc-isystem /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/arm-linux-androideabi -internal-externc-isystem /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/include -internal-externc-isystem /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include -fdeprecated-macro -fdebug-compilation-dir /Users/apple/Projects/SF -ferror-limit 19 -fmessage-length 100 -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/tq/00ytq8l56vg4gxfvrh_nrgq40000gn/T/include-972537.o -x c++ include.c -faddrsig
clang -cc1 version 8.0.7 based upon LLVM 8.0.7svn default target x86_64-apple-darwin19.0.0
ignoring nonexistent directory "/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/include"
ignoring duplicate directory "/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
 /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1
 /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/local/include
 /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/8.0.7/include
 /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/arm-linux-androideabi
 /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include
End of search list.
In file included from include.c:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:807:2: error:
      Unsupported architecture
#error Unsupported architecture
 ^
include.c:4:2: error: Nope not the right header
#error Nope not the right header
 ^
2 errors generated.
```

Sorry I am a little busy right now so there are no time for me to look into it however it is clear that the -I fails to override the system include directory. Which is weird, because it shouldn't work that way.

`-nostdinc` works in command line, however it fails at Android Studio. Here are the logs: 

##### Terminal

```sh
Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: armv7-none-linux-android16
Thread model: posix
InstalledDir: /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin
Found candidate GCC installation: /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x
Selected GCC installation: /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x
Candidate multilib: thumb;@mthumb
Candidate multilib: armv7-a;@march=armv7-a
Candidate multilib: armv7-a/thumb;@march=armv7-a@mthumb
Candidate multilib: .;
Selected multilib: armv7-a;@march=armv7-a
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
 "/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++" -cc1 -triple armv7-none-linux-android16 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name include.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +soft-float-abi -target-feature -fp-only-sp -target-feature +d16 -target-feature +vfp3 -target-feature -fp16 -target-feature -vfp4 -target-feature -fp-armv8 -target-feature -neon -target-feature -crypto -target-abi aapcs-linux -mfloat-abi soft -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -target-linker-version 241.9 -v -nostdsysteminc -nobuiltininc -resource-dir /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/8.0.7 -I /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -internal-isystem /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1 -fdeprecated-macro -fdebug-compilation-dir /Users/apple/Projects/SF -ferror-limit 19 -fmessage-length 100 -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/tq/00ytq8l56vg4gxfvrh_nrgq40000gn/T/include-be7e5e.o -x c++ include.c -faddrsig
clang -cc1 version 8.0.7 based upon LLVM 8.0.7svn default target x86_64-apple-darwin19.0.0
#include "..." search starts here:
#include <...> search starts here:
 /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
 /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/include/c++/v1
End of search list.
 "/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld" -pie -EL -z now -z relro -X --hash-style=both --enable-new-dtags --eh-frame-hdr -m armelf_linux_eabi -dynamic-linker /system/bin/linker -o a.out /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/lib/arm-linux-androideabi/16/crtbegin_dynamic.o -L/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/8.0.7/lib/linux/arm -L/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/armv7-a -L/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/../lib/armv7-a -L/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/lib/arm-linux-androideabi/16 -L/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/lib/arm-linux-androideabi -L/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/lib/../lib -L/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/lib/arm-linux-androideabi/../../lib -L/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/armv7-a -L/Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/lib /var/folders/tq/00ytq8l56vg4gxfvrh_nrgq40000gn/T/include-be7e5e.o -lc++ -lm -lgcc -ldl -lc -lgcc -ldl /Users/apple/Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/bin/../sysroot/usr/lib/arm-linux-androideabi/16/crtend_android.o
```

##### Android Studio

```sh
FAILED: /Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi16 --gcc-toolchain=/Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -Dnative_lib_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -std=c++11 -nostdinc -I /Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/files.cpp.o -MF CMakeFiles/native-lib.dir/files.cpp.o.d -o CMakeFiles/native-lib.dir/files.cpp.o -c /Users/apple/Projects/3DSnooker/app/src/main/cpp/files.cpp
In file included from /Users/apple/Projects/3DSnooker/app/src/main/cpp/files.cpp:5:
In file included from /Users/apple/Projects/3DSnooker/app/src/main/cpp/files.h:9:
In file included from /Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/android/asset_manager.h:30:
In file included from /Users/apple/Library/Android/sdk/ndk/21.0.5935234/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/sys/types.h:32:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stddef.h:64:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_types.h:27:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/_types.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
#error architecture not supported
```

Looks like even without `-nostdinc`, Xcode headers are still being added.

**Comment by pirama-arumuga-nainar** [comment] 2019-11-20 00:37
@42yeah Do you have `CPATH` environment variable set, by any chance?

**Comment by stephenhines** [comment] 2019-11-20 03:39
Can you look at your environment variables? Is something like `SDKROOT` set? I saw something Darwin-specific about that in Clang, but didn't get to look further today.

**Comment by 42yeah** [comment] 2019-11-20 07:26
@pirama-arumuga-nainar Oh yeah... Now that you mention about it...

<img width="553" alt="Capture d’écran 2019-11-20 à 3 21 51 PM" src="https://user-images.githubusercontent.com/4988733/69217363-7ba4d500-0ba9-11ea-8355-01a17e596fa0.png">

When a newer version of Xcode came out, this was told to be the fix of the autocomplete errors, so I added it in my `.zshrc`... Sorry for all those ruckus caused! Removing this line solved all the problems.

**Comment by sinfere** [comment] 2019-11-20 10:23
Great!!! it works

**Comment by DanAlbert** [comment] 2019-11-20 12:22
Glad we have a workaround. Thanks a bunch @42yeah for the help with the diagnosis. I want to take a closer look before we close this for sure, but this looks like the fix is just "don't do that" and there's no reasonable clang change we can make here.

**Closed** 2020-05-28 21:05 UTC
Labels: bug
