### ISSUE TITLE
[Bug]: No support for std::derived_from concept

### ISSUE THREAD

**Issue by SarkisKhachatryan** [android/ndk#1808] opened 2022-11-21 13:42 UTC
### Description

when trying to use `std::derived_from` concept, getting this error.

```
error: no template named 'derived_from' in namespace 'std'
      template <std::derived_from<smth> T>
```

### Affected versions

r25

### Host OS

Linux

### Host OS version

Ubuntu 20.04

### Affected ABIs

arm64-v8a

**Comment by SarkisKhachatryan** [comment] 2022-11-21 13:48
As a workaround, added this code snippet to use it for now
```
template <class Derived, class Base>
concept derived_from = std::is_base_of_v<Base, Derived> &&
    std::is_convertible_v<const volatile Derived*, const volatile Base*>;
```

this works fine

**Comment by DanAlbert** [comment] 2022-11-28 21:33
Any reason to believe this isn't a duplicate of the pinned issue https://github.com/android/ndk/issues/1530?

**Comment by DanAlbert** [comment] 2022-12-12 19:55
Closing for lack of feedback. Probably a dup.

**Closed by DanAlbert** 2022-12-12 19:55 UTC
Labels: bug

**Comment by SarkisKhachatryan** [comment] 2022-12-26 10:19
Sure, thanks
