### ISSUE TITLE
[BUG] New cmake toolchain does not correct ANDROID_PLATFORM value

### ISSUE THREAD

**Issue by DoDoENT** [android/ndk#1588] opened 2021-09-22 16:43 UTC
#### Description

I'm not sure if that is an NDK or Android Gradle plugin bug - probably a bit of both.

WIth legacy toolchain, when `android-16` was selected as `ANDROID_PLATFORM` and `arm64-v8a` as `ANDROID_ABI`, the toolchain corrected the `ANDROID_PLATFORM` value to `android-21`, as 64-bit platforms are supported only from Android API 21.

This is problematic as Android Gradle Plugin 7.0.2 (bundled with Android Studio Arctic Fox) invokes cmake with `ANDROID_ABI` equal to `minSdkVersion` for all ABIs. So, when configuring an app with `minSdkVersion` set to `16` with no set `abiFilters` (or having at least one 64-bit ABI), cmake configuration fails with following error:

```
  -- Check for working C compiler: /Users/dodo/.conan/data/AndroidNdk/r23/microblink/stable/package/743cf0321be3152777da4d05247a66d1552e70a2/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
  -- Check for working C compiler: /Users/dodo/.conan/data/AndroidNdk/r23/microblink/stable/package/743cf0321be3152777da4d05247a66d1552e70a2/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - broken
  -- Configuring incomplete, errors occurred!
  See also "/Users/dodo/Work/Microblink/Builds/core-utils/clang/dev-release/CoreUtilsTest-android-studio/app/.cxx/Release/c2p1z626/arm64-v8a/CMakeFiles/CMakeOutput.log".
  See also "/Users/dodo/Work/Microblink/Builds/core-utils/clang/dev-release/CoreUtilsTest-android-studio/app/.cxx/Release/c2p1z626/arm64-v8a/CMakeFiles/CMakeError.log".

  CMake Error at /Applications/CMake.app/Contents/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
    The C compiler

      "/Users/dodo/.conan/data/AndroidNdk/r23/microblink/stable/package/743cf0321be3152777da4d05247a66d1552e70a2/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: /Users/dodo/Work/Microblink/Builds/core-utils/clang/dev-release/CoreUtilsTest-android-studio/app/.cxx/Release/c2p1z626/arm64-v8a/CMakeFiles/CMakeTmp

      Run Build Command(s):/usr/local/bin/ninja cmTC_fa1e9 && [1/2 ?/sec] Building C object CMakeFiles/cmTC_fa1e9.dir/testCCompiler.c.o
      [2/2 91.8/sec] Linking C executable cmTC_fa1e9
      FAILED: cmTC_fa1e9
      : && /Users/dodo/.conan/data/AndroidNdk/r23/microblink/stable/package/743cf0321be3152777da4d05247a66d1552e70a2/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=aarch64-none-linux-android16 --sysroot=/Users/dodo/.conan/data/AndroidNdk/r23/microblink/stable/package/743cf0321be3152777da4d05247a66d1552e70a2/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions  -O2 -g -DNDEBUG -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Qunused-arguments -Wl,--no-undefined  -Wl,--gc-sections CMakeFiles/cmTC_fa1e9.dir/testCCompiler.c.o -o cmTC_fa1e9  -latomic -lm && :
      ld: error: cannot open crtbegin_dynamic.o: No such file or directory
      ld: error: cannot open crtend_android.o: No such file or directory
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ninja: build stopped: subcommand failed.





    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:3 (project)
```

By using legacy toolchain or by setting `minSdkVersion` to `21` or above, the problem is gone.

Although the AGP clearly invokes CMake in a wrong manner, I think this should also be fixed on the NDK side because it should be possible to use NDK r23 with an older Gradle plugin (Android Studio 4 and earlier) that is not aware of the new cmake toolchain file in NDK r23.

#### Environment Details

* NDK Version: r23
* Build system: CMake
* Host OS: happens on both MacOS and Linux (haven't tested on Windows, but due to a nature of the issue, it should be reproducible there as well)
* ABI: arm64-v8a
* NDK API level: 16

Sample project that demonstrates the issue is attached here: 
[ndkr23bug.zip](https://github.com/android/ndk/files/7212473/ndkr23bug.zip)

**Comment by DanAlbert** [comment] 2021-09-22 18:43
Duplicate of #1560

**Closed by DanAlbert** 2021-09-22 18:43 UTC
Labels: bug
