### ISSUE TITLE
Android builds, .so files are not stack canary protected and the binary does not have any fortified functions

### ISSUE THREAD

**Issue by muralitharana** [android/ndk#2085] opened 2024-10-08 11:26 UTC
### Description

Please help!!

Existing issues are closed related to this

[36870](https://github.com/facebook/react-native/issues/36870)
[46537](https://github.com/facebook/react-native/issues/46537)

Continuation of issue: 46537

Tried with React Native 0.76.0-rc.1 but this issue is Android NDK Specific, Still I can see on these files, binary does not have a stack canary value and not have any fortified functions. These files are created by NDK system

1. armeabiv7a/libc++_shared.so
2. arm64-v8a/libc++_shared.so
3. armeabiv7a/libc++_shared.so
4. x86/libc++_shared.so
5. x86_64/libc++_shared.so

**Steps to reproduce** 
1. create a fresh react native project using 0.76.0-rc.1
2. create an Android release build
3. static analysis of apk using MobSF

### Affected versions

r28

### Host OS

Mac

### Host OS version

macOS 14.5

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

ndk-build

### minSdkVersion

26

**Comment by DanAlbert** [comment] 2024-10-08 18:39
Duplicate of #2072.

**Closed by DanAlbert** 2024-10-08 18:39 UTC
Labels: bug

**Comment by muralitharana** [comment] 2024-10-09 04:24
Thanks @DanAlbert Hoping for the resolution.
