### ISSUE TITLE
[BUG] `clang.cmd` doesn't work well with `-march=armv7-a`

### ISSUE THREAD

**Issue by Berrysoft** [android/ndk#1856] opened 2023-03-30 13:01 UTC
### Description

I've installed NDK 25.2.9519653 and want to work with rust. However, the content of `*-*-*-clang.cmd` causes issues. The content of such cmd script is:

``` cmd
@echo off
setlocal
call :find_bin
if "%1" == "-cc1" goto :L

set "_BIN_DIR=" && "%_BIN_DIR%clang.exe" --target=armv7a-linux-androideabi24 %*
if ERRORLEVEL 1 exit /b 1
goto :done

:L
rem Target is already an argument.
set "_BIN_DIR=" && "%_BIN_DIR%clang.exe" %*
if ERRORLEVEL 1 exit /b 1
goto :done

:find_bin
rem Accommodate a quoted arg0, e.g.: "clang"
rem https://github.com/android-ndk/ndk/issues/616
set _BIN_DIR=%~dp0
exit /b

:done
```

The fourth line, `if "%1" == "-cc1" goto :L`, causes issues. Rust put a param `"-march=armv7-a"` with armv7a target, and cmd will throw error

```
=armv7-a"" was unexpected at this time.
```

That's because the line is interpreted as `if ""-march=armv7-a"" == "-cc1" goto :L`. When I comment out this line, it works well.

### Affected versions

r25

### Host OS

Windows

### Host OS version

Windows 11

### Affected ABIs

armeabi-v7a

### Build system

ndk-build

### minSdkVersion

24

**Comment by DanAlbert** [comment] 2023-03-30 20:05
@rprichard could you look at this for r26? I think you understand the cmd stuff better than the rest of us.

**Comment by rprichard** [comment] 2023-03-30 21:01
Maybe `EnableDelayedExpansion` would help?

https://stackoverflow.com/a/26079381

> ```
> @echo off
> SetLocal EnableDelayedExpansion
>
> :: Test empty string
> set Lhs=
> set Rhs=
> echo Lhs: !Lhs! & echo Rhs: !Rhs!
> if !Lhs! == !Rhs! (echo Equal) else (echo Not Equal)
> echo.
>
> :: Test symbols
> set Lhs= \ / : * ? " ' < > | %% ^^ ` ~ @ # $ [ ] & ( ) + - _ =
> set Rhs= \ / : * ? " ' < > | %% ^^ ` ~ @ # $ [ ] & ( ) + - _ =
> echo Lhs: !Lhs! & echo Rhs: !Rhs!
> if !Lhs! == !Rhs! (echo Equal) else (echo Not Equal)
> echo.
> ```

I wonder if our wrappers can forward arguments containing special characters, like `%`, `!`, `^`, `"`...

**Comment by leleliu008** [comment] 2023-05-04 08:17
I encounered this when building [libvpx](https://github.com/webmproject/libvpx)

```
    [AS] vpx_dsp/arm/intrapred_neon_asm.asm.S.o
    [AS] vpx_dsp/arm/vpx_convolve_copy_neon_asm.asm.S.o
    [AS] vpx_dsp/arm/vpx_convolve8_horiz_filter_type2_neon.asm.S.o
    [AS] vpx_dsp/arm/vpx_convolve8_vert_filter_type2_neon.asm.S.o
llvm-asllvm-as: Unknown command line argument ': Unknown command line argument '-march=armv7-a-march=armv7-a'.  Try: ''.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-as: Did you mean '--llvm-asd=armv7-a'?
 --help'
llvm-as: Unknown command line argument '-mfloat-abi=softfp'.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-as: Did you mean ': Unknown command line argument '--module-hash=softfp'?
llvm-asllvm-as: Unknown command line argument '-mfpu=neon-march=armv7-a'.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as'.  Try: ' --help'
/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as: Did you mean 'llvm-as: Did you mean ' --help'
--f=neon--llvm-asd=armv7-a'?
: Did you mean '--d=armv7-allvm-as: Unknown command line argument ''?
'?
-I./'.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-asllvm-as: Unknown command line argument ': Did you mean '-mfloat-abi=softfp-'.  Try: 'd/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as'?
 --help'
llvm-as: Unknown command line argument 'llvm-as: Did you mean '--module-hash=softfp'?
-mfloat-abi=softfpllvm-as: Unknown command line argument '-mfpu=neonllvm-as'.  Try: ': Unknown command line argument ''.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
-I/home/leleliu008/.ndk-pkg/installing/android-21/armeabi-v7a/libvpx/src/'.  Try: ' --help'
/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-asllvm-as: Did you mean 'llvm-as--f=neon: Did you mean ''?
--: Did you mean 'llvm-asllvm-as: Unknown command line argument 'help-list-hidden-I./'?
'.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as-- --help'
module-hash=softfpllvm-as'?
: Did you mean '-d'?
llvm-as: Unknown command line argument '-mfpu=neon'.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-as: Did you mean '--f=neon'?
llvm-asllvm-as: Unknown command line argument '-I/home/leleliu008/.ndk-pkg/installing/android-21/armeabi-v7a/libvpx/src/'.  Try: ': Unknown command line argument '-I.//home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-as: Did you mean '--'.  Try: 'help-list-hidden'?
/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-as: Did you mean '-d'?
llvm-as: Unknown command line argument '-I/home/leleliu008/.ndk-pkg/installing/android-21/armeabi-v7a/libvpx/src/'.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-as: Did you mean '--help-list-hidden'?
: Unknown command line argument '-march=armv7-a'.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-as: Did you mean '--d=armv7-a'?
llvm-as: Unknown command line argument '-mfloat-abi=softfp'.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-as: Did you mean '--module-hash=softfp'?
llvm-as: Unknown command line argument '-mfpu=neon'.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-as: Did you mean '--f=neon'?
gmake[1]: *** [Makefile:210: vpx_dsp/arm/intrapred_neon_asm.asm.S.o] Error 1
llvm-as: Unknown command line argument '-I./'.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-as: Did you mean '-d'?
llvm-as: Unknown command line argument '-I/home/leleliu008/.ndk-pkg/installing/android-21/armeabi-v7a/libvpx/src/'.  Try: '/home/leleliu008/Downloads/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as --help'
llvm-as: Did you mean '--help-list-hidden'?
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: *** [Makefile:210: vpx_dsp/arm/vpx_convolve_copy_neon_asm.asm.S.o] Error 1
gmake[1]: *** [Makefile:210: vpx_dsp/arm/vpx_convolve8_horiz_filter_type2_neon.asm.S.o] Error 1
gmake[1]: *** [Makefile:210: vpx_dsp/arm/vpx_convolve8_vert_filter_type2_neon.asm.S.o] Error 1
gmake: *** [Makefile:17: .DEFAULT] Error 2

```

**Comment by rib** [comment] 2023-05-16 17:54
I also just arrived at the same workaround as @vbieleny

**Comment by MarijnS95** [comment] 2023-05-16 22:26
Isn't the idea to ditch the `.cmd` scripts and invoke `clang` directly, as per https://android-review.googlesource.com/c/platform/ndk/+/2134712?

**Comment by rib** [comment] 2023-05-17 07:01
> Isn't the idea to ditch the `.cmd` scripts and invoke `clang` directly, as per https://android-review.googlesource.com/c/platform/ndk/+/2134712?

At least for my current use case i'm using the toolchain via cargo/rustc and I'm not sure if there's any practical way yet to specify the target api level via cargo afaik? (adding the api level suffix wouldn't be a valid target name for rust) so at least for now it's still useful to have these wrappers.

**Comment by MarijnS95** [comment] 2023-05-17 08:13
In [`ndk-build` we provide that via `C(XX)FLAGS` and `RUSTFLAGS`](https://github.com/rust-mobile/ndk/pull/306). `cargo-apk` selects the API level via the manifest (and some other sources such as latest installed SDK?), `cargo-ndk` seems to pull it from cmdline.

**Comment by DanAlbert** [comment] 2023-05-17 23:00
> > Isn't the idea to ditch the `.cmd` scripts and invoke `clang` directly, as per https://android-review.googlesource.com/c/platform/ndk/+/2134712?
> 
> At least for my current use case i'm using the toolchain via cargo/rustc and I'm not sure if there's any practical way yet to specify the target api level via cargo afaik? (adding the api level suffix wouldn't be a valid target name for rust) so at least for now it's still useful to have these wrappers.

`CC="clang -target aarch64-linux-android24"`. You only need the wrappers in the rare cases where you're using a system that's going to fumble when escaping that. They're rare but I've seen it happen in not-actually-autoconf-but-almost projects.

**Comment by MarijnS95** [comment] 2023-05-17 23:08
Rust unfortunately seems to be rare in how we can provide the linker... by needing a different nontrivial environment var (`RUSTFLAGS` with all kinds of mutual exclusivity with user-settable config files) to add this extra arg (https://github.com/rust-mobile/ndk/pull/306/files#diff-33520aaf2e3ca2264c50b4159237131b9804b93d42e50b2276a281da69567b8bR41-R42).

I wonder if we could have added it to [the `LINKER` env var](https://github.com/rust-mobile/ndk/pull/306/files#diff-33520aaf2e3ca2264c50b4159237131b9804b93d42e50b2276a281da69567b8bR35-R37) directly and do away with all this hassle, like you suggest for `CC`.

**Comment by rib** [comment] 2023-05-18 11:33
> I wonder if we could have added it to [the LINKER env var](https://github.com/rust-mobile/ndk/pull/306/files#diff-33520aaf2e3ca2264c50b4159237131b9804b93d42e50b2276a281da69567b8bR35-R37) directly and do away with all this hassle, like you suggest for CC.

Just for reference, I gave this a try and cargo expects to be able to resolve the `_LINKER` to an absolute path and so it didn't work to try and add the target argument to the `_LINKER` environment variable. Also just conceptually; without something similar to `CARGO_ENCODED_RUSTFLAGS` it would be awkward to deal with paths that have spaces, in conjunction with arguments.

Unfortunately right now it looks like it's very difficult to pass `--target` to Clang when cross compiling Rust crates with Cargo without risking trampling the user's own rustflags.

As discussed here https://github.com/bbqsrc/cargo-ndk/issues/104#issuecomment-1552716328; tools such as `cargo ndk`, `cargo apk` and `xbuild` have no real hope of being able to determine the rustflags that have been configured by the user and so they can't add the required `-Clink-arg=` to add the `--target` to the rustflags without potentially trampling the user's own configuration of rustflags.

Unfortunately that means that the solution [mentioned above](https://github.com/android/ndk/issues/1856#issuecomment-1550954433) for `ndk-build` isn't compatible with Rust projects that configure rustflags via Cargo. The current project I'm working with, for example, configures rustflags via `.cargo/config.toml`

The best solution for Rust projects would probably be to look at adding `cargo ndk` functionality to `cargo` itself, considering that cargo is the only thing that can really extend rustflags reliably.

Alternatively I think Cargo and the `cc` crate would need to offer some alternative ways of specifying a linker, with flags that can be used by tools like `cargo ndk` / `ndk-build` that won't trample the user's configured rustflags. E.g. Cargo could potentially support a `CARGO_ENCODED_<target>_LINKER` that could accept arguments for the linker too.

Without something like that then I think we need to continue using these `.cmd` wrappers with Rust and we also need to patch them to fix this bug because rustc seems to be passing arguments to the linker with quotes (E.g. we see this with `-Wl,--version-scripts` created by rustc)

One other approach I may investigate is to treat `cargo-ndk` as a `RUSTC_WRAPPER` on Windows so we can handle adding the `-Clink-arg=` at a point where all the rustflags should have been resolved by Cargo. This will likely make builds noticeably slower on Windows if it works since it will add a redundant `CreateProcess` for every rustc invocation.

**Comment by leleliu008** [comment] 2023-05-18 13:45
for package manager developers and build system developers, maybe write your own wrapper in C API is a best choice.

here is a example I'm using https://github.com/leleliu008/ndk-pkg/blob/master/proxy-cc.c

write your own wrapper, you can do many things. let's show us some examples:

1. fix bugs. for exmaple, checking if `--Wl,--soname,libxx.so` is passed, if not, adding it. as discussed in https://github.com/android/ndk/issues/1865
2. generate `compile_commands.json`
3. do whatever you want

**Comment by DanAlbert** [comment] 2024-01-24 22:28
https://android-review.googlesource.com/c/platform/ndk/+/2925163 incorporates @vbieleny's suggested fix. Thanks! I need to wait for presubmit to finish with it before I can verify it, but I should be able to do that later today.

**Comment by DanAlbert** [comment] 2024-01-24 23:20
Confirmed, fix merged.

**Closed by DanAlbert** 2024-01-24 23:20 UTC
Labels: bug
