### ISSUE TITLE
[BUG] Accessor functions for std::array<T,0> aren't constexpr

### ISSUE THREAD

**Issue by sunnlok** [android/ndk#1630] opened 2021-12-15 12:17 UTC
--------------------------------------------------------------------------------

#### Description

Accessor functions for std::array<T,0> aren't constexpr.
This means that std::array can not be used in a constexpr context if its, for example, used to initialize a span, which might or might not be empty depending on other compile time evaluated factors.

Current implementation:
`_LIBCPP_INLINE_VISIBILITY
    value_type* data() _NOEXCEPT {return reinterpret_cast<value_type*>(__elems_);}
    _LIBCPP_INLINE_VISIBILITY
    const value_type* data() const _NOEXCEPT {return reinterpret_cast<const value_type*>(__elems_);}`

Fixed in LLV since version 11:

[https://github.com/llvm/llvm-project/blob/release/11.x/libcxx/include/array](url)

**Comment by DanAlbert** [comment] 2021-12-15 19:03
Duplicate of #1530

**Closed by DanAlbert** 2021-12-15 19:03 UTC
Labels: bug
