### ISSUE TITLE
[BUG] Global C++ variables' constructors are not called in static executables when using LTO

### ISSUE THREAD

**Issue by topjohnwu** [android/ndk#1461] opened 2021-03-03 07:01 UTC
#### Environment Details

* NDK Version: both `22.0.7026061` and `23.0.7123448-beta1`
* Build system: ndk-build
* Host OS: Mac
* ABI: every ABI
* NDK API level: 21 - 31

#### Reproducible Example

Application.mk
```
APP_ABI := armeabi-v7a x86 arm64-v8a x86_64
APP_CFLAGS := -Oz -flto
APP_LDFLAGS := -flto
APP_CPPFLAGS := -std=c++17
APP_STL := c++_static
APP_PLATFORM := android-30
```

Android.mk
```
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := test
LOCAL_SRC_FILES := test.cpp
LOCAL_LDFLAGS := -static
include $(BUILD_EXECUTABLE)
```

test.cpp
```
struct SideEffectClass {
    SideEffectClass(const char *str) {
        printf("%s\n", str);
    }
};

static SideEffectClass global("global");

int main(int argc, char *argv[]) {
    SideEffectClass local("local");
    return 0;
}
```

- Expected behavior: print `global`, then `local`
- Actual behavior: only `local` was printed

#### Notes

Building as non static executable (removing `-static` in `LOCAL_LDFLAGS`) works just fine.
This issue only occurs when building as static executable.
This issue is reproducible on every single ABI I have tested, and happens regardless of the target API version (tried 21, 30, 31)

**Comment by DanAlbert** [comment] 2021-03-03 07:42
@rprichard I know this is specifically *not* the loader, but is this something you're familiar with? Something wrong in our CRT objects maybe?

**Comment by rprichard** [comment] 2021-03-03 08:49
The code works if I disable LTO. The LTO-generated .init_array entry ends up *after* the NULL terminator in crtend_android.o.

**Comment by rprichard** [comment] 2021-03-03 11:00
Maybe LLD needs to insert the LTO-generated object files into the list of object files, rather than append them to the end? Somehow gold seems to insert its LTO object between crtbegin and crtend. (I'm examining the output of `-Wl,-Map,a.map`.)

This bug doesn't affect glibc. It looks like glibc and musl don't have the -1 header or a NULL terminator in `.init_array`. I think they're using the magic linker symbols, `__{preinit,init,fini}_{start,end}`, which LLD supports (as well as ld.bfd/gold). I believe it's possible to switch Bionic to these, but with some extra complexity for dynamic executables.

This problem also happens with dynamic executables, but only for destructor functions in `.fini_array`. Functions in the `.preinit_array` and `.init_array` tables are instead called by the loader.
```
cat >test.c <<EOF
#include <stdio.h>
__attribute__((destructor)) static void func_dtor() { printf("dtor\n"); }
int main() { return 0; }
EOF
/x/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang test.c
adb push a.out /data/local/tmp
adb shell /data/local/tmp/a.out
/x/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang test.c -flto
adb push a.out /data/local/tmp
adb shell /data/local/tmp/a.out

---

output:
a.out: 1 file pushed, 0 skipped. 20.3 MB/s (5776 bytes in 0.000s)
dtor
a.out: 1 file pushed, 0 skipped. 26.1 MB/s (5808 bytes in 0.000s)
```
Aside: ELF destructor functions aren't used for destructing C++ variables. Instead, when those variables are constructed, there is a call to `__cxa_atexit` to register the destructor.

**Comment by rprichard** [comment] 2021-03-04 07:26
If I interleave non-bitcode and bitcode input object files, then gold seems to insert its LTO object file at the first bitcode input file. (I don't know where in gold this logic is implemented.)
```
CC=/x/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
echo 'void FUNC() {}' >test.c
$CC test.c -c -o test1.o -DFUNC=func1
$CC test.c -c -o test2.o -DFUNC=func2
$CC test.c -c -o test3.o -DFUNC=func3 -flto
$CC test.c -c -o test4.o -DFUNC=func4
$CC test.c -c -o test5.o -DFUNC=func5
$CC test.c -c -o test6.o -DFUNC=func6 -flto
$CC test.c -c -o test7.o -DFUNC=func7
$CC test.c -c -o test8.o -DFUNC=func8
$CC -flto -fuse-ld=gold -O2 -Wl,-Map,a.map -fpic -shared test[12345678].o
cat a.map
```
layout of `.text`:
```
.text           0x0000000000000640       0x5c
 .text          0x0000000000000640       0x3c /x/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/21/crtbegin_so.o
                0x0000000000000654                __atexit_handler_wrapper
                0x000000000000064c                __emutls_unregister_key
                0x0000000000000660                atexit
 .text          0x000000000000067c        0x4 test1.o
                0x000000000000067c                func1
 .text          0x0000000000000680        0x4 test2.o
                0x0000000000000680                func2
 .text          0x0000000000000684        0x0 /tmp/lto-llvm-c4c213.o
 .text.func3    0x0000000000000684        0x4 /tmp/lto-llvm-c4c213.o
                0x0000000000000684                func3
 .text.func6    0x0000000000000688        0x4 /tmp/lto-llvm-c4c213.o
                0x0000000000000688                func6
 .text          0x000000000000068c        0x4 test4.o
                0x000000000000068c                func4
 .text          0x0000000000000690        0x4 test5.o
                0x0000000000000690                func5
 .text          0x0000000000000694        0x4 test7.o
                0x0000000000000694                func7
 .text          0x0000000000000698        0x4 test8.o
                0x0000000000000698                func8
 .text          0x000000000000069c        0x0 /x/android-ndk-r22/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/21/crtend_so.o
```

I see `.init` and `.fini` terminators in the glibc and musl crtn.o files, so if the LTO output has entries for those sections (e.g inline assembly?), then LTO breaks them:
```
$ cat >test.c <<EOF
#include <stdio.h>
void foo() { printf("foo!\n"); }
asm(".section .init,\"ax\",@progbits\ncall foo\n");
int main() {}
EOF
$ /x/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang test.c -O2 -fuse-ld=lld && ./a.out
foo!
$ /x/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang test.c -O2 -fuse-ld=lld -flto && ./a.out
```
The gold behavior seems better to me? (Before I tested it, I also guessed that it might use the last bitcode input.)

**Comment by MaskRay** [comment] 2021-03-05 18:21
This has been reported in https://bugs.llvm.org/show_bug.cgi?id=39390 "for example, ndk crtend_android.o will push 0x0 entry as the last entry in .init_array section."

From the description, I think the -1 or 0 sentinel values should be dropped. They are only needed by legacy .ctors/.dtors sections.

As a workaround, lld/ELF/OutputSections.cpp:isCrtEnd can be adjusted to account for the different crtend names.

Regarding https://bugs.llvm.org/show_bug.cgi?id=39390#c2 , LLD 12 has a mechanism but requires the user to specify the linker script: https://reviews.llvm.org/D91187

> Aside: ELF destructor functions aren't used for destructing C++ variables. Instead, when those variables are constructed, there is a call to __cxa_atexit to register the destructor.

That is to semi support running destructors at dlclose time.
I remember that there are differences with pie and static non-pie programs in glibc...

> If I interleave non-bitcode and bitcode input object files, then gold seems to insert its LTO object file at the first bitcode input file. (I don't know where in gold this logic is implemented.)

https://bugs.llvm.org/show_bug.cgi?id=39390#c7 has more description.
The placement of the LTO object files are not well defined.... (The same in GCC LTO https://sourceware.org/bugzilla/show_bug.cgi?id=27441#c9)
We probably should not expect too much from the behavior.

**Comment by rprichard** [comment] 2021-03-09 08:41
Thanks for the links!

> From the description, I think the -1 or 0 sentinel values should be dropped. They are only needed by legacy .ctors/.dtors sections.

I think we can switch Bionic to using the linker-generated start/end symbols, but we can't entirely drop the sentinels, at least for .fini_array in dynamically-linked executables, because a new executable should work with an old libc.so (which contains Bionic's [__libc_init] and [__libc_fini]). The dynamic loader [ignores the sentinel values](https://android.googlesource.com/platform/bionic/+/6ba27e04dff8ddf9573ded7a176052aff5273ebd/linker/linker_soinfo.cpp#466), and IIRC the loader is responsible for everything except calling the executable's .fini_array functions.

> As a workaround, lld/ELF/OutputSections.cpp:isCrtEnd can be adjusted to account for the different crtend names.

I think this function is currently only used to sort .ctors / .dtors. Other than Bionic, I think there's no need to put crtend* last for *_array, and there's no sorting of .preinit_array at all.

[__libc_init]: https://android.googlesource.com/platform/bionic/+/6ba27e04dff8ddf9573ded7a176052aff5273ebd/libc/bionic/libc_init_dynamic.cpp#137
[__libc_fini]: https://android.googlesource.com/platform/bionic/+/6ba27e04dff8ddf9573ded7a176052aff5273ebd/libc/bionic/libc_init_common.cpp#372

**Comment by yujincheng08** [comment] 2022-01-08 05:17
I need static build with LTO enabled. So my current solution is to write the following linker script:
```
SECTIONS {
  .init_array : {
    *(SORT_BY_INIT_PRIORITY(.init_array.* .ctors.*))
    *(EXCLUDE_FILE(*crtend_android.o) .init_array .ctors)
  }
} INSERT AFTER .fini_array;
SECTIONS {
  .fini_array : {
    *(SORT_BY_INIT_PRIORITY(.fini_array.* .dtors.*))
    *(EXCLUDE_FILE(*crtend_android.o) .fini_array .dtors)
  }
} INSERT BEFORE .init_array;
```

**Comment by DanAlbert** [comment] 2023-04-20 23:49
No changes upstream: https://github.com/llvm/llvm-project/issues/38738

**Comment by rprichard** [comment] 2023-09-01 01:04
@yabinc uploaded a fix for this issue, https://android-review.googlesource.com/c/platform/bionic/+/2725997.

**Comment by DanAlbert** [comment] 2023-09-05 18:54
Even backwards compatible :)

That drops our reliance on an LLVM fix for this, and since we build the NDK's CRT objects directly from bionic, we already have the fix and it'll go out in r27.

**Comment by enh-google** [comment] 2023-09-05 18:59
seems like this is user-visible enough that it should be documented in https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md ?

**Comment by DanAlbert** [comment] 2023-09-05 19:01
@yabinc, could you do that?

**Comment by DanAlbert** [comment] 2023-09-06 23:26
The doc fix: https://r.android.com/2741814

I've added a regression test as well: https://android-review.googlesource.com/c/platform/ndk/+/2743938. I didn't actually see the behavior I expected from the test before applying the fix though. Before I see a segfault. I'm running on different hardware than usual today though so who knows. With the fix applied I do see the expected result.

**Closed by DanAlbert** 2023-09-06 23:26 UTC
Labels: bug
