### ISSUE TITLE
[BUG] Bionic - undefined reference to 'operator new(unsigned int)'

### ISSUE THREAD

**Issue by hypothermic** [android/ndk#1130] opened 2019-11-10 20:58 UTC
#### Description

Compiler gives the following error when building:

```
/usr/local/google/buildbot/src/android/ndk-release-r20/bionic/libc/bionic/locale.cpp:155: error: undefined reference to 'operator new(unsigned int)'
```

Project "app/src/cpp" folder: https://github.com/hypothermic/bionic-bug-repro
Using cmake version 3.10.2 

#### Environment Details

* NDK Version: 20.0.5594570
* Build system: CMake
* Host OS: Ubuntu 18.04 with kernel 4.15
* ABI: arm64-v8a
* NDK API level: 21
* Device API level: 29

**Comment by DanAlbert** [comment] 2019-11-11 08:26
What's in the build.gradle? There's nothing obviously wrong from what I can see in that project, and without the rest of the project we can't reproduce the error.

**Comment by hypothermic** [comment] 2019-11-11 10:58
The repository to the full project: https://github.com/hypothermic/ValaAndroid

**Comment by DanAlbert** [comment] 2019-11-11 18:11
Nothing immediately suspicious there either. I'll try building it later and see what I find.

**Comment by AntonioNoack** [comment] 2019-12-01 06:05
I have the same issue, when trying to compile xmllib2 for Android.
My flags for xmllib: 
#define LIBXML_TREE_ENABLED 1
#define LIBXML_OUTPUT_ENABLED 1
#define LIBXML_SAX1_ENABLED 1
#define HAVE_CTYPE_H 1

**Comment by hypothermic** [comment] 2019-12-02 17:41
@DanAlbert Hi, have you built it?

**Comment by DanAlbert** [comment] 2019-12-02 20:05
I've been out sick for a couple weeks. Haven't had a chance.

**Comment by DanAlbert** [comment] 2020-04-11 00:17
And when I was back I'd totally forgotten about this... sorry about that!

Seems like this is an issue with using the static libc++ with anything that ends up using the locale code in libandroid_support? The linker script for libc++.a is `INPUT(-lc++_static -lc++abi -landroid_support)`, and for libc++.so it's `INPUT(-landroid_support -lc++_shared)`. If the locale.cpp code from libandroid_support ends up being used, it needs new/delete. I think we just need to do the usual linker nonsense of `-lc++_static -lc++abi -landroid_support -lc++_static -lc++abi`, but haven't tested yet (I'm not sure if we can use `--begin-group`/`--end-group` in a linker script).

I'm not sure why this wouldn't show up in testing. I suspect none of our tests use enough of libc++ to end up depending on locale code when using libc++_static?

**Comment by DanAlbert** [comment] 2020-06-08 23:44
https://android-review.googlesource.com/c/platform/ndk/+/1326079 fixes the linker scripts. A bit more testing revealed that this is also fixed by just using LLD since it'll re-search earlier libraries for missing symbols, so this would have gone away for most users in r22 anyway :)

Apparently this has actually been broken since r17. I guess most code does a pretty good job of avoiding `newlocale`? That, or just not many people building for pre-21.

**Closed** 2020-06-09 22:08 UTC
Labels: bug
