### ISSUE TITLE
[BUG] <vector>: std::erase should return size_type, not void

### ISSUE THREAD

**Issue by VioletGiraffe** [android/ndk#1773] opened 2022-10-06 12:58 UTC
### Description

The algorithm `std::erase`, introduced in C++20, must return `size_type`, but NDK 25.0.8775105 returns `void`. Which leads to very annoying compilation errors in cross-platform code that works on a bunch of other Clang, GCC and MSVC platforms.

### Affected versions

r25

### Host OS

Linux, Windows

### Host OS version

Ubuntu 20.04, Windows 10

### Affected ABIs

x86_64

### Build system

CMake

### minSdkVersion

21

### Device API level

32

**Comment by DanAlbert** [comment] 2022-10-06 17:12
Duplicate of #1530

**Closed by DanAlbert** 2022-10-06 17:12 UTC
Labels: bug
