### ISSUE TITLE
[BUG]  'link.txt' has wrong linker for cross-compile

### ISSUE THREAD

**Issue by wkunice** [android/ndk#1350] opened 2020-09-15 03:59 UTC
I am cross compiling C, C++ code using the NDK.
I am using 'cmake' files that first build small static libraries and then links them together to build a single large shared library.
I am using the android.toolchain.cmake file for the CMAKE_TOOLCHAIN_FILE.

When it tries to build the shared library I get errors:
bin/ld: error: no archive symbol table (run ranlib)

I dig down to the build directory and the 'link.txt' file has
"gcc-ar ....."  that generates the library from the .o's.

it should be generating the link.txt file with the cross compiler <....-ar> and <....-ranlib> programs to generate the library.

When I change the 'link.txt file to have:
arm-...-ar library
arm...-ranlib library.a

the shared library link works.

* NDK Version: 21.3
* Build system: cmake
* Host OS: Linux
* ABI:
* NDK API level:
* Device API level:

**Comment by DanAlbert** [comment] 2020-09-16 18:41
We have tests that show linking .a files into shared libraries works fine. There's nothing we can investigate with the information given. Closing, but will reopen if you can provide information that makes it possible for us to help.

I'm not sure what advice to offer, since you already seem to know what the problem is (using the wrong `ar`). Without more information I don't have any guesses as to *why* that's happening :(

**Closed by DanAlbert** 2020-09-16 18:41 UTC
Labels: bug

**Comment by wkunice** [comment] 2020-09-16 21:47
Dan,  
I will get you more information.  In the mean time, can you tell me how the 'link.txt' file gets generated if one is using the cmake with a cross-compile toolchain?

**Comment by DanAlbert** [comment] 2020-09-16 21:57
No idea. We don't generate that. CMake does.

**Comment by DanAlbert** [comment] 2020-09-16 21:58
I guess maybe something to try would be not using make? We never test that, we use ninja. Any difference between those two is probably a CMake bug though.

**Comment by wkunice** [comment] 2020-09-16 22:09
Do the people in charge care the cmake works with the NDK, because they do produce a toolchain file for cross-compiling with the NDK.

**Comment by DanAlbert** [comment] 2020-09-16 22:51
I'm not sure I understand the question? We're happy to help if we can, but we don't have the info needed to do so.

**Comment by wkunice** [comment] 2020-09-17 01:10
Dan,  
I can't give you my build environment (the company won't let me).  So either I or you would need to setup a small project that has 2 or 3 files that each link into a static library and then link those static libraries into a shared library.  We need to use the cmake command with a toolchain file that has the arm64 compiler.

**Comment by DanAlbert** [comment] 2020-09-17 08:32
As I said, we have tests that already do that. It's a CMake script that builds a static library and then links it into a shared library. There's something deeper going on, so we need your help to investigate further.

The most likely explanation is that there is no bug and that something in your project is passing those flags explicitly. grepping for fno-exceptions might answer your question.

**Comment by wkunice** [comment] 2020-09-17 14:15
I am asserting that all the link.txt files generate a "gcc -ar" line.  This doesn't work when cross compiling. Do your tests test this?

**Comment by DanAlbert** [comment] 2020-09-17 17:58
Our tests don't generate that file because they don't use the make generator, but it does not make a similar error for ninja. Our toolchain file does configure AR. If CMake isn't honoring that option when using the mingw makefile generator that's a CMake bug and there's nothing that we can do about it.
