### ISSUE TITLE
[BUG] HeapTaskDaemon thread's stack cannot be decoded correctly since ndk 23.

### ISSUE THREAD

**Issue by dpinthinker** [android/ndk#1675] opened 2022-03-01 11:41 UTC
### Description

Whentring to analysis GC with simpleperf's call graph, I found that the GC thread (HeapTaskDaemon)'s stacks are not decoded correctly.
While it is ok in ndk 22 and before, since ndk 23 begins not working.

Following is the way I am using:

```
cd <ndkpath>/simpleperf
adb shell simpleperf record -g --app com.intel.crtl.GCWA --duration 10 -o /data/perf_GCWA.dat
adb pull /data/perf_GCWA.dat
report_html.py -i perf_GCWA.dat -o perf_GCWA.html
```

Test Case：https://github.com/android-workloads/gcwfa

### Affected versions

r23

### Host OS

Linux

### Host OS version

Ubuntu 18.04.5 LTS

### Affected ABIs

arm64-v8a

### Build system

Other (specify below)

### Other build system

AOSP system build

### minSdkVersion

NA

**Comment by enh-google** [comment] 2022-03-01 17:57
can you show an example of an incorrect decoding? (ideally with the corresponding .dat file?)

**Comment by dpinthinker** [comment] 2022-03-02 01:57
> 

It is reproducable, you can get the incorrect decoding easily by profiling the https://github.com/android-workloads/gcwfa apk.

**Comment by enh-google** [comment] 2022-03-02 02:33
aye, but providing the usual "what i expected"/"what i actually saw" information in your bug report helps move it to the top of the pile... (you already got the "what i did", which is a good start. but right now anyone wanting to look at this needs to check out, build, and run some random github project before they even know what you're _claiming_ is wrong...)

**Comment by dpinthinker** [comment] 2022-03-02 02:47
> aye, but providing the usual "what i expected"/"what i actually saw" information in your bug report helps move it to the top of the pile... (you already got the "what i did", which is a good start. but right now anyone wanting to look at this needs to check out, build, and run some random github project before they even know what you're _claiming_ is wrong...)

Since NDK 23, it looks like below:

![image](https://user-images.githubusercontent.com/2778945/156284703-f200fee1-ffe2-464d-a48c-9e2e10733364.png)

While before NDK 22, it looks like below:

![image](https://user-images.githubusercontent.com/2778945/156284822-a5452dc8-8363-4137-83ab-a2efed9ddf6e.png)


Actualy, I have try to parse the dat file with `simpleperf report -g -i /data/perf_GCWA.dat`, and its result show that dat file has stack info for methods like `CopyingPhase` and `ReclaimPhase`.

For info security, I'm not able to share the dat file. Sorry for that.

**Comment by enh-google** [comment] 2022-03-02 02:52
just to clarify: that's the NDK r22 simpleperf vs the NDK r23 simpleperf on the _same_ .dat file, or two different .dat files? (your "what i did" instructions don't push a simpleperf binary to the device, so i'm not sure what version of simpleperf did the recording, and whether the recording and the reporting simpleperf versions matched or were mixed.)

**Comment by dpinthinker** [comment] 2022-03-02 02:59
> just to clarify: that's the NDK r22 simpleperf vs the NDK r23 simpleperf on the _same_ .dat file, or two different .dat files? (your "what i did" instructions don't push a simpleperf binary to the device, so i'm not sure what version of simpleperf did the recording, and whether the recording and the reporting simpleperf versions matched or were mixed.)

I am working on a root phone, which has built-in simpleperf and is based on [android-12.0.0_r2 simpleperf](https://android.googlesource.com/platform/system/extras/+/refs/tags/android-12.0.0_r2/simpleperf/).

**Comment by enh-google** [comment] 2022-03-02 03:03
hmm... the real simpleperf maintainer will be around tomorrow to say whether that's supported or not. (if it's actually not, we should probably add a check and a visible warning!)

in the meantime have you tried pushing the simpleperf binary from the NDK you're using? (that is: only ever using the same version of simpleperf to record data as you're using to report it later?)

**Comment by dpinthinker** [comment] 2022-03-02 03:07
> hmm... the real simpleperf maintainer will be around tomorrow to say whether that's supported or not. (if it's actually not, we should probably add a check and a visible warning!)
> 
> in the meantime have you tried pushing the simpleperf binary from the NDK you're using? (that is: only ever using the same version of simpleperf to record data as you're using to report it later?)

With pushing the ndk simpleperf binary, it still has the same issue.

**Comment by dpinthinker** [comment] 2022-03-03 06:28
Hi @yabinc @enh-google, Is there any updates?

**Comment by yabinc** [comment] 2022-03-03 18:29
Yeah, I can reproduce the problem. Actually it works as expected.

By default, simpleperf hides ART frames in callstacks when reporting. Because most users don't care ART frames, and too many ART frames affect users viewing app frames.
But you can show ART frames by adding --show_art_frames to report_html.py. This option is also available in some other scripts.
The problem happens in ndk r23, because simpleperf in ndk r23 just got better at hiding ART frames.

**Comment by yabinc** [comment] 2022-03-03 18:34
Simpleperf supports reporting perf.data generated by older versions, but may not support perf.data generated by newer versions. Because I expect NDK on host distributes much faster than Android on device.

**Comment by dpinthinker** [comment] 2022-03-04 01:44
Got it, Thank you @yabinc !

**Comment by dpinthinker** [comment] 2022-03-04 01:57
> But you can show ART frames by adding --show_art_frames to report_html.py. 

Could you also help to add this option to report_sample.py script?

**Comment by yabinc** [comment] 2022-03-08 00:05
Done in https://android-review.googlesource.com/c/platform/system/extras/+/2008381. It will finally be in ndk release, currently you can download it from AOSP at https://android.googlesource.com/platform/system/extras/+/refs/heads/master/simpleperf/scripts/.

**Comment by yabinc** [comment] 2022-03-17 21:59
Sorry, I forgot to add --show-art-frames option to report_sample.py in the previous CL. Now fixed in https://android-review.googlesource.com/c/platform/system/extras/+/2031143/1

**Closed by yabinc** 2022-03-17 21:59 UTC
Labels: bug
