### ISSUE TITLE
[BUG] vget_high_p64 / vmull_p64 crypto feature mismatch

### ISSUE THREAD

**Issue by cajus** [android/ndk#1945] opened 2023-10-06 13:54 UTC
### Description

When doing test builds with NDK r26, I'm running into

```
In file included from ../../source_subfolder/src/libsodium/crypto_aead/aes256gcm/armcrypto/aead_aes256gcm_armcrypto.c:35:
/var/home/ciuser/.conan/data/android_ndk_installer/r26/foo/stable/package/b925f19ad6eb509f29bf6c0a5b52e2a00411ce69/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/include/arm_neon.h:62829:32: error: always_inline function 'vget_high_p64' requires target feature 'crypto', but would be inlined into function 'vmull_high_p64' that is compiled without support for 'crypto'
  __ret = vmull_p64((poly64_t)(vget_high_p64(__p0)), (poly64_t)(vget_high_p64(__p1)));
```

when compiling [libsodium](https://github.com/jedisct1/libsodium/blob/7e3500e878ee5a3a286705ea646a535b33a29cd3/src/libsodium/crypto_aead/aes256gcm/armcrypto/aead_aes256gcm_armcrypto.c#L35) for _arm_ architectures. x86_64 still compiles cleanly as in r25c. I'm not that familiar with these features, but it looks to originate in the NDK.

Any ideas here? Thanks!

### Affected versions

r26

### Host OS

Linux

### Host OS version

Fedora 38

### Affected ABIs

armeabi-v7a, arm64-v8a

### Build system

CMake

### minSdkVersion

23

**Comment by DanAlbert** [comment] 2023-10-06 18:48
> when compiling [libsodium](https://github.com/jedisct1/libsodium/blob/7e3500e878ee5a3a286705ea646a535b33a29cd3/src/libsodium/crypto_aead/aes256gcm/armcrypto/aead_aes256gcm_armcrypto.c#L35) for arm architectures.

Could you elaborate on what you're doing? IME any time we have to guess at build instructions, we waste a bunch of time and fail anyway.

**Comment by DanAlbert** [comment] 2023-10-06 18:49
Specific revision of libsodium too, please. The more guesswork you can eliminate the faster we can diagnose.

**Comment by enh-google** [comment] 2023-10-06 18:51
i think the error is pretty clear, right? "you're trying to build something that requires the crypto extension, but you haven't told the compiler it's okay to use the crypto extension".

(iirc clang did get more strict in this area recently; previously -- for some extensions -- i think it would just silently use them anyway?)

**Comment by cajus** [comment] 2023-10-06 19:30
If you click on the embedded „libsodium“ link, you’re directly pointed to the file with the desired revision.

**Comment by cajus** [comment] 2023-10-06 19:32
Thanks for the answer. As written I’m not 100% familiar with the arm stuff. Will check when I’m back at work - it should add "-march=armv8-a+crypto+aes“ to the CFLAGs, right?

**Comment by DanAlbert** [comment] 2023-10-06 19:33
Note that doing that will make your code incompatible with all devices that don't support that extension (which is why I'm not sure if it's the correct incantation or not; I rarely see it done in apps).

**Comment by enh-google** [comment] 2023-10-06 20:03
yeah, what you probably want is (a) just build that _file_ with the extra extension(s) enabled or (b) do what the error message says and explicitly annotate the relevant _functions_.

typically (for the author of source) option (b) is the best option, because you know that you don't even call that function without having done a runtime check for the extension, and the attribute is the best way to localize where the compiler can/can't use the relevant instructions.

**Comment by cajus** [comment] 2023-10-09 06:08
I've checked my build recipe and the libsodium docs. They say that I've to add `-march=armv8-a+crypto` to the CFLAGS when building for armv8. Did that, and it builds. Will need to check for any effects on the supported devices, though. 

Thanks for your input and sorry for the noise...

**Comment by enh-google** [comment] 2023-10-09 15:28
yeah, like i say --- safest _in general_ is to just add that to the compiler flags _for the file in question_, but in practice for this particular case i'm not aware that the compiler will automatically use _crypto_ instructions unless you're explicitly asking for them via inline assembler or intrinsics, so i think this should be safe. (so please let us know if you find otherwise --- that would be a useful counterexample to know about!)

**Comment by enh-google** [comment] 2023-10-11 19:33
yeah, to expand on appujee's "thumbs up" emoji ... everywhere i said "crypto" above i actually meant "the full set of extensions are actually needed by the code in question" :-)

this one's a bit weird, because "crypto" _includes_ "aes", but i'm guessing the compiler isn't clever enough to know that, so if you say "aes" in one place, you have to say it in the other and vice versa. i guess it's doing string matching rather than expanding them out into sets of subfeatures and doing set arithmetic.

so i think in this case, you could probably also change them all to "aes" (if you're only using the AES subset) or all to "crypto" (if you're using more), or just go with "aes,crypto" if you're just trying to shut the stupid compiler up and/or want to reserve the right to use more of crypto in future.

**Comment by DanAlbert** [comment] 2023-10-11 19:35
I think the snippet above is actually from LLVM's `arm_neon.h` rather than the library's code, right?

**Comment by DanAlbert** [comment] 2023-10-11 19:37
> x86_64 still compiles cleanly as in r25c

Did arm32/arm64 work with r25?

**Comment by martinbonaciugome** [comment] 2023-10-11 19:59
> I think the snippet above is actually from LLVM's `arm_neon.h` rather than the library's code, right?

yes thats from `arm_neon.h`

**Comment by DanAlbert** [comment] 2023-10-11 20:27
And if I've understood @enh-google correctly, he's recommending that `arm_neon.h` start using `"aes,crypto"` instead of just `"aes"`? Assuming that's correct, over to @pirama-arumuga-nainar because LLVM.

**Comment by appujee** [comment] 2023-10-11 20:42
>  because "crypto" includes "aes", 

in that case `__attribute__((target("crypto")))` should also work

**Comment by enh-google** [comment] 2023-10-11 20:52
oh, yeah, i didn't realize that this was an llvm header!

i think in order i'd suggest:
1. file a bug with Arm and let them worry about this.
2. fix llvm to know that "crypto" implies "aes" (amongst other things), so you can write "aes" if you want to be specific for some reason, and this "just works".
3. that specific function appears to just use vmull.p64, which isn't "aes" anyway, so that's just plain wrong? (i don't know whether llvm splits out "pmull" in the same way the kernel/AT_HWCAP does?)
4. yeah, just s/"aes"/"crypto"/ and assume no-one _actually_ has a cpu that has crypto without vmull.p64.

**Comment by pirama-arumuga-nainar** [comment] 2023-10-12 06:09
So, this was a bit puzzling because `vget_high_p64` doesn't require crypto (the rust [documentation](https://doc.rust-lang.org/beta/core/arch/aarch64/fn.vget_high_p64.html) is better in this regard), while [vmull_high_p64](https://doc.rust-lang.org/beta/core/arch/aarch64/fn.vmull_high_p64.html) does require `aes`.

The reason for `vget_high_p64` requiring `crypto` is [this](https://github.com/jedisct1/libsodium/blob/7e3500e878ee5a3a286705ea646a535b33a29cd3/src/libsodium/crypto_aead/aes256gcm/armcrypto/aead_aes256gcm_armcrypto.c#L23C1-L24C1) line in the source in the original report:

> #pragma clang attribute push(__attribute__((target("neon,crypto,aes"))), apply_to = function)

which applies these attributes to any definition that follows.  I couldn't confirm, but it's likely that the `__attribute__((target...))` for `vmull_high_p64` overrides the values in the prior `clang attribute push`.

This worked fine because intrinsics in `arm_neon` were guarded by pre-processor checks for target features.   Recently, `arm_neon.h` functions were annotated with `target` attributes (in order to support FMV... but that's a different topic).  So the `clang attribute push` in `aead_aes256gcm_armcrypto.c` applied to all functions in `arm_neon.h`  - even those that don't require `crypto`.

The fix for this error is to move the `pragma clang attribute push` to after the `#include <arm_neon.h>`.

--------------------------------

> fix llvm to know that "crypto" implies "aes" (amongst other things), so you can write "aes" if you want to be specific for some reason, and this "just works".

LLVM seems to already do this: https://godbolt.org/z/ePhdcvPzf.  Note the `-march=armv8-a+crypto` in the arguments and `+aes` in the emitted LLVM IR.

**Comment by enh-google** [comment] 2023-10-12 18:33
> LLVM seems to already do this: https://godbolt.org/z/ePhdcvPzf. Note the -march=armv8-a+crypto in the arguments and +aes in the emitted LLVM IR.

ah, and reading the error message a bit more carefully, the inlining is in the opposite direction to what i'd assumed above:
```
arm_neon.h:62829:32: error: always_inline function 'vget_high_p64' requires target feature 'crypto', but would be inlined into function 'vmull_high_p64' that is compiled without support for 'crypto'
  __ret = vmull_p64((poly64_t)(vget_high_p64(__p0)), (poly64_t)(vget_high_p64(__p1)));
```
so, yeah, although it required re-reading the error more carefully to understand what he was saying, i fully agree with pirama :-)

**Comment by martinbonaciugome** [comment] 2023-10-12 19:00
i can confirm the pragma in the source file before `#include <arm_neon.h>` is the main issue here

**Comment by DanAlbert** [comment] 2023-10-12 19:30
So no NDK bug here?

**Comment by enh-google** [comment] 2023-10-12 20:28
no, and i don't think there's an llvm one either (unless there's a way for arm_neon.h to protect itself by pushing and popping a "fresh" empty attribute scope for itself?).

**Comment by DanAlbert** [comment] 2023-10-12 20:35
Even if it could I don't know that it should. There are potentially some cases where the caller does actually want to apply pragmas to the included file? I'm really not sure.

**Comment by pirama-arumuga-nainar** [comment] 2023-10-12 20:57
I don't think `arm_neon.h` should do this even if it is possible.

(it's not really possible either, with current attribute syntax.  Setting `pragma clang attribute((__target__))`  to empty would also prevent these functions from inheriting attributes from `-march=`.)

**Closed by pirama-arumuga-nainar** 2023-10-12 20:57 UTC
Labels: bug

**Comment by jonathan-hale-work** [comment] 2024-10-20 17:57
I had this same issue when trying to build libsodium for aarch64 in Termux on Android.

I made the change suggested above. I went into `/data/data/com.termux/files/usr/lib/clang/18/include/arm_neon.h`. On lines 62500 and 62506 I replaced "aes" with "aes,crypto". Now libsodium builds fine 🙂 

I really appreciate the help.
