### ISSUE TITLE
PREBUILT_SHARED_LIBRARY make -n compatibility

### ISSUE THREAD

**Issue by AndreaFiorito** [android/ndk#676] opened 2018-04-23 17:49 UTC
#### Description

https://stackoverflow.com/questions/49985084/skip-prebuilt-library-mk-on-gradle-sync-android-studio

#### Environment Details

latest

**Comment by DanAlbert** [comment] 2018-04-23 18:44
Or a gradle question, at least. Either way, you'll need to ask the Studio team.

**Comment by alexcohn** [comment] 2018-04-24 15:33
Here is a working solution: https://stackoverflow.com/a/50005410/192373

**Comment by alexcohn** [comment] 2018-04-25 14:05
It's enough to modify one line in `prebuilt-library.mk`, to have this piece work as expected:

```
ifndef prebuilt
$(call __ndk_info,ERROR:$(LOCAL_MAKEFILE):$(LOCAL_MODULE): LOCAL_SRC_FILES points to a missing file)
$(call __ndk_info,Check that $(prebuilt_path) exists, or that its path is correct)
###### removed ##### $(call __ndk_error,Aborting)
endif
``` 

Well, if the file is not available at build time, the build fails with an error message which is not easy to interpret. I must confess that I cannot understand the logic towards the end of `prebuilt-library.mk`, where

> If LOCAL_BUILT_MODULE is not defined, then ensure that the prebuilt is
> copied to TARGET_OUT during the build.

**Comment by DanAlbert** [comment] 2018-04-26 17:35
Been giving this some thought since @alexcohn pointed out that this is caused by `make -n`. While I really don't think Studio should be using `make -n` for a handful of reasons, us maintaining compatibility with `make -n` is probably a good goal.

**Comment by alexcohn** [comment] 2018-04-26 19:03
@DanAlbert it's a bit more complicated: `prebuilt-library.mk` was added as an afterthought and require little hacks all the time to do their job reliably (for example, it's use of $wildcard primes the gnu make cache), not necessarily in `-n` scenario. On the other hand, the trouble reported by @AndreaFiorito is not rooted in  `-n`. The root cause is that `prebuilt-library.mk` aborts on missing src file at parse time, before Gradle (or make, or cmake, or any other external build system) has a chance to provide that file.

**Comment by alexcohn** [comment] 2018-04-29 12:39
> but that ordering is not being respected by gradle?

The ordering is respected OK, but **Sync** stage for second project happens before the first project gets built. Let me emphasize that this is the perfectly correct behavior: first, sync only; after that, build all the projects.

The same situation happens without Gradle or Android Studio. E.g. one of our libraries depends on **libvpx.a**, which has its own build scripts for Android (*configure/make*), and does not use **Android.mk** to orchestrate its build. We wanted to build **libvpx** from sources, using the official build process, on one hand, and to have our build using the standard NDK **Android.mk** hierarchy. I have prepared a script that lets us use PREBUILT_STATIC_LIBRARY correctly in this case, but it is rather tricky. The workarounds I proposed above are derived from this script.

An ugly alternative that I see quite often is to force such 'external build' happen out of the natural lifecycle of make, by calling an equivalent of

    $(shell ./configure && make )

I see this as an abuse of **make**, and the consequences of such approach tend to be that **ndk-build** can only be used with **git clean -f**.

**Comment by AndreaFiorito** [comment] 2018-05-01 10:36
Hi, I was finally able to sync and build my project. As per Dan suggestion, i double checked that the order on the compilation phase was correct. it wasn't, and I add to explicitly set the dependency with this snippet:
`tasks.whenTaskAdded { task ->
        if (task.name.contains('externalNativeBuild') && !task.name.contains('externalNativeBuildClean')) {
        task.dependsOn(':mysdk:' + task.name)
        //logger.lifecycle('DEPENDENCY ADDED:' +  task.name + ' depends on ' + ':mysdk:' + task.name)
    }
}`
regarding the sync and clean phases, i added on the makefile:
`PREBUILT_HACK := $(or $(findstring n,$(MAKEFLAGS)), $(findstring $(MAKECMDGOALS),clean))
ifneq ($(PREBUILT_HACK),)
  include $(BUILD_SHARED_LIBRARY)
else
  include $(PREBUILT_SHARED_LIBRARY)
endif`

Let me first thank you for the support you both given to me in solving this issue.
My impression on the current situation is that both gradle for android (maybe responsibility of the plugin?) and ndk are not integrated as they should. On the gradle side, it's a pity you cannot express dependencies between libraries on the native side in a simple way. On the ndk side, it's a pity you cannot express dependency on an external library whose building process is managed externally from another build system. Neither prebuilt_libraries nor build_shared matched this case, being it something in the middle of the two. (In fact we have control of the build of the dependency but it's not embeddable in the main makefile). Choosing to force the prebuilt_libraries option to this case led to various problems related to the presence of the file, notably passing the -n flag, and on the clean phase (seriously, if i clean i need the library there?!). Ideally, the two build systems, should be able to communicate and execute the checks in a better way.

**Comment by alexcohn** [comment] 2018-05-01 13:44
@AndreaFiorito, how comes it was not enough to set in `app/build.gradle`

    dependencies {
        implementation project(':mysdk')
    }

**Comment by DanAlbert** [comment] 2018-12-03 17:22
@jomof: is there anything that can be done about this on the Studio side? The ndk-build-only fix is to just allow missing prebuilts when make is dry-run (and hope that never causes any bugs), but that *should* be an error, same as a missing source file would be.

This happens in multi-module gradle builds where one project imports "prebuilt" libraries from another module. Gradle syncs all the projects at once, so the "prebuilt" modules don't exist yet. This is really not how `PREBUILT_SHARED_LIBRARY` is supposed to be used, but I don't see that users have any beter option right now.

Would it be possible for gradle to not sync dependent projects until their dependencies are built? Alternatively, could gradle start passing `INVOKED_BY_GRADLE=true` or something similar when it invokes ndk-build? I really don't want to break this for non-gradle users.

**Comment by jomof** [comment] 2018-12-03 17:48
INVOKE_BY_GRADLE=true is easily done but doesn't separate concerns very well. We can't build before sync because sync is what makes Android Studio responsive to the user. I don't know how feasible but if ndk-build had a metadata mode "ndk-build --metadata <flags>" that emitted compilation database plus link/target information then gradle could use that instead of -nB info. Of course that's a bunch of work on both sides. Discuss Thursday?

**Comment by DanAlbert** [comment] 2018-12-03 18:19
That's something we should be working toward as well, but is actually orthogonal to this problem. Even if we're emitting metadata rather than using `-n`, ndk-build is still being invoked when there's a source file that hasn't been generated yet.

I could add a `IGNORE_MISSING_PREBUILTS` flag instead. What I really want to avoid doing is making dry run behave differently than a non-dry run, since that kind of defeats the purpose.

**Comment by alexcohn** [comment] 2018-12-03 18:44
Please note that gradle is only one, maybe very prominent, scenario. We had to come up with tricky workarounds for missing (at makefile parsing stage) PREBUILT_SHARED_LIBRARY in other situations, too. E.g. our project depends on ffmpeg libraries. There is no way to wrap their configuration in Android.mk (believe me, many make ninjas tried!), especially when you consider the frequency of ffmpeg version updates.

IGNORE_MISSING_PREBUILTS could be a step in the right direction. Or an alternative, EXTERNALLY_BUILT_SHARED_LIBRARY.

**Comment by DanAlbert** [comment] 2018-12-03 18:58
> Or an alternative, EXTERNALLY_BUILT_SHARED_LIBRARY.

I'd considered this too, but the problem remains: the external library isn't built yet, so ndk-build shouldn't be invoked.

I get why that's happening with gradle, even if there it's a symptom of a missing feature. Why does it happen outside gradle?

Maybe using `PREBUILT_SHARED_LIRBARY` to refer to something built by a custom rule?

**Comment by DanAlbert** [comment] 2018-12-03 19:35
Okay, looks like this isn't going to work regardless. If I go ahead and make the change described here (i.e. ignore the fact that the library is missing and continue with the dry run), make complains that the library is missing:

```makefile
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := foo
LOCAL_SRC_FILES := lib.so # Doesn't exist.
include $(PREBUILT_SHARED_LIBRARY)
```

```bash
$ android-ndk-r20-canary/ndk-build -C foo -B -n                
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.    
Android NDK: WARNING:jni/Android.mk:foo: LOCAL_SRC_FILES points to missing file jni/lib.so. Continuing dry run.    
Android NDK: WARNING:jni/Android.mk:foo: LOCAL_SRC_FILES points to missing file jni/lib.so. Continuing dry run.    
Android NDK: WARNING:jni/Android.mk:foo: LOCAL_SRC_FILES points to missing file jni/lib.so. Continuing dry run.    
Android NDK: WARNING:jni/Android.mk:foo: LOCAL_SRC_FILES points to missing file jni/lib.so. Continuing dry run.    
make: Entering directory `/work/src/ndk/ndk/foo'
rm -f ./libs/arm64-v8a/* ./libs/armeabi-v7a/* ./libs/x86/* ./libs/x86_64/*
rm -f ./libs/arm64-v8a/gdbserver ./libs/armeabi-v7a/gdbserver ./libs/x86/gdbserver ./libs/x86_64/gdbserver
rm -f ./libs/arm64-v8a/gdb.setup ./libs/armeabi-v7a/gdb.setup ./libs/x86/gdb.setup ./libs/x86_64/gdb.setup
make: *** No rule to make target `jni/lib.so', needed by `obj/local/arm64-v8a/lib.so'.  Stop.
make: Leaving directory `/work/src/ndk/ndk/foo'
```

The fix that Alex mentions in https://stackoverflow.com/a/50005410/192373 (replace `PREBUILT_SHARED_LIBRARY` with `BUILD_SHARED_LIRBARY` when using `-n`) allows the dry run to complete, but also completely changes the output.

<details>
<summary>Build log</summary>
<p>

```bash
android-ndk-r20-canary/ndk-build -C foo -B -n
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.    
Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module foo    
Android NDK:   lib.so    
Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module foo    
Android NDK:   lib.so    
Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module foo    
Android NDK:   lib.so    
Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module foo    
Android NDK:   lib.so    
make: Entering directory `/work/src/ndk/ndk/foo'
rm -f ./libs/arm64-v8a/* ./libs/armeabi-v7a/* ./libs/x86/* ./libs/x86_64/*
rm -f ./libs/arm64-v8a/gdbserver ./libs/armeabi-v7a/gdbserver ./libs/x86/gdbserver ./libs/x86_64/gdbserver
rm -f ./libs/arm64-v8a/gdb.setup ./libs/armeabi-v7a/gdb.setup ./libs/x86/gdb.setup ./libs/x86_64/gdb.setup
mkdir -p obj/local/arm64-v8a
echo [arm64-v8a] "SharedLibrary  ": "libfoo.so"
/work/src/ndk/out/linux/android-ndk-r20-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -Wl,-soname,libfoo.so -shared -lgcc -Wl,--exclude-libs,libgcc.a -latomic -Wl,--exclude-libs,libatomic.a -target aarch64-none-linux-android21 -no-canonical-prefixes    -Wl,--build-id -nostdlib++ -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings   -lc -lm -o ./obj/local/arm64-v8a/libfoo.so
mkdir -p libs/arm64-v8a
echo [arm64-v8a] "Install        ": "libfoo.so => libs/arm64-v8a/libfoo.so"
install -p ./obj/local/arm64-v8a/libfoo.so ./libs/arm64-v8a/libfoo.so
/work/src/ndk/out/linux/android-ndk-r20-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip --strip-unneeded  ./libs/arm64-v8a/libfoo.so
mkdir -p obj/local/armeabi-v7a
echo [armeabi-v7a] "SharedLibrary  ": "libfoo.so"
/work/src/ndk/out/linux/android-ndk-r20-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -Wl,-soname,libfoo.so -shared -lgcc -Wl,--exclude-libs,libgcc.a -latomic -Wl,--exclude-libs,libatomic.a -target armv7-none-linux-androideabi16 -no-canonical-prefixes    -Wl,--build-id -nostdlib++ -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings    -lc -lm -o ./obj/local/armeabi-v7a/libfoo.so
mkdir -p libs/armeabi-v7a
echo [armeabi-v7a] "Install        ": "libfoo.so => libs/armeabi-v7a/libfoo.so"
install -p ./obj/local/armeabi-v7a/libfoo.so ./libs/armeabi-v7a/libfoo.so
/work/src/ndk/out/linux/android-ndk-r20-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip --strip-unneeded  ./libs/armeabi-v7a/libfoo.so
mkdir -p obj/local/x86
echo [x86] "SharedLibrary  ": "libfoo.so"
/work/src/ndk/out/linux/android-ndk-r20-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -Wl,-soname,libfoo.so -shared -lgcc -Wl,--exclude-libs,libgcc.a -latomic -Wl,--exclude-libs,libatomic.a -target i686-none-linux-android16 -no-canonical-prefixes    -Wl,--build-id -nostdlib++ -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings   -lc -lm -o ./obj/local/x86/libfoo.so
mkdir -p libs/x86
echo [x86] "Install        ": "libfoo.so => libs/x86/libfoo.so"
install -p ./obj/local/x86/libfoo.so ./libs/x86/libfoo.so
/work/src/ndk/out/linux/android-ndk-r20-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-strip --strip-unneeded  ./libs/x86/libfoo.so
mkdir -p obj/local/x86_64
echo [x86_64] "SharedLibrary  ": "libfoo.so"
/work/src/ndk/out/linux/android-ndk-r20-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -Wl,-soname,libfoo.so -shared -lgcc -Wl,--exclude-libs,libgcc.a -latomic -Wl,--exclude-libs,libatomic.a -target x86_64-none-linux-android21 -no-canonical-prefixes    -Wl,--build-id -nostdlib++ -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings   -lc -lm -o ./obj/local/x86_64/libfoo.so
mkdir -p libs/x86_64
echo [x86_64] "Install        ": "libfoo.so => libs/x86_64/libfoo.so"
install -p ./obj/local/x86_64/libfoo.so ./libs/x86_64/libfoo.so
/work/src/ndk/out/linux/android-ndk-r20-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-strip --strip-unneeded  ./libs/x86_64/libfoo.so
make: Leaving directory `/work/src/ndk/ndk/foo'
```

</p>
</details>

ndk-build is perfectly happy to build an empty shared library, but the output of this approach is very different from what the non-dry run will do. Like I said, dry run needs to be honest or it's not good for much.

**Comment by alexcohn** [comment] 2018-12-03 22:37
I guess you substituted **$(prebuilt)** with **$(prebuilt_path)** in your **prebuilt-library.mk**. Here is what I get for your **Android.mk**, having instead commented out the single string in **prebuilt-library.mk:45**, namely

```
ifndef prebuilt
$(call __ndk_info,ERROR:$(LOCAL_MAKEFILE):$(LOCAL_MODULE): LOCAL_SRC_FILES points to a missing file)
$(call __ndk_info,Check that $(prebuilt_path) exists, or that its path is correct)
#$(call __ndk_error,Aborting)
endif
```
I have *empty* **$(prebuilt)** and get no errors for dry run:

```
$ ../android-ndk-r18/ndk-build -n -B APP_ABI=arm64-v8a
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.
Android NDK: ERROR:jni/Android.mk:foo: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that jni/lib.so  exists  or that its path is correct

rm -f ./libs/arm64-v8a/* ./libs/armeabi-v7a/* ./libs/x86/* ./libs/x86_64/*
rm -f ./libs/arm64-v8a/gdbserver ./libs/armeabi-v7a/gdbserver ./libs/x86/gdbserver ./libs/x86_64/gdbserver
rm -f ./libs/arm64-v8a/gdb.setup ./libs/armeabi-v7a/gdb.setup ./libs/x86/gdb.setup ./libs/x86_64/gdb.setup
mkdir -p obj/local/arm64-v8a
echo [arm64-v8a] "Prebuilt       ": "lib.so <= "
cp -f  obj/local/arm64-v8a/lib.so
mkdir -p libs/arm64-v8a
echo [arm64-v8a] "Install        ": "lib.so => libs/arm64-v8a/lib.so"
install -p ./obj/local/arm64-v8a/lib.so ./libs/arm64-v8a/lib.so
.../bin/aarch64-linux-android-strip --strip-unneeded  ./libs/arm64-v8a/lib.so
```

You can notice that two lines look strange here: if lib.so is present, we get

```
echo [arm64-v8a] "Prebuilt       ": "lib.so <= jni/"
cp -f jni/lib.so obj/local/arm64-v8a/lib.so
```

But I checked how this output is parsed by the Gradle plugin during synchroniztion, and I found no differences there. Anyway, I don't know what information AS needs about prebuilt libraries. They are not indexed in any way.

**Comment by alexcohn** [comment] 2018-12-04 11:20
The above change only helps with `-n` scenario, but does not resolve all issues expected for EXTERNALLY_BUILT_SHARED_LIBRARY.

Let's go back to the **libvpx.a** example. I would really want to be able to write a simple **Android.mk** as this:

```
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := foo
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/lib.so # Doesn't exist yet.
include $(EXTERNALLY_BUILT_SHARED_LIBRARY)

$(LOCAL_OBJECTS): # Instead of typing $(LOCAL_PATH)/$(TARGET_ARCH_ABI)/lib.so
        @echo Building $@
        $(MAKE) -C $(dir $(@D)) $@
```
It happens that the change to **prebuilt-library.mk** is minimal:
```
43c43
< $(call __ndk_info,ERROR:$(LOCAL_MAKEFILE):$(LOCAL_MODULE): LOCAL_SRC_FILES points to a missing file)
---
> $(call __ndk_info,WARNING:$(LOCAL_MAKEFILE):$(LOCAL_MODULE): LOCAL_SRC_FILES points to a missing file)
45d44
< $(call __ndk_error,Aborting)
66c65
<   LOCAL_OBJECTS      := $(prebuilt)
---
>   LOCAL_OBJECTS      := $(prebuilt_path)
```

**Comment by DanAlbert** [comment] 2018-12-04 21:04
Pretty much any time someone has to write a custom make rule like that it's because we're missing a feature. In this case is some form of genrule: https://github.com/android-ndk/ndk/issues/865

**Comment by alexcohn** [comment] 2018-12-05 05:53
Yes, this would be great

**Comment by alexcohn** [comment] 2019-02-14 14:11
To add insult to injury, **make** has a very naughty feature n Windows. When used with the default (**cmd**) shell, it cannot perform **$(shell)** function in **dry-run** (i.e. **-n**) mode:
```
qq = $(shell echo qq)
$(info qq=$(qq))

all:
        @echo done
```
Now, here is the result:
```
c:\>make -f qq.mk -n SHELL=cmd
process_begin: CreateProcess(NULL, "", ...) failed.
`qq=`
`echo done`
c:\>make -f qq.mk -n SHELL=sh.exe
`qq=qq`
`echo done`
````
This further reduces the reliability of the way Android Studio uses the **dry-run** mode to analyze the **ndkBuild** clause.

**Comment by DanAlbert** [comment] 2019-09-17 00:00
btw, the issue in the most recent comment should be resolved in r21. There was a bug in make that caused that: http://gnu-make.2324884.n4.nabble.com/process-begin-CreateProcess-NULL-quot-quot-failed-td13819.html

**Comment by alexcohn** [comment] 2019-09-17 08:08
And what are the expectations on https://github.com/android/ndk/issues/865 ?

**Comment by DanAlbert** [comment] 2019-09-17 17:11
Still a thing I'd like to do, but unfortunately not at the top of the Todo list yet.

**Comment by DanAlbert** [comment] 2020-04-14 00:54
#865 covers the part of this that I think we should fix (where we is the NDK proper; I think gradle still needs to support intermodule native dependencies but that's out of scope for this bug tracker). Those seem to be the two cases in play here, so closing this.

**Closed by DanAlbert** 2020-04-14 00:54 UTC
Labels: ndk-build
