### ISSUE TITLE
[BUG] Bionic: `#include <features.h>` in .S files lead to unexpected C tokens

### ISSUE THREAD

**Issue by MaskRay** [android/ndk#1422] opened 2021-01-07 00:51 UTC
#### Description

I believe glibc provides `features.h` and a few other platforms provide the file for compatibility. In glibc, `features.h` can be included in assembly files (in a few glibc .S files, `features.h` is included so it seems that this should work in .S files):

```
% cat a.S
#include <features.h>
% clang -c a.S
```

However, the same does not work with Bionic `features.h`.

Originally reported as https://crbug.com/1162741 , `#include <features.h>` in .S files lead to unrecognized C declaration errors

```
FAILED: lib/hwasan/CMakeFiles/RTHwasan.aarch64.dir/hwasan_setjmp.S.o 
 /b/s/w/ir/cache/builder/src/third_party/llvm-build/Release+Asserts/bin/clang -DHWASAN_WITH_INTERCEPTORS=1 -I/b/s/w/ir/cache/builder/src/third_party/llvm/compiler-rt/lib/hwasan/.. --target=aarch64-linux-android21 --sysroot=/b/s/w/ir/cache/builder/src/third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot --gcc-toolchain=/b/s/w/ir/cache/builder/src/third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64 -O3 -DNDEBUG    -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -nostdinc++ -fno-rtti -fPIC -ffreestanding -MD -MT lib/hwasan/CMakeFiles/RTHwasan.aarch64.dir/hwasan_setjmp.S.o -MF lib/hwasan/CMakeFiles/RTHwasan.aarch64.dir/hwasan_setjmp.S.o.d -o lib/hwasan/CMakeFiles/RTHwasan.aarch64.dir/hwasan_setjmp.S.o -c /b/s/w/ir/cache/builder/src/third_party/llvm/compiler-rt/lib/hwasan/hwasan_setjmp.S
 /b/s/w/ir/cache/builder/src/third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/get_device_api_level_inlines.h:38:26: error: unexpected token in argument list
 int __system_property_get(const char* __name, char* __value);
                          ^
 /b/s/w/ir/cache/builder/src/third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/get_device_api_level_inlines.h:39:9: error: unexpected token in argument list
 int atoi(const char* __s) __attribute__((__pure__));
         ^
```

For my compiler-rt sanitizer patch (https://reviews.llvm.org/D93848), I worked around the issue with

```c
#if __has_include(<features.h>) && !defined(__ANDROID__)
#include <features.h>
#endif
```

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 
* Build system: CMake
* Host OS: Debian testing
* ABI:
* NDK API level:
* Device API level:

**Comment by DanAlbert** [comment] 2021-01-07 22:50
Caused by https://android-review.googlesource.com/c/platform/bionic/+/822621/4/libc/include/android/api-level.h. @enh-google, I'm guessing you didn't intend to expose those in `<sys/cdefs.h>`?

**Comment by enh-google** [comment] 2021-01-07 22:58
> I'm guessing you didn't intend to expose those

i did --- that was the whole point of that change :-)

but, no, i hadn't thought of assembler. adding the `#if !defined(__ASSEMBLER__)` seems reasonable enough though (given that we don't actually distinguish between <features.h> and <sys/cdefs.h>, and that it's hard to retcon transitive includes without breaking the world for little to no value).

**Comment by DanAlbert** [comment] 2021-01-07 23:46
Specifically in cdefs though?

**Comment by enh-google** [comment] 2021-01-08 00:20
sort of:

* does <sys/cdefs.h> deliberately include <android/api-level.h>? yes.
* does <android/api-level.h> deliberately contain the corresponding function declarations? yes.

the questionable part was:

* does <features.h> deliberately include <sys/cdefs.h>?

where, yeah, it was deliberate, but it's probably not how we'd have done things if we'd had a blank slate. we added <features.h> really late, and didn't try to pull out the stuff that "should be in <features.h>" because we didn't want to break existing code, and it's not like there's any standard for <features.h> anyway. making <features.h> == <sys/cdefs.h> was the easiest/cleanest/least disruptive choice, and removed the temptation to try to move things between there and <sys/cdefs.h> over time (which is the most annoying thing we could do to developers, to no real benefit except our sense of "cleanliness").

even so, i think the answer to "should <features.h> give you the API level constants and functions?" is "of course!". so many of the <features.h> questions are run-time rather than compile-time for Android developers that developers -- app developers at least, who are the vast majority -- almost never want the compile-time stuff and almost always want the run-time stuff.

(if you're wondering what the motivating example was, iirc it was someone who couldn't use `__has_include()` because they needed GCC compatibility so they ended up with a bunch of awful #ifdefery and we said "this is silly --- the Android API level stuff is enough of a fact of life for Android development that it should just be there, not something you have to hunt for".

**Comment by DanAlbert** [comment] 2021-01-08 00:27
I think all the constants are hard to argue with, but we could move the "what OS am I on?" functions to another file. Doesn't seem to be much reason to do that over just using `#if !defined(__ASSEMBLER__)` though, so sgtm.

**Comment by enh-google** [comment] 2021-01-08 01:25
i'm _pretty_ sure you were on the "let's put them in <android/api-level.h>" side of the argument when we originally had to decide, on the basis that they're most findable if they're next to the constants you use them with :-) (but then i was too, so it's possible i'm remembering more agreement than was actually the case!)

anyway, https://android-review.googlesource.com/c/platform/bionic/+/1543864 adds the `__ASSEMBLER__` check. (testing this by adding an unnecessary #include into a .S file has made me realize too that the kernel headers' use of `__ASSEMBLY__` isn't right. but i'll fix that in a separate CL.)

**Comment by enh-google** [comment] 2021-01-08 01:29
actually, no `__ASSEMBLY__` does work. i'd confused my various edits. i might actually check in the "useless" #include as a handy regression test...

**Comment by enh-google** [comment] 2021-01-08 20:29
(fix merged in AOSP master.)

**Closed** 2022-10-18 00:07 UTC
Labels: bug
