### ISSUE TITLE
[BUG] error: no type named 'identity' in namespace 'std'

### ISSUE THREAD

**Issue by MBilderbeek** [android/ndk#1845] opened 2023-02-22 12:55 UTC
### Description

This piece of code (which is a minimal part of the openMSX/openMSX project on GitHub, see also [here](https://github.com/openMSX/openMSX/issues/1431)) doesn't compile with the Android NDK C++ compiler, and does compile with clang++.

```
#include <iostream>
#include <functional>
#include <iterator> // for std::begin(), std::end()

template<typename ForwardRange, typename Compare = std::less<>, typename Proj = std::identity>
[[nodiscard]] bool is_sorted(ForwardRange&& range, Compare comp = {}, Proj proj = {})
{
        return std::is_sorted(std::begin(range), std::end(range),
                [&](const auto& x, const auto& y) {
                        return comp(std::invoke(proj, x), std::invoke(proj, y));
                });
}

int main() {
    std::cout << "Hello World!";
    return 0;
}
```
This builds fine with clang++:
```
$ clang++ -std=c++20 test.cc 
$ clang++ --version
Debian clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
but not with the NDK clang++:
```
$ armv7a-linux-androideabi19-clang++ -std=c++20 /tmp/test.cc
/tmp/test.cc:5:86: error: no type named 'identity' in namespace 'std'
template<typename ForwardRange, typename Compare = std::less<>, typename Proj = std::identity>
                                                                                ~~~~~^
1 error generated.
$ armv7a-linux-androideabi19-clang++ --version
Android (8075178, based on r437112b) clang version 14.0.1 (https://android.googlesource.com/toolchain/llvm-project 8671348b81b95fc603505dfc881b45103bee1731)
Target: armv7a-unknown-linux-android19
Thread model: posix
InstalledDir: /usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
```
This prevents us from compiling our project on Android, since we are using this C++-20 feature.

### Affected versions

r24

### Host OS

Linux

### Host OS version

Debian testing

### Affected ABIs

armeabi-v7a

### Build system

Other (specify below)

### Other build system

none

### minSdkVersion

n.a.

### Device API level

19

**Comment by jfgoog** [comment] 2023-02-22 19:57
This is probably because the version of libc++ in the NDK is somewhat out of date. We are working on fixing this.

**Comment by jfgoog** [comment] 2023-02-22 19:58
Duplicate of #1530

**Closed** 2023-02-22 19:58 UTC
Labels: bug
