### ISSUE TITLE
[BUG] NDK r23 Segmentation fault

### ISSUE THREAD

**Issue by calvin2021y** [android/ndk#1572] opened 2021-08-26 12:27 UTC
#### Description

build with lto cause clang Segmentation fault
```sh
1.	Running pass 'Function Pass Manager' on module 'ld-temp.o'.
2.	Running pass 'ARM Instruction Selection' on function '@_test'
 #0 0x00000000025bd168 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x25bd168)
 #1 0x00000000025bcff0 llvm::sys::RunSignalHandlers() android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x25bcff0)
 #2 0x00000000025bd63a (ndroid-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x25bd63a)
 #3 0x00007fcc58c10140 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14140)
 #4 0x000000000182dda3 llvm::DataLayout::getAlignment(llvm::Type*, bool) const (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x182dda3)
 #5 0x0000000002919867 (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x2919867)
 #6 0x0000000001c6fae5 llvm::TargetLowering::LowerCallTo(llvm::TargetLowering::CallLoweringInfo&) const (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1c6fae5)
 #7 0x0000000001c43921 llvm::SelectionDAGBuilder::lowerInvokable(llvm::TargetLowering::CallLoweringInfo&, llvm::BasicBlock const*) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1c43921)
 #8 0x0000000001c425f8 llvm::SelectionDAGBuilder::LowerCallTo(llvm::CallBase const&, llvm::SDValue, bool, llvm::BasicBlock const*) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1c425f8)
 #9 0x0000000001c3cd00 llvm::SelectionDAGBuilder::visitCall(llvm::CallInst const&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1c3cd00)
#10 0x0000000001c3c5fc llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1c3c5fc)
#11 0x0000000001c3c191 llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, bool&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1c3c191)
#12 0x0000000001c3b047 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1c3b047)
#13 0x0000000001c383a4 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1c383a4)
#14 0x0000000001c37ec1 (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1c37ec1)
#15 0x0000000001ff24da llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1ff24da)
#16 0x0000000001a09037 llvm::FPPassManager::runOnFunction(llvm::Function&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1a09037)
#17 0x0000000001a08d2f llvm::FPPassManager::runOnModule(llvm::Module&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x1a08d2f)
#18 0x0000000002280f04 llvm::legacy::PassManagerImpl::run(llvm::Module&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x2280f04)
#19 0x0000000002b89252 (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x2b89252)
#20 0x0000000002b78ffd llvm::lto::backend(llvm::lto::Config const&, std::__1::function<std::__1::unique_ptr<llvm::lto::NativeObjectStream, std::__1::default_delete<llvm::lto::NativeObjectStream> > (unsigned int)>, unsigned int, std::__1::unique_ptr<llvm::Module, std::__1::default_delete<llvm::Module> >, llvm::ModuleSummaryIndex&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x2b78ffd)
#21 0x0000000002b780d8 llvm::lto::LTO::runRegularLTO(std::__1::function<std::__1::unique_ptr<llvm::lto::NativeObjectStream, std::__1::default_delete<llvm::lto::NativeObjectStream> > (unsigned int)>) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x2b780d8)
#22 0x000000000260879e llvm::lto::LTO::run(std::__1::function<std::__1::unique_ptr<llvm::lto::NativeObjectStream, std::__1::default_delete<llvm::lto::NativeObjectStream> > (unsigned int)>, std::__1::function<std::__1::function<std::__1::unique_ptr<llvm::lto::NativeObjectStream, std::__1::default_delete<llvm::lto::NativeObjectStream> > (unsigned int)> (unsigned int, llvm::StringRef)>) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x260879e)
#23 0x000000000265bfc0 lld::elf::BitcodeCompiler::compile() (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x265bfc0)
#24 0x000000000264ed7c void lld::elf::LinkerDriver::compileBitcodeFiles<llvm::object::ELFType<(llvm::support::endianness)1, false> >() (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x264ed7c)
#25 0x00000000026466e1 void lld::elf::LinkerDriver::link<llvm::object::ELFType<(llvm::support::endianness)1, false> >(llvm::opt::InputArgList&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x26466e1)
#26 0x0000000002641287 lld::elf::LinkerDriver::linkerMain(llvm::ArrayRef<char const*>) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x2641287)
#27 0x000000000258c6e9 lld::elf::link(llvm::ArrayRef<char const*>, bool, llvm::raw_ostream&, llvm::raw_ostream&) (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x258c6e9)
#28 0x00000000018fcf91 (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x18fcf91)
#29 0x00000000018fc9c9 main (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x18fc9c9)
#30 0x00007fcc5862fd0a __libc_start_main ./csu/../csu/libc-start.c:308:16
#31 0x000000000340b351 _start (android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld+0x340b351)
clang-12: error: unable to execute command: Segmentation fault
clang-12: error: linker command failed due to signal (use -v to see invocation)

``` 

#### Environment Details

* NDK Version:  android-ndk-r23
* Build system:  test arm32, aarch64, x86, x86-64 get same error
* Host OS:  test on linux and osx get same error
* ABI: all abi test has same error
* NDK API level: test 31 and 21 and 23 all get this error

**Comment by calvin2021y** [comment] 2021-08-30 13:36
Only without LTO -O2 or -O3,  -O1 or without LTO work.

I can not send my project report to public because I signup Confidentiality agreement, Maybe there is any way to find the problem ?

**Comment by pirama-arumuga-nainar** [comment] 2021-08-30 18:33
> This problem raised if I use LTO with -O2 or -O3. -O1 or without LTO work.

It's easy to investigate or bisect with LTO off.  So please check if this reproduces without LTO.

> I can not send my project report to public

Can you share a reduced form of the crash?  Check function `_test` for anything suspicious.  Maybe a suspicious intrinsic or builtin call?  Like I mentioned, reproducing with LTO off would help reduce the test case either manually or with a tool like CReduce ([1](https://embed.cs.utah.edu/creduce/), [2](http://nickdesaulniers.github.io/blog/2019/01/18/finding-compiler-bugs-with-c-reduce/)).

**Comment by stephenhines** [comment] 2021-08-30 18:51
https://embed.cs.utah.edu/creduce/using/ and https://nickdesaulniers.github.io/blog/2019/01/18/finding-compiler-bugs-with-c-reduce/ are good introductions to using creduce. Since this is a seg fault, you will need to write your test script such that it checks the compiler crashes (rather than just generating an error message for malformed code).

**Comment by calvin2021y** [comment] 2021-08-31 05:04
Thanks for the tips, I will try reduce the code.

Without LTO work fine.

**Comment by DanAlbert** [comment] 2021-08-31 21:05
Closing for lack of info, but that's just to help us with tracking. We'll reopen as soon as there's something we can do, and this is still a candidate for an r23 update (the window is closing on r23b, but it's very unlikely that'll be our last release of r23).

**Closed by DanAlbert** 2021-08-31 21:05 UTC
Labels: bug, needs-info

**Comment by calvin2021y** [comment] 2021-09-01 09:58
100% r last release of r23.

```sh
cat source.properties 
Pkg.Desc = Android NDK
Pkg.Revision = 23.0.7599858
```

**Comment by DanAlbert** [comment] 2021-09-01 17:55
Our tests lass. We need a repro case.
