### ISSUE TITLE
[BUG] std::from_chars (charconv) uses undefined log2f when targeting api level 16

### ISSUE THREAD

**Issue by 0x416c69** [android/ndk#1580] opened 2021-09-07 15:46 UTC
NDK version: r23

charconv:560: auto __digits = __tl::digits / log2f(float(__base));

log2f is only defined on api level >= 18

**Comment by DanAlbert** [comment] 2021-09-07 20:50
Please always follow the bug template. We only ask for that information because we need it.

What's this a symptom of? It's expected that some corners of libc++ can't be used on old devices (though they are very rare). With the information given I can't tell if this is a bug or expected.

Closing until we get info.

**Closed by DanAlbert** 2021-09-07 20:50 UTC
Labels: bug

**Comment by enh-google** [comment] 2021-09-07 21:16
(libandroid_support has log2f(), so the NDK build systems ought to mean this just works? if you have your own build system and you need to support pre-18, you'll have to drag that in. but note that we're dropping support for releases that old in NDK r24, as described in the r23 release notes.)

**Comment by DanAlbert** [comment] 2021-09-07 21:32
libandroid_support use is automatic in the toolchain though. You have to do a lot of work to not use it.

**Comment by 0x416c69** [comment] 2021-09-08 05:22
> Please always follow the bug template. We only ask for that information because we need it.

Of course, I thought this is rather obvious since I also included the line number & line contents of charconv. But I've included the info anyway.

> libandroid_support has log2f(), so the NDK build systems ought to mean this just works?

I wasn't aware of this. Thank you. Currently we're using the log2f implementation from the android source code. I am aware that you're going to drop the support for Jelly Bean but I thought since r23 is a LTS release and since api 16 is meant to be supported on this version you should have used functions that were defined in api 16 while implementing libc++.

**Comment by DanAlbert** [comment] 2021-09-08 09:13
Works for me:

```
$ cat foo.cpp
#include <stdint.h>
#include <charconv>
#include <string_view>

int main() {
  uint32_t test;
  std::string_view view = "FFFFFF";
  std::from_chars(view.data(), view.data() + view.length(), test, 16);
}
$ ~/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -target armv7-linux-androideabi16 foo.c
pp
$ readelf -sW a.out | grep log2f
    69: 00000000     0 FILE    LOCAL  DEFAULT  ABS e_log2f.c
    73: 000020fd   332 FUNC    LOCAL  HIDDEN    14 log2f
```

Without a more complete repro case (compile/link flags) I can't tell, but I'd guess that VS is just calling the compiler wrong. It's a very common cause of unreproducible linker issues.
