### ISSUE TITLE
[Bug]: Can't Use LLDB Which Comes From NDK On MacOs

### ISSUE THREAD

**Issue by SsageParuders** [android/ndk#1749] opened 2022-08-15 18:59 UTC
---

### On MacOs

Just as discussion #1748 
When I want to enter the LLDB command line.
Whether I use lldb.sh or lldb bin after source lldb.sh.
It comes a information like: **terminals database is inaccessible**

<img width="579" alt="image" src="https://user-images.githubusercontent.com/75780727/184697920-cdd81aa5-d319-4aed-8f5e-57ae9cefb22b.png">

---

### On Linux(Ubuntu 18.04)

And I had tested. `lldb.sh` which comes from NDK looks fine for Linux (Ubuntu 18.04)

<img width="852" alt="image" src="https://user-images.githubusercontent.com/75780727/184697414-94e192e4-0b57-42d9-9717-355784b1aaaf.png">

But there still seems to be a problem for Linux as:

> Cannot read termcap database;
> using dumb terminal settings.

No tests yet to see if it has any effects.

---

### Affected versions

r25 and below

### Host OS

Mac

### Host OS version

macOs 12.4

**Comment by pirama-arumuga-nainar** [comment] 2022-08-15 21:04
Explicitly setting `export TERMINFO=/usr/share/terminfo` changes the error message to:
```
$ ../llvm-toolchain/prebuilts/clang/host/darwin-x86/clang-r450784e/bin/lldb.sh ./a.out 
(lldb) target create "./a.out"
Current executable set to '/Volumes/android/tmp/a.out' (arm64).
'xterm-256color': unknown terminal type.
```

This was on an M1 Mac.  The error seems to be emitted by `libncurses`, FWIW.

**Comment by rprichard** [comment] 2022-08-15 21:33
I think this is a duplicate of https://github.com/android/ndk/issues/1565.

**Comment by DanAlbert** [comment] 2022-08-15 22:25
Is this two bugs? Why is `lldb.sh` needed at all? Is that how LLVM normally ships, or is that our wrapper?

**Comment by rprichard** [comment] 2022-08-15 22:46
I think this issue is a duplicate of the previous terminal database issue.

lldb.sh is our wrapper (created by llvm_android/builders.py). It sets PYTHONHOME, and if that's unset, then lldb may search the local system for Python modules:
```
$ /x/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/lldb
Cannot read termcap database;
using dumb terminal settings.
(lldb) script
Python Interactive Interpreter. To exit, type 'quit()', 'exit()' or Ctrl-D.
Cannot read termcap database;
using dumb terminal settings.
>>> import subprocess
>>> subprocess
<module 'subprocess' from '/usr/lib/python3.9/subprocess.py'>
```

It also sets either LD_LIBRARY_PATH or DYLD_LIBRARY_PATH.

Both the platform's lldbclient.py and ndk-gdb use lldb.sh if it exists:
```
def get_lldb_path(toolchain_path):
    for lldb_name in ["lldb.sh", "lldb.cmd", "lldb", "lldb.exe"]:
        debugger_path = os.path.join(toolchain_path, "bin", lldb_name)
        if os.path.isfile(debugger_path):
            return debugger_path
    return None
```

I think the ncurses that we distribute isn't finding the Linux/macOS system's terminal database. Maybe some paths need to be adjusted.

**Comment by SsageParuders** [comment] 2022-08-16 03:59
> Is this two bugs? Why is `lldb.sh` needed at all? Is that how LLVM normally ships, or is that our wrapper?

Dear bro, as @rprichard said, I also think `lldb.sh` is our wrapper.

LLVM normally ships don't have a shell named `lldb.sh`.

And our `lldb.sh` will set the environment before we run lldb.

----

BTW, I had tested `lldb.bat` On Windows. And it works fine.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/75780727/184795081-ee758842-e1ff-4db6-b719-e49b6f912daf.png">

**Comment by SsageParuders** [comment] 2022-08-16 04:01
> I think this issue is a duplicate of the previous terminal database issue.
> 
> lldb.sh is our wrapper (created by llvm_android/builders.py). It sets PYTHONHOME, and if that's unset, then lldb may search the local system for Python modules:
> 
> ```
> $ /x/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64/bin/lldb
> Cannot read termcap database;
> using dumb terminal settings.
> (lldb) script
> Python Interactive Interpreter. To exit, type 'quit()', 'exit()' or Ctrl-D.
> Cannot read termcap database;
> using dumb terminal settings.
> >>> import subprocess
> >>> subprocess
> <module 'subprocess' from '/usr/lib/python3.9/subprocess.py'>
> ```
> 
> It also sets either LD_LIBRARY_PATH or DYLD_LIBRARY_PATH.
> 
> Both the platform's lldbclient.py and ndk-gdb use lldb.sh if it exists:
> 
> ```
> def get_lldb_path(toolchain_path):
>     for lldb_name in ["lldb.sh", "lldb.cmd", "lldb", "lldb.exe"]:
>         debugger_path = os.path.join(toolchain_path, "bin", lldb_name)
>         if os.path.isfile(debugger_path):
>             return debugger_path
>     return None
> ```
> 
> I think the ncurses that we distribute isn't finding the Linux/macOS system's terminal database. Maybe some paths need to be adjusted.

Bro,did you solve the problem on macOs?
Could you give me a help?
Thanks a lot~

**Comment by DanAlbert** [comment] 2022-08-16 18:13
We're working on it. We'll post here when it's fixed.

**Comment by SsageParuders** [comment] 2022-08-17 00:57
> 

Thinks, bro.

**Comment by DanAlbert** [comment] 2023-02-27 20:23
Duplicate of #1565

(sorry for not duping sooner, it sounded uncertain to me at first but on re-read I don't think that was the case)

**Closed by DanAlbert** 2023-02-27 20:23 UTC
Labels: bug
