### ISSUE TITLE
[BUG] LLDB crash  with a simple help commond

### ISSUE THREAD

**Issue by zte-majiang** [android/ndk#1590] opened 2021-09-26 03:11 UTC
#### Description
/mnt/d/opensource/android_ndk/android-ndk-r23$ ./toolchains/llvm/prebuilt/linux-x86_64/bin/lldb.sh
Cannot read termcap database;
using dumb terminal settings.
(lldb) help x
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: /mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/lldb
 #0 0x0000000000231665 (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/lldb+0x231665)
 #1 0x0000000000231bb0 (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/lldb+0x231bb0)
 #2 0x0000000000231b1a (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/lldb+0x231b1a)
 #3 0x00007f5ea9c003c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #4 0x00007f5ea9012395 lldb_private::Options::GenerateOptionUsage(lldb_private::Stream&, lldb_private::CommandObject*, unsigned int) (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/liblldb.so.12git+0x442e395)
 #5 0x00007f5ea8ffd6e1 lldb_private::CommandObject::GenerateHelpText(lldb_private::Stream&) (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/liblldb.so.12git+0x44196e1)
 #6 0x00007f5ea94cd5cb lldb_private::CommandObjectHelp::DoExecute(lldb_private::Args&, lldb_private::CommandReturnObject&) (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/liblldb.so.12git+0x48e95cb)
 #7 0x00007f5ea8ffe38f lldb_private::CommandObjectParsed::Execute(char const*, lldb_private::CommandReturnObject&) (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/liblldb.so.12git+0x441a38f)
 #8 0x00007f5ea8ff18ac lldb_private::CommandInterpreter::HandleCommand(char const*, lldb_private::LazyBool, lldb_private::CommandReturnObject&, lldb_private::ExecutionContext*, bool, bool) (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/liblldb.so.12git+0x440d8ac)
 #9 0x00007f5ea8ff6240 lldb_private::CommandInterpreter::IOHandlerInputComplete(lldb_private::IOHandler&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/liblldb.so.12git+0x4412240)
#10 0x00007f5ea8f4f346 lldb_private::IOHandlerEditline::Run() (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/liblldb.so.12git+0x436b346)
#11 0x00007f5ea8f325ed lldb_private::Debugger::RunIOHandlers() (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/liblldb.so.12git+0x434e5ed)
#12 0x00007f5ea8ff78bc lldb_private::CommandInterpreter::RunCommandInterpreter(lldb_private::CommandInterpreterRunOptions&) (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/liblldb.so.12git+0x44138bc)
#13 0x00007f5ea8a9db8d lldb::SBDebugger::RunCommandInterpreter(bool, bool) (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib64/liblldb.so.12git+0x3eb9b8d)
#14 0x00000000002388b1 main (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/lldb+0x2388b1)
#15 0x00007f5ea47570b3 __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:342:3
#16 0x0000000000231d95 _start (/mnt/d/opensource/android_ndk/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/lldb+0x231d95)
./toolchains/llvm/prebuilt/linux-x86_64/bin/lldb.sh: line 5:  3618 Segmentation fault      (core dumped) "$CURDIR/lldb" "$@"

#### Environment Details
Windows10 WSL Ubuntu20.04 

:/mnt/d/opensource/android_ndk/android-ndk-r23$ uname -a
Linux P80299346 4.4.0-17763-Microsoft #1432-Microsoft Mon Aug 18 18:18:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
:/mnt/d/opensource/android_ndk/android-ndk-r23$ cat source.properties
Pkg.Desc = Android NDK
Pkg.Revision = 23.0.7599858

**Comment by DanAlbert** [comment] 2021-09-27 20:25
Repros on debian as well, so it's at least not a WSL issue. It looks like it is specifically a crash that happens when you run help with an unrecognized argument (`help` is fine, `help list` is fine, `help x` is not). Still present in the r24 canary.

**Comment by rprichard** [comment] 2021-09-27 21:22
> It looks like it is specifically a crash that happens when you run help with an unrecognized argument

`help asdfasdfasdf` prints `error: 'asdfasdfasdf' is not a known command.` The `x` command is supposed to be short for `memory read`, and `help memory read` also segfaults. They don't segfault in the upstream clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-20.04 binary.

It looks broken in r416183{b,c,c1} and fixed in r428724 and r433403.

**Comment by pirama-arumuga-nainar** [comment] 2021-09-27 21:37
FWIW, it was easy to find the fix by looking for `memory read` in `git log lldb`: https://reviews.llvm.org/D94917 (9a7672ac4980bca8829814e1e49e1c201a5bf9b6).

I don't think we should respin toolchain specifically for this issue though.

**Comment by DanAlbert** [comment] 2021-09-27 22:11
> I don't think we should respin toolchain specifically for this issue though.

Agreed. We should pick it up if (and realistically, _when_) we need to respin the toolchain for other issues. Triaged to r23c but will punt to r23d if we somehow manage to make it through a minor release without otherwise updating the toolchain.

**Comment by DanAlbert** [comment] 2021-09-29 07:36
Confirmed fixed with https://android-review.googlesource.com/c/platform/ndk/+/1839724.

**Comment by stephenhines** [comment] 2022-02-01 05:22
https://android-review.googlesource.com/c/toolchain/llvm_android/+/1965517 has the cherry-pick for r416183b (but needs prebuilts once merged).

**Closed** 2022-04-22 20:24 UTC
Labels: bug

**Comment by DanAlbert** [comment] 2022-04-22 20:25
Should be fixed in [build 8486889](https://ci.android.com/builds/branches/aosp-ndk-release-r23/grid?head=8486889&tail=8486889).
