### ISSUE TITLE
[BUG] target armv7 + armv8-a+crypto - ndk19

### ISSUE THREAD

**Issue by arturbac** [android/ndk#910] opened 2019-02-15 11:46 UTC
There is a problem with NDK 19 and propably gcc-tollchain set by cmake toolchain
NDK 18 uses --gcc-toolchain=/opt/android-ndk-r18/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
NDK19 uses --gcc-toolchain=/opt/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64

and this causes fails to compile code like below with -march=armv8-a+crypto -marm -mfpu=crypto-neon-fp-armv8  for armv7 target (conditionaly used during runtime if ext is present)
if gcc toolchain is changed to --gcc-toolchain=/opt/android-ndk-r19/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
code builds again

<code>
#if !defined(__ARM_NEON) || !defined(__ARM_FEATURE_CRYPTO)

  #error "neon/crypto must be anabled for building this code"

#endif

#include <arm_neon.h>
</code>

ndk 18 works
/opt/android-ndk-r18/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7-none-linux-androideabi16 --gcc-toolchain=/opt/android-ndk-r18/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r18/sysroot -std=gnu11 -isystem /opt/android-ndk-r18/sysroot/usr/include/arm-linux-androideabi -ggdb -DANDROID -ffunction-sections -funwind-tables -fno-stack-protector -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -marm -fPIC -ggdb -fvisibility=hidden -fvisibility-inlines-hidden -flto=thin -Oz -DNDEBUG  -fPIC -march=armv8-a+crypto -marm -mfpu=crypto-neon-fp-armv8 -dM -E - < /dev/null | grep ARM
[..]
#define __ARM_FEATURE_CRC32 1
#define __ARM_FEATURE_CRYPTO 1
[..]
#define __ARM_FEATURE_SIMD32 1
[..]
#define __ARM_NEON 1
#define __ARM_NEON_FP 0x6
#define __ARM_NEON__ 1
[..]

this generated from ndk cmake toolchain fails
/opt/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7-none-linux-androideabi16 --gcc-toolchain=/opt/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64 -std=gnu11  -std=gnu11 --sysroot /opt/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/sysroot -ggdb -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fno-stack-protector -no-canonical-prefixes -mfpu=vfpv3-d16 -fno-addrsig -marm  -Wformat -Werror=format-security  -fPIC -ggdb -fvisibility=hidden -fvisibility-inlines-hidden -flto=thin  -Oz -DNDEBUG  -fPIC   -march=armv8-a+crypto -marm -mfpu=crypto-neon-fp-armv8 -dM -E - < /dev/null | grep ARM
#define __ARMEL__ 1
#define __ARM_32BIT_STATE 1
#define __ARM_ACLE 200
#define __ARM_ARCH 8
#define __ARM_ARCH_8A__ 1
#define __ARM_ARCH_EXT_IDIV__ 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH_PROFILE 'A'
#define __ARM_EABI__ 1
#define __ARM_FEATURE_CLZ 1
#define __ARM_FEATURE_CRC32 1
#define __ARM_FEATURE_DIRECTED_ROUNDING 1
#define __ARM_FEATURE_DSP 1
#define __ARM_FEATURE_IDIV 1
#define __ARM_FEATURE_LDREX 0xf
#define __ARM_FEATURE_NUMERIC_MAXMIN 1
#define __ARM_FEATURE_QBIT 1
#define __ARM_FEATURE_SAT 1
#define __ARM_FEATURE_SIMD32 1
#define __ARM_FEATURE_UNALIGNED 1
#define __ARM_FP16_ARGS 1
#define __ARM_FP16_FORMAT_IEEE 1
#define __ARM_PCS 1
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_SIZEOF_WCHAR_T 4

this (fixed by hand) works
 /opt/android-ndk-r19/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7-none-linux-androideabi16 --gcc-toolchain=/opt/android-ndk-r19/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r19/sysroot -std=gnu11 -isystem /opt/android-ndk-r19/sysroot/usr/include/arm-linux-androideabi -ggdb -DANDROID -ffunction-sections -funwind-tables -fno-stack-protector -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -marm -fPIC -ggdb -fvisibility=hidden -fvisibility-inlines-hidden -flto=thin -Oz -DNDEBUG  -fPIC -march=armv8-a+crypto -marm -mfpu=crypto-neon-fp-armv8 -dM -E - < /dev/null | grep ARM
#define __ARMEL__ 1
#define __ARM_32BIT_STATE 1
#define __ARM_ACLE 200
#define __ARM_ARCH 8
#define __ARM_ARCH_8A__ 1
#define __ARM_ARCH_EXT_IDIV__ 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARM_ARCH_ISA_THUMB 2
#define __ARM_ARCH_PROFILE 'A'
#define __ARM_EABI__ 1
#define __ARM_FEATURE_CLZ 1
#define __ARM_FEATURE_CRC32 1
#define __ARM_FEATURE_CRYPTO 1
#define __ARM_FEATURE_DIRECTED_ROUNDING 1
#define __ARM_FEATURE_DSP 1
#define __ARM_FEATURE_IDIV 1
#define __ARM_FEATURE_LDREX 0xf
#define __ARM_FEATURE_NUMERIC_MAXMIN 1
#define __ARM_FEATURE_QBIT 1
#define __ARM_FEATURE_SAT 1
#define __ARM_FEATURE_SIMD32 1
#define __ARM_FEATURE_UNALIGNED 1
#define __ARM_FP 0xe
#define __ARM_FP16_ARGS 1
#define __ARM_FP16_FORMAT_IEEE 1
#define __ARM_FPV5__ 1
#define __ARM_NEON 1
#define __ARM_NEON_FP 0x6
#define __ARM_NEON__ 1
#define __ARM_PCS 1
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_SIZEOF_WCHAR_T 4

**Comment by DanAlbert** [comment] 2019-02-15 18:40
`-gcc-toolchain` doesn't seem to have anything to do with this. The part of your "fix" that fixes it is that your "fix" doesn't use `-march=armv8-a+crypto`. `-march` flags do not combine. The last one is the one that takes effect. You're targeting ARMv7. When targeting ARMv8 Clang doesn't set `__ARM_NEON`. I don't know if that's a bug or not (will investigate).

Regardless of that though, are you sure you want to target 32-bit ARMv8? Most of the devices that support that also support aarch64, and the devices that don't are likely ARMv7 anyway. You're excluding a lot of devices by targeting 32-bit ARMv8.

**Comment by DanAlbert** [comment] 2019-02-15 18:53
Adding `-mfloat-abi=hard` makes ARMv8 emit the NEON defines... that definitely seems like a bug.

**Comment by DanAlbert** [comment] 2019-02-15 19:33
Same for `-mfloat-abi=softfp`. An explicit `-mfloat-abi=soft` with ARMv7 will also disable NEON, so it seems the problem is that softfp is only being used by default for Android with ARMv7.

Aside from that, while Clang does set `__ARM_NEON__` for `-target armv7-linux-android16` (no other `-march`/`-mfpu`/`-mfloat-abi` flags), it doesn't pass the NEON target feature to the assembler. The assembler is actually the one with the correct behavior here, since r19's Clang isn't supposed to enable NEON until android-23 (though I'm changing that for r20 or r21 anyway).

**Comment by arturbac** [comment] 2019-02-15 19:44
So what are the proper additional flags to  use during compilation form single .c source crypto extensions with 32 bit android build.
I have some code that is called for crunching aes instead of software one when on 32bit cpu is detected armv8a cpu, which is ver common on androids to have 64bit kernel and 32bit java stack and entire android runing in 32bit mode.
i know that last switch goes into action but i just wanted to show case 
default generated flags from cmake toolchain + my additional ones
to get crypto extensions as instrinsics into compialtion
i just addes so far -march=armv8-a+crypto -mfpu=crypto-neon-fp-armv8 and i was able to compile 
with vaesmcq_u8,vaeseq_u8,veorq_u8 and vector types like uint8x16_t

till ndk i just added fro that single source file
set_source_files_properties(aes_armv8.c PROPERTIES COMPILE_FLAGS "-march=armv8-a+crypto -marm -mfpu=crypto-neon-fp-armv8")

**Comment by DanAlbert** [comment] 2019-02-15 20:37
> I have some code that is called for crunching aes instead of software one when on 32bit cpu is detected armv8a cpu, which is very common on androids to have 64bit kernel and 32bit java stack and entire android runing in 32bit mode on armv8a.

Okay, just wanted to make sure you were aware that this was a fairly distant edge case. This sounds like the right approach to me.

The flag you're missing is `-mfloat-abi=softfp`. It should be unnecessary to do so though, so I'll get that fixed (hopefully for r20, but r21 might be more likely).

**Comment by arturbac** [comment] 2019-02-15 20:42
Just found the same -mfloat-abi=softfp is sufficient

**Comment by arturbac** [comment] 2019-02-15 20:44
Btw this was very common scenario armv8a and 32bit android on androids-7 ex Samsung Galaxy S7.

**Comment by arturbac** [comment] 2019-02-15 20:46
And Thx for help

**Comment by DanAlbert** [comment] 2019-02-20 22:14
https://reviews.llvm.org/D58477 will fix this upstream.

- [ ] Land https://reviews.llvm.org/D58477
- [ ] Pull the fix into Android
- [ ] Update the NDK Clang

**Comment by petemoore** [comment] 2020-04-22 08:42
> https://reviews.llvm.org/D58477 will fix this upstream.
> 
>     * [x]  Land https://reviews.llvm.org/D58477
> 
>     * [ ]  Pull the fix into Android
> 
>     * [ ]  Update the NDK Clang

@DanAlbert Are these two items still open? Thanks.

**Comment by DanAlbert** [comment] 2020-04-22 09:32
I seriously doubt it given how long ago I submitted that, but I'll confirm tomorrow just in case. My guess is that the fix was in r20.

**Comment by DanAlbert** [comment] 2020-04-22 19:18
Was fixed in r21. Sorry for missing the close!

**Closed by DanAlbert** 2020-04-22 19:18 UTC
Labels: bug
