### ISSUE TITLE
Unable to link to openmp

### ISSUE THREAD

**Issue by knightfork** [android/ndk#1253] opened 2020-05-09 18:32 UTC
NDK - 21b
target arch - armv7a
toolchain - llvm
minAPI - 21
TargetAPI - 29
Tools version - 29.0.2
Android studio v - 3.6.2
host - OSX 10.15.1

I have tried to include it via cmakelist.txt file and also tried to add it as a shared object (not sure if that would work at all).

add_library(openmp STATIC IMPORTED)
set_target_properties(openmp PROPERTIES IMPORTED_LOCATION
        -L${NDK_ROOT}/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/9.0.8/lib/linux/arm/libomp.a)

  ninja: error: '-L/Users/***/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/9.0.8/lib/linux/arm/libomp.a', needed by 'XXXX/app/build/intermediates/cmake/debug/obj/armeabi-v7a/libXYZ-lib.so', missing and no known rule to make it

What I am wondering is, is it because there is no build for api-21? What am I doing wrong to have it included? Following blogpost says llvm has been updated for openmp support.

https://android-developers.googleblog.com/2019/10/introducing-ndk-r21-our-first-long-term.html

**Comment by enh-google** [comment] 2020-05-11 23:54
looks like a dupe of issue #1160

**Closed by enh-google** 2020-05-11 23:54 UTC
Labels: question
