### ISSUE TITLE
[FR] support std::jthread

### ISSUE THREAD

**Issue by atsushieno** [android/ndk#1669] opened 2022-02-10 07:51 UTC
### Description

std::jthread is a new face in C++20 (if I can say C++20 is new) that provides join-able threads.

- https://en.cppreference.com/w/cpp/thread/jthread
- https://github.com/josuttis/jthread
- https://github.com/martinmoene/jthread-lite

Recently I tried to use in in my code, but had to give up because it's missing in NDK. It would be nice to have it supported so that we do not have to worry about portability.

**Comment by DanAlbert** [comment] 2022-02-10 19:31
Duplicate of https://github.com/android/ndk/issues/1530

**Closed by DanAlbert** 2022-02-10 19:31 UTC
Labels: enhancement

**Comment by PabloMK7** [comment] 2024-07-16 09:06
Still an issue in ndk 27.0.11902837-rc2

**Comment by DanAlbert** [comment] 2024-07-16 19:04
Looks like it was added in https://github.com/llvm/llvm-project/commit/695138ca8405779c2b7756cc31d887aa54f56bb8. Grepping in the NDK's header shows that it does exist: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/ndk-r27-release/clang-r522817/include/c++/v1/__thread/jthread.h

https://libcxx.llvm.org/UsingLibcxx.html#enabling-experimental-c-library-features says it's an experimental feature and you need to use `-fexperimental-library`.
