### ISSUE TITLE
[BUG] error: use of undeclared identifier 'strtouq' / 'strtoq'

### ISSUE THREAD

**Issue by JMLX42** [android/ndk#1803] opened 2022-11-08 07:22 UTC
### Description

Trying to compile [PCRE](https://sourceforge.net/projects/pcre/files/pcre/) 8.45, I got the following error:

1. `error: use of undeclared identifier 'strtoq'`
2. `error: use of undeclared identifier 'strtouq'`

Here is the complete command line:

```
/opt/android-ndk-linux/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --sysroot=/opt/android-ndk-linux/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DHAVE_CONFIG_H -I/srv/embedb/build/third_party/pcre/src/pcre-build -I/srv/embedb/build/third_party/pcre/src/pcre -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -fPIC -MD -MT CMakeFiles/pcrecpp.dir/pcrecpp.cc.o -MF CMakeFiles/pcrecpp.dir/pcrecpp.cc.o.d -o CMakeFiles/pcrecpp.dir/pcrecpp.cc.o -c /srv/embedb/build/third_party/pcre/src/pcre/pcrecpp.cc
/srv/embedb/build/third_party/pcre/src/pcre/pcrecpp.cc:885:17: error: use of undeclared identifier 'strtoq'; did you mean 'strtol'?
  long long r = strtoq(str, &end, radix);
                ^~~~~~
                strtol
/opt/android-ndk-linux/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdlib.h:91:6: note: 'strtol' declared here
long strtol(const char* __s, char** __end_ptr, int __base);
     ^
/srv/embedb/build/third_party/pcre/src/pcre/pcrecpp.cc:917:26: error: use of undeclared identifier 'strtouq'; did you mean 'strtoul'?
  unsigned long long r = strtouq(str, &end, radix);
                         ^~~~~~~
                         strtoul
/opt/android-ndk-linux/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdlib.h:93:15: note: 'strtoul' declared here
unsigned long strtoul(const char* __s, char** __end_ptr, int __base);
              ^
2 errors generated.
```

### Affected versions

r23, r24, r25

### Host OS

Linux

### Host OS version

Ubuntu 20.04

### Affected ABIs

armeabi-v7a

### Build system

CMake

### minSdkVersion

19

**Comment by JMLX42** [comment] 2022-11-08 07:41
The following works:

```
mkdir build
cd build
cmake .. \
  -DANDROID_PLATFORM=android-19
  -DCMAKE_BUILD_TYPE=Release \
  -DANDROID_ABI=armeabi-v7a \
  -DANDROID_STL=c++_shared
make
```

The following does *not* work:

```
mkdir build
cd build
cmake .. \
  -DANDROID_PLATFORM=android-24
  -DCMAKE_BUILD_TYPE=Release \
  -DANDROID_ABI=armeabi-v7a \
  -DANDROID_STL=c++_shared
make
```

**Comment by JMLX42** [comment] 2022-11-08 08:30
The following works:

```
mkdir build
cd build
cmake .. \
  -DANDROID_PLATFORM=android-19
  -DCMAKE_BUILD_TYPE=Release \
  -DANDROID_ABI=armeabi-v7a \
  -DANDROID_STL=c++_shared
make
```

The following does *not* work:

```
mkdir build
cd build
cmake .. \
  -DANDROID_PLATFORM=android-24
  -DCMAKE_BUILD_TYPE=Release \
  -DANDROID_ABI=armeabi-v7a \
  -DANDROID_STL=c++_shared
make
```

Apparently, is works from `android-19` up to `android-20`.

**Comment by Grimler91** [comment] 2022-11-08 10:25
pcre's CMakeLists.txt uses `check_function_exists` to check if `strtoq` is available. The [documentation for that macro](https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html) lists several shortcomings, and advises to use `cmake_symbol_exists` instead. pcre builds fine if `cmake_symbol_exists` is used instead, or if we skip cmake altogether and use the `configure && make` scripts.

So, don't think this is a ndk issue, rather cmake/pcre issue.

**Comment by JMLX42** [comment] 2022-11-08 11:41
@Grimler91 thank you! Any reason why it still works up to `android-20` though?

**Comment by Grimler91** [comment] 2022-11-08 13:23
> @Grimler91 thank you! Any reason why it still works up to `android-20` though?

Don't know, haven't tested building with an older ndk. Maybe ndk developers have an idea

**Comment by enh-google** [comment] 2022-11-08 17:04
> > @Grimler91 thank you! Any reason why it still works up to `android-20` though?
> 
> Don't know, haven't tested building with an older ndk. Maybe ndk developers have an idea

i can kind of answer this...

basically, strtoq() and strtouq() _are_ in bionic, and have been since API 21. (despite the fact that they're not in any header file.)

i don't know anything about cmake, but i suspect the difference there is that `check_function_exists` is looking for the _symbol_ in the ELF file (which succeeds, correctly) while `cmake_symbol_exists` is looking for the _declaration_ in the header file (which fails, also correctly).

obviously the real question though is "why are they in libc.so but not in any header file?", and that's where i don't have a really satisfactory answer because i don't find any explicit record of any decisions in the history. as far as i can tell, the _symbol_ was added by accident (possibly because we didn't even realize it wasn't in any header, and because it _is_ available on macOS/iOS, so i may have thought "oh, that might be useful for developers" without questioning who in their right mind wouldn't just use strtoll() instead) and then when we discovered that we had the symbol but not the declaration (while i was cleaning up our strto*() functions for other reasons), we left it like that because we couldn't really justify the disruption of adding it the headers.

**Comment by JMLX42** [comment] 2022-11-08 17:08
@enh-google thanks that makes a lot of sense.

> obviously the real question though is "why are they in libc.so but not in any header file?"

Would it make sense to add it to the headers then?

**Comment by DanAlbert** [comment] 2022-11-09 00:20
>> obviously the real question though is "why are they in libc.so but not in any header file?"
>
> Would it make sense to add it to the headers then?

It sounds like we should either add it to the header or remove it from the stub library. It sounds like it's probably better to just add it to the header, but if we for some reason don't want to make this available (I'm not familiar with the API, but if all we're doing is giving you yet-another-footgun, might be better to remove entirely), we should also remove it from the stubs. Being inconsistent is likely the worst option.

**Comment by JMLX42** [comment] 2022-11-09 10:19
>  i'm working on resigning myself to adding this to the header

AFAIK in this very case, PCRE has a fallback:

```cpp
#if defined HAVE_STRTOQ
  long long r = strtoq(str, &end, radix);
#elif defined HAVE_STRTOLL
  long long r = strtoll(str, &end, radix);
#elif defined HAVE__STRTOI64
  long long r = _strtoi64(str, &end, radix);
#elif defined HAVE_STRTOIMAX
  long long r = strtoimax(str, &end, radix);
#else
#error parse_longlong_radix: cannot convert input to a long-long
#endif
```

So I guess `HAVE_STRTOLL` would just work in this case assuming it is in the headers *and* in the lib (AFAIK it is because CMake's `check_function_exists` finds it). Correct?

> i'm working on resigning myself to adding this to the header

Any reason why those functions have been (apparently) [*removed* from `android-20`+](https://github.com/android/ndk/issues/1803#issuecomment-1306823906)?

Can't we just revert the corresponding commit?

**Comment by enh-google** [comment] 2022-11-09 16:17
https://android-review.googlesource.com/c/platform/bionic/+/2295477 removes the aliases from bionic.

**Comment by DanAlbert** [comment] 2022-11-10 19:54
Change is merged into bionic. I'll update the sysroot for r25 when we get a new toolchain so this will ship in r25c.

**Comment by DanAlbert** [comment] 2023-01-19 22:18
Hmm, it's actually complicated for us to get a sysroot update that includes this into r25c, since the platform is no longer producing stubs for kitkat... The platform stopped producing those in August, but the fix was merged in November. It would take quite some doing to get that change into the NDK (new branch of AOSP). Given that this isn't a regression, I think we need to punt this to r26.

**Comment by DanAlbert** [comment] 2023-01-19 22:18
(and it's already fixed in r26)

**Closed by DanAlbert** 2023-01-19 22:18 UTC
Labels: bug
