### ISSUE TITLE
Simpleperf: do not works with some cpu-cores in the multi-core architecture?

### ISSUE THREAD

**Issue by xhuilala** [android/ndk#784] opened 2018-09-03 08:29 UTC
Hi,

I have some confusion on simpleperf.

I use the command: "./simpleperf stat -p pid" to get  the cpu-cycle and instruction information of my algorithm running on an Android device. However, when I bind the process to big cpu cores, simpleperf gets zero cpu-cycle and zero instruction. And I switch to bind the process to small cpu cores, the value of both cpu-cycle and instruction can get but not consistent. 

How can it explain?

Thanks a lot.

* NDK Version: 17.1.4828580

**Comment by yabinc** [comment] 2018-09-05 20:45
As I know, simpleperf may get zero cpu cycles and zero instruction of a process in below situations:
1. the process isn't running while stating.
2. there is some kernel bug making hardware counters not working.

If both cpu-cycles and cpu-clock (which is software counter) are zero, probably it is the first case.
If cpu-cycles is zero, but cpu-clock (which is software counter) isn't zero, probably it is the second case. And I'd like to know your device type and android version if you'd like to share.

You can also use ./simpleperf stat --verbose --log verbose -p pid to show more details to help find out the reason.

**Comment by xhuilala** [comment] 2018-09-06 04:03
I used SDM845 for arm64 (sdm845) by QUALCOMM with Android 8

**Comment by yabinc** [comment] 2018-09-06 18:27
SDM845 is a very new soc. I have a SDM845 with Android 9 and kernel 4.9, but I can't reproduce the problem. To verify if it is a kernel bug, can you provide more info:
The output of `simpleperf stat --log verbose --verbose --cpu 0-7 -e cpu-cycles,cpu-clock --duration 10 -p pid`.
And the kernel version by `uname -a`.

A kernel bug is likely to have this behavior: it works fine when the device is restarted, but has problem after profiling for some times. So can you also provide the output of the above stat cmd just after device restart?

**Comment by xhuilala** [comment] 2018-09-09 04:13
The device is with kernel 4.9.
I typed the simpleperf stat cmd after device restart, and the output shows like that:

```
Performance counter statistics:
cpu-cycles(tid 5225, cpu 0): count 0, time_enabled 5324743401, time running 0, id 35
cpu-cycles(tid 5225, cpu 1): count 0, time_enabled 5324743401, time running 0, id 36
cpu-cycles(tid 5225, cpu 2): count 0, time_enabled 5324743401, time running 0, id 37
cpu-cycles(tid 5225, cpu 3): count 0, time_enabled 5324743401, time running 0, id 38
cpu-cycles(tid 5225, cpu 4): count 0, time_enabled 5324743401, time running 0, id 39
cpu-cycles(tid 5225, cpu 5): count 374586, time_enabled 5324743401, time running 305156, id 40
cpu-cycles(tid 5225, cpu 6): count 14849247849, time_enabled 5324743401, time running 5324438245, id 41
cpu-cycles(tid 5225, cpu 7): count 0, time_enabled 5324743401, time running 0, id 42
cpu-clock(tid 5225, cpu 0): count 0, time_enabled 5324880069, time running 0, id 43
cpu-clock(tid 5225, cpu 1): count 0, time_enabled 5324880069, time running 0, id 44
cpu-clock(tid 5225, cpu 2): count 0, time_enabled 5324880069, time running 0, id 45
cpu-clock(tid 5225, cpu 3): count 0, time_enabled 5324880069, time running 0, id 46
cpu-clock(tid 5225, cpu 4): count 0, time_enabled 5324880069, time running 0, id 47
cpu-clock(tid 5225, cpu 5): count 271823, time_enabled 5324880069, time running 279844, id 48
cpu-clock(tid 5225, cpu 6): count 5324685844, time_enabled 5324880069, time running 5324600225, id 49
cpu-clock(tid 5225, cpu 7): count 0, time_enabled 5324880069, time running 0, id 50
   14,849,622,435  cpu-cycles   # 11.868570 GHz  (12%)
  5324.957667(ms)  cpu-clock    #                (12%)
Total test time: 10.009376 seconds.
```

 And I did the profiling after some times, the output shows that:

```
Performance counter statistics:
cpu-cycles(tid 5703, cpu 0): count 0, time_enabled 0, time running 0, id 683
cpu-cycles(tid 5703, cpu 1): count 0, time_enabled 0, time running 0, id 684
cpu-cycles(tid 5703, cpu 2): count 0, time_enabled 0, time running 0, id 685
cpu-cycles(tid 5703, cpu 3): count 0, time_enabled 0, time running 0, id 686
cpu-cycles(tid 5703, cpu 4): count 0, time_enabled 0, time running 0, id 687
cpu-cycles(tid 5703, cpu 5): count 0, time_enabled 0, time running 0, id 688
cpu-cycles(tid 5703, cpu 6): count 0, time_enabled 0, time running 0, id 689
cpu-cycles(tid 5703, cpu 7): count 0, time_enabled 0, time running 0, id 690
cpu-clock(tid 5703, cpu 0): count 0, time_enabled 5511955021, time running 0, id 691
cpu-clock(tid 5703, cpu 1): count 0, time_enabled 5511955021, time running 0, id 692
cpu-clock(tid 5703, cpu 2): count 0, time_enabled 5511955021, time running 0, id 693
cpu-clock(tid 5703, cpu 3): count 0, time_enabled 5511955021, time running 0, id 694
cpu-clock(tid 5703, cpu 4): count 0, time_enabled 5511955021, time running 0, id 695
cpu-clock(tid 5703, cpu 5): count 0, time_enabled 5511955021, time running 0, id 696
cpu-clock(tid 5703, cpu 6): count 5511889601, time_enabled 5511955021, time running 5511668198, id 697
cpu-clock(tid 5703, cpu 7): count 283698, time_enabled 5511955021, time running 286823, id 698
                0  cpu-cycles   # 0.000000 GHz  (100%)
  5512.173299(ms)  cpu-clock    #               (12%)
Total test time: 7.009429 seconds.
```

As you said, Android 9 doesn't have the problem. Is there a kernel bug on Android 8?

**Comment by DanAlbert** [comment] 2018-10-19 03:10
@yabinc: anything to be done here?

**Comment by DanAlbert** [comment] 2018-11-27 20:52
@yabinc: ping? Should this be closed?

**Comment by yabinc** [comment] 2018-11-28 00:38
Please don't close it. I left it when I was back from vacation.
It seems after restart, the stat result is fine. But after sometime running, the time_enabled for cpu-cycles become 0, which looks wrong. I don't know why it can happen, will check kernel code for possible answers.

**Comment by DanAlbert** [comment] 2018-11-28 04:52
SGTM, just wondering how to triage. If you're looking now I'll triage for r20. Reassign that if you need to.

**Comment by DanAlbert** [comment] 2019-09-19 03:19
@yabinc Did this get fixed?

**Comment by yabinc** [comment] 2019-09-20 00:28
I don't know any kernel bug that can make time_enabled for cpu-cycles to be 0.
Reading the kernel code doesn't give any hint. The kernel code ensures that as long as a task is scheduled on cpu, the enabled time should increase.

It is clearly a kernel bug caused by vendor code. Because hardware events are affected, while software events (cpu-clock) work well.

Since it is qcom device, we do find a qcom bug in 4.9 kernel in Android P cts test https://b.corp.google.com/issues/79750044. But I have tested that the bug can't make time_enabled for cpu-cycles to be 0.
Probably we don't need to anything here. This is a kernel bug that we can't fix. And the new cts test probably can already catch it.

**Closed** 2019-09-20 00:33 UTC
