### ISSUE TITLE
[BUG] C++20 header <concepts> nearly empty

### ISSUE THREAD

**Issue by prapin** [android/ndk#1876] opened 2023-04-28 11:07 UTC
### Description

In Android  NDK, the standard C++20 header `<concepts>` exists but is nearly empty.
While it should define all [those concepts](https://en.cppreference.com/w/cpp/header/concepts), only `same_as` is actually defined (although the header synopsis is complete).
According to [cppreference](https://en.cppreference.com/w/cpp/20), the concepts library have been implemented in GNU libstdc++ as of version 10, and in Clang libc++ as of version 13. Therefore, it should have been supported by Android NDK for a long time, but is not.

Small test case: this snippet fails to compiles in C++20 standard with NDK:
```
// Compile with: -std=c++20
#include <concepts>

static_assert(std::integral<int>);
static_assert(std::floating_point<double>);
static_assert(std::same_as<int, signed>);
static_assert(std::convertible_to<int, long>);
```

### Affected versions

r23, r24, r25

### Host OS

Mac

### Host OS version

macOS 13.2.1

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

ndk-build

### minSdkVersion

25

**Comment by DanAlbert** [comment] 2023-04-28 19:07
It's always worth looking at the pinned issues before filing.

Duplicate of https://github.com/android/ndk/issues/1530.

**Closed by DanAlbert** 2023-04-28 19:07 UTC
Labels: bug

**Comment by prapin** [comment] 2023-04-28 19:18
I searched for `concepts` in open and closed tickets before filling. No reference whatsoever.
The "duplicate" is somewhat similar, but refers to another head and even another C++ standard.

**Comment by DanAlbert** [comment] 2023-04-28 19:22
That bug is "update libc++". When it was titled that no one was finding it either. I keep trying things to stem the flow of duplicate bugs. What would have helped you find that?

**Comment by prapin** [comment] 2023-04-28 19:26
Well, I just discovered now the concept of "pinned issue".
I didn't paid attention to those until now. I promise I will take attention
to them the next time I have any issue to report on GitHub.

Le ven. 28 avr. 2023 à 21:22, Dan Albert ***@***.***> a
écrit :

**Comment by DanAlbert** [comment] 2023-04-28 19:51
They're pretty helpful :) I've also updated the bug category page to quite loudly tell people they exist, so that should help.

**Comment by enh-google** [comment] 2023-04-28 19:57
(it might be useful for us to make clear in the title of the libc++ bug just how old the current version is, too. i don't know myself!)

**Comment by DanAlbert** [comment] 2023-04-28 20:00
Took some golfing to make a more detailed title fit in the pinned card, but how's that?

**Comment by enh-google** [comment] 2023-04-28 22:06
lgtm. (i was able to use https://releases.llvm.org/ to see that that's llvm 10.)
