### ISSUE TITLE
[BUG] Native breakpoints not working (Arm64 devices) 

### ISSUE THREAD

**Issue by twisted89** [android/ndk#1754] opened 2022-08-23 08:43 UTC
### Description

Native breakpoints no longer seem to be working on certain devices. For example, Samsung Galaxy S20 FE, LG G6 running Android 12 and 11 respectively. 

When launching a debug session with a native breakpoint set the following error shows in the LLDB console:

warning: failed to set breakpoint side 0xa3d741c for breakpoint -5.1: error: 9 sending the breakpoint request. 

Testing the exact same app on an older armeabi_v7a device (HTC One M7 running Android 11) the breakpoints work without issue. Testing in x86/x86_64 AVD's also works without issue which leads me to believe the issue is specific to arm64 devices.

Running the 'image list' command in LLDB seems to be missing the native library, adding the symbol directory to LLDB settings doesn't help, nor does add-sym or add image commands.
Although the add image command does succeed, and the breakpoint suggests it will be hit, it is still ignored. 

I've tested various combinations of Build tools and NDK versions with no success and also the latest stable, beta and canary versions of android studio. a test project is attached.
[TestApp.zip](https://github.com/android/ndk/files/9400820/TestApp.zip)
 

### Affected versions

r23, r24, r25

### Host OS

Linux, Windows

### Host OS version

11

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

CMake

### minSdkVersion

24

### Device API level

Tested on 30 & 31

**Comment by enh-google** [comment] 2022-08-23 15:49
i think this is a dupe of https://issuetracker.google.com/243471116, which is actually (even though you had no way to know this) a better place to file the bug because it's more likely that someone from Studio will be looking at it... (i've already added the appropriate person there.)

**Comment by DanAlbert** [comment] 2022-08-23 17:22
I'll keep this open for triage reasons :) Will lock the thread so it's clear that discussion belongs on https://issuetracker.google.com/243471116

**Comment by DanAlbert** [comment] 2024-08-21 20:46
Other bug was closed (seemingly a problem with other software on the device, not lldb).

**Closed by DanAlbert** 2024-08-21 20:46 UTC
Labels: bug
