### ISSUE TITLE
[BUG] Methods on empty std::array not declared as constexpr

### ISSUE THREAD

**Issue by levinli303** [android/ndk#1835] opened 2023-01-27 04:33 UTC
### Description

The specialization of array<_Tp, 0> is missing constexpr on its methods.

In the `<array>` header array has
```
    _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_AFTER_CXX14
    value_type* data() _NOEXCEPT {return __elems_;}
```
it has _LIBCPP_CONSTEXPR_AFTER_CXX14

But in specialization array<_Tp, 0>
```
    _LIBCPP_INLINE_VISIBILITY
    value_type* data() _NOEXCEPT {return reinterpret_cast<value_type*>(__elems_);}
```
it does not have it.

Upstream libc++ https://reviews.llvm.org/D80821 fixed it as early as in clang 11. Maybe NDK has not updated the array header?

### Affected versions

r25

### Host OS

Linux, Mac, Windows

### Host OS version

macOS 13

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

CMake

### minSdkVersion

21

**Comment by stephenhines** [comment] 2023-01-27 07:48
This is a duplicate of #1530 as libcxx hasn't been updated yet.

**Closed** 2023-01-27 07:48 UTC
Labels: bug

**Comment by stephenhines** [comment] 2023-01-27 07:51
Duplicate of #1530
