### ISSUE TITLE
[BUG] Broken symlinks in android-ndk - r23b

### ISSUE THREAD

**Issue by a4z** [android/ndk#1671] opened 2022-02-16 13:08 UTC
### Description

There are broken symlinks in at least the Mac package, but maybe also the Linux one

for example the file `toolchains/llvm/prebuilt/darwin-x86_64/aarch64-linux-android/bin/as` 

```
ls -l toolchains/llvm/prebuilt/darwin-x86_64/aarch64-linux-android/bin/as
lrwxr-xr-x  1 a4z  staff  149 Sep 30 00:54 toolchains/llvm/prebuilt/darwin-x86_64/aarch64-linux-android/bin/as -> /Volumes/Android/buildbot/src/android/ndk-release-r23/out/darwin/android-ndk-r23b/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-as
```

as you can see, the link goes to `/Volumes/Android/buildbot/src/....`

there might be more 

The reason why this is a problem is that this broke packaging of the android-ndk for the conan center
see
https://github.com/conan-io/conan-center-index/pull/8168

so r23b currently exists just for Windows on the conan center index

### Affected versions

r23

### Host OS

Mac

### Host OS version

MacOS 12.1

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

Other (specify below)

### Other build system

all

### minSdkVersion

not effected

**Comment by DanAlbert** [comment] 2022-02-16 22:58
Thanks for the detail. Confirmed that the same problem is present on linux. It won't be on windows because windows doesn't support symlinks (yes I know it kind of does but it doesn't generally so it doesn't at all as far as we're concerned).

The problem is unique to r23b. This was caused by https://android-review.googlesource.com/c/platform/ndk/+/1817218 (the fix for https://github.com/android/ndk/issues/1569) was only in that release. r24+ don't have those directories at all because they only exist to appease `-fno-integrated-as`, but GAS is gone in r24+ so that flag won't work out of the box anyway.

**Comment by rprichard** [comment] 2022-02-16 23:20
This change needs to be cherry-picked to r23c:

https://android-review.googlesource.com/c/platform/ndk/+/1877617

Might also want to cherry-pick the test:

https://android-review.googlesource.com/c/platform/ndk/+/1877830/

**Comment by orifmilod** [comment] 2022-03-29 16:24
For those who face this issue with the broken SIM link - please refer to this [comment](https://github.com/android/ndk/issues/1569#issuecomment-1082091664)

**Comment by DanAlbert** [comment] 2022-04-22 20:29
Should be fixed in r23 [build 8486889](https://ci.android.com/builds/branches/aosp-ndk-release-r23/grid?head=8486889&tail=8486889).

**Closed by DanAlbert** 2022-04-22 20:29 UTC
Labels: bug

**Comment by ZijunZhaoCCK** [comment] 2022-05-11 16:51
@orifmilod  The latest build is [build 8568313](https://android-build.googleplex.com/builds/branch-dashboard/aosp-ndk-release-r23?build_id=8568313)

**Comment by DanAlbert** [comment] 2022-05-11 17:07
Sorry about that. I think the API of the build page must have changed so my link no longer worked. Updated.

The link @ZijunZhaoCCK gave you though (thanks!) is the build that we're expecting to ship though, so that's a better link anyway :)

**Comment by orifmilod** [comment] 2022-05-11 17:47
@ZijunZhaoCCK I cannot access the link. It says I need to sign in with a google account.

**Comment by ZijunZhaoCCK** [comment] 2022-05-11 17:59
> Should be fixed in r23 [build 8486889](https://android-build.googleplex.com/builds/branch-dashboard/aosp-ndk-release-r23?build_id=8486889).

@orifmilod  Could you access this link? I think the only difference between them is the build_id.

**Comment by enh-google** [comment] 2022-05-11 18:00
> > Should be fixed in r23 [build 8486889](https://android-build.googleplex.com/builds/branch-dashboard/aosp-ndk-release-r23?build_id=8486889).
> 
> @orifmilod Could you access this link? I think the only difference between them is the build_id.

they're both googleplex.com links, which only work for googlers, no? don't we need a ci.android.com link?

**Comment by orifmilod** [comment] 2022-05-11 18:02
@ZijunZhaoCCK  - nope I can't.

**Comment by DanAlbert** [comment] 2022-05-11 18:35
Oh, _that's_ why the format changed. I wasn't paying close enough attention. Yeah, those links won't work. afaict the public page doesn't support linking to a single build (don't ask me why, I've filed a bug). https://ci.android.com/builds/branches/aosp-ndk-release-r23/grid? is the page, there are only a few builds, match the build numbers to the ones mentioned above.

**Comment by orifmilod** [comment] 2022-05-11 19:24
"don't ask me why, I've filed a bug" This is soo relatable xd 
The new [link](https://ci.android.com/builds/branches/aosp-ndk-release-r23/grid?) shows and empty list. 

![Screenshot 2022-05-11 at 21 22 45](https://user-images.githubusercontent.com/25881325/167929518-7aeb07ff-3988-4ce9-9851-55b14011ffe3.png)

**Comment by DanAlbert** [comment] 2022-05-11 19:27
Forking this into a new thread: https://github.com/android/ndk/issues/1715
