### ISSUE TITLE
[DOC] changelog is not clear about the LLVM version

### ISSUE THREAD

**Issue by H-G-Hristov** [android/ndk#1939] opened 2023-09-20 19:08 UTC
### Description

Using C++23 with the NDK r26

```cmake
target_compile_features(${CMAKE_PROJECT_NAME}
        PUBLIC
            cxx_std_20)
```

with latest CMake

```Kotlin
    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.27.5"
        }
    }
```

Adding this line to the default sample create by Android studio fails with:

```txt
FAILURE: Build completed with 4 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/Users/hristohristov/AndroidStudioProjects/MyApplication2/app/.cxx/Debug/3c5w5n6q/arm64-v8a'
  [1/2] Building CXX object CMakeFiles/myapplication.dir/native-lib.cpp.o
  FAILED: CMakeFiles/myapplication.dir/native-lib.cpp.o 
  /Users/hristohristov/Library/Android/sdk/ndk/26.0.10792818/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=aarch64-none-linux-android29 --sysroot=/Users/hristohristov/Library/Android/sdk/ndk/26.0.10792818/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -Dmyapplication_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -std=gnu++23 -fPIC -MD -MT CMakeFiles/myapplication.dir/native-lib.cpp.o -MF CMakeFiles/myapplication.dir/native-lib.cpp.o.d -o CMakeFiles/myapplication.dir/native-lib.cpp.o -c /Users/hristohristov/AndroidStudioProjects/MyApplication2/app/src/main/cpp/native-lib.cpp
  error: invalid value 'gnu++23' in '-std=gnu++23'
  note: use 'c++98' or 'c++03' for 'ISO C++ 1998 with amendments' standard
  note: use 'gnu++98' or 'gnu++03' for 'ISO C++ 1998 with amendments and GNU extensions' standard
  note: use 'c++11' for 'ISO C++ 2011 with amendments' standard
  note: use 'gnu++11' for 'ISO C++ 2011 with amendments and GNU extensions' standard
  note: use 'c++14' for 'ISO C++ 2014 with amendments' standard
  note: use 'gnu++14' for 'ISO C++ 2014 with amendments and GNU extensions' standard
  note: use 'c++17' for 'ISO C++ 2017 with amendments' standard
  note: use 'gnu++17' for 'ISO C++ 2017 with amendments and GNU extensions' standard
  note: use 'c++20' for 'ISO C++ 2020 DIS' standard
  note: use 'gnu++20' for 'ISO C++ 2020 DIS with GNU extensions' standard
  note: use 'c++2b' for 'Working draft for ISO C++ 2023 DIS' standard
  note: use 'gnu++2b' for 'Working draft for ISO C++ 2023 DIS with GNU extensions' standard
  ninja: build stopped: subcommand failed.
  
  C++ build system [build] failed while executing:
      /opt/homebrew/bin/ninja \
        -C \
        /Users/hristohristov/AndroidStudioProjects/MyApplication2/app/.cxx/Debug/3c5w5n6q/arm64-v8a \
        myapplication
    from /Users/hristohristov/AndroidStudioProjects/MyApplication2/app
```

It looks like the toolchain doesn't support the latest standards C++23, C++26.

**Comment by DanAlbert** [comment] 2023-09-20 20:22
The version of Clang in r26 doesn't have this because upstream LLVM didn't. r27 will have a newer compiler.

I'm closing this because the only work here for us is "update clang again", which is something we always do as part of every major version, and we don't bother with tracking bugs for that (I can guarantee that I will not remember to close this bug when it is fixed, so it's not going to be a useful source of data).

**Comment by Zingam** [comment] 2023-09-24 16:41
According to r26 release notes: Updated LLVM to clang-r487747c, based on LLVM 17 development.

Clang 17 does have the C++23 switch. How come the bundled doesn't do it? AFAIK these switches were added several months ago.

![image](https://github.com/android/ndk/assets/3337419/4dcd3f32-ff66-4424-adaa-4e1a1b7c29b3)

**Comment by DanAlbert** [comment] 2023-09-25 18:45
> **based on** LLVM 17 **development**.

It is not 17.0. It is a development snapshot of LLVM 17. See the AndroidVersion.txt file in the same directory as the Clang binary.

**Comment by enh-google** [comment] 2023-09-25 19:53
i suspect that's going to confuse others too. did we have clearer wording in the past we can reuse? if not, should we be more explicit with something like "between LLVM 16 and 17"?

**Comment by DanAlbert** [comment] 2023-09-25 19:59
It's the wording we've always used: https://github.com/android/ndk/wiki/Changelog-r17. Prior to NDK r17 changelogs didn't mention the LLVM version at all. It was much more obvious what the text meant when LLVM was still on svn and that revision number meant something obvious.

I was working on improving the wording already, but I'm about a dozen "one five minute task"s deep right now, so I'll reopen this so I don't forget to do that when I inevitably don't get to it today.

**Comment by DanAlbert** [comment] 2023-09-25 21:00
https://android-review.git.corp.google.com/c/platform/ndk/+/2761268

**Closed** 2023-09-25 22:22 UTC
Labels: docs

**Comment by H-G-Hristov** [comment] 2024-02-23 09:38
@DanAlbert  The release notes:
https://github.com/android/ndk/wiki/Changelog-r26#r26c
claim:
> Updated LLVM to clang-r487747e. See AndroidVersion.txt and clang_source_info.md in the toolchain directory for version information.
And checking in the toolchain directory I see the version number: `17.0.2` Does this mean that the toolchain was updated to a proper final 17.0.2 release from upstream or is it still the pre-release snapshot 17.0.0.
Starting LLVM 18, now the release versions will start with xx.1 (e.g. 18.1).
So my point is: if 17.0.2 isn't the RTM version than the notes are still misleading.

**Comment by DanAlbert** [comment] 2024-02-23 20:40
> And checking in the toolchain directory I see the version number: 17.0.2 Does this mean that the toolchain was updated to a proper final 17.0.2 release from upstream

No, and it never will be. We will always build our own binaries for supply chain protection reasons. They are not going to be a direct match to any upstream release in the near future because upstream releases rarely meet the quality bar required to build Android.

> So my point is: if 17.0.2 isn't the RTM version than the notes are still misleading.

That version isn't mentioned in the release notes.

**Comment by enh-google** [comment] 2024-02-23 20:50
> [17.0.2] isn't mentioned in the release notes.

not directly, but the release notes now point you here, which does say 17.0.2:
```
~/aosp-main-with-phones/prebuilts/clang/host/linux-x86/clang-r487747c$ cat AndroidVersion.txt 
17.0.2
based on r487747c
for additional information on LLVM revision and cherry-picks, see clang_source_info.md
```

**Comment by DanAlbert** [comment] 2024-02-23 21:10
Ah. That's up to @pirama-arumuga-nainar

**Comment by DanAlbert** [comment] 2024-02-23 21:12
@H-G-Hristov what questions are you actually trying to answer by finding the version number? The problem is that there is no version number to find other than the one in the changelog. "What is in this LLVM?" is answered by `clang_source_info.md`. If you're looking for a more succinct answer than that file, that's what r487747c is. If you're looking for a connection to an LLVM released version, there isn't one.

**Comment by DanAlbert** [comment] 2024-02-23 21:26
https://android-review.googlesource.com/c/platform/ndk/+/2974330

**Comment by Zingam** [comment] 2024-04-23 15:16
This is a bit off-topic.

I implemented several libc++ papers in LLVM 18 but none of them were included in NDK r27 currently. When does branching LLVM happen in AOSP?
If I want to get something into NDK r28 what would be the approximate deadline?
