### ISSUE TITLE
[BUG] NDK R25 not supported P0919R3 Heterogeneous lookup for unordered containers 

### ISSUE THREAD

**Issue by LimeVista** [android/ndk#1886] opened 2023-05-16 08:26 UTC
R25 NDK based on LLVM 14. But not supported P0919R3 [Heterogeneous lookup for unordered containers](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0919r3.html).

**Comment by DanAlbert** [comment] 2023-05-16 20:39
Duplicate of https://github.com/android/ndk/issues/1530

**Closed by DanAlbert** 2023-05-16 20:39 UTC
Labels: bug
