### ISSUE TITLE
vsnprintf return -1 with any buffer size inside separated thread

### ISSUE THREAD

**Issue by formatCvt** [android/ndk#879] opened 2018-12-23 15:10 UTC
#### Description

On some Android devices `vsprintf` return -1 with any buffer size inside separated thread for non-english languages. 

##### Steps to reproduce:
1. Take any format function (i've tried many). For example this one https://github.com/cocos2d/cocos2d-x/blob/cocos2d-x-3.17/cocos/base/ccUTF8.cpp#L43
2. Call format function in separated thread twice with delay (1-2 sec) with non-english language text. 

##### Example code: 
```
std::thread _thread = std::thread([](){
    std::string test1 = format("Any text here. Language doesn't matter %d", 1);
    // sleep is important. vsnprint stop working (returns -1) after some delay, not immediately
    sleep(2);
    // non-english language is important
    std::string test2 = format("运送%d个乘客！电工、防火员和警察不算", 1);
});
_thread.detach();
```

Or use this test case https://github.com/formatCvt/android-ndk-vsnprintf-issue

#### Environment Details
 * NDK Version: staring from r15c/ (with r14b everything is fine)
 * Build system: cmake/ndk-build
 * Host OS: MacOS 10.13.6/Linux Ubuntu 16.04
 * Compiler: clang
 * ABI: armeabi-v7a
 * STL: c++_static
 * NDK API level: 16
 * Device API level: 24, 26 

##### Non-affected devices (tested)
* Samsung GT-I9082 (Android 4.2.2, API 17)
* Xiaomi Mi A1 (Android 8.1.0, API 27)
* DIGMA VOX S501 3G VS5002PG (Android 5.1, API 22)
* TCL 5065D (Android 5.1.1, API 22)
* Sony E5303 (Android 6.0 API 23)
* Google Pixel XL (Android 9, API 28)
* Google Pixel 3 XL (Android 9, API 28)

##### Affected devices (tested):
* Xiaomi Mi PAD 3 (Android 7.0.0, API 24)

##### Affected devices (according to top devices from crashlytics issue):
* waiting for new statistic from crashlytics

#### Screenshots:
![screenshot1](https://user-images.githubusercontent.com/9342933/50384804-259a8980-06db-11e9-8db6-f4ed4363fc68.png)
![screenshot2](https://user-images.githubusercontent.com/9342933/50384808-33500f00-06db-11e9-9c63-07c75c449692.png)

**Comment by formatCvt** [comment] 2018-12-26 08:48
We've found and fix other bug in our project related to this issue in crashlytics. 
Bug with `vsnprintf` 100% reproduce on xiaomi mi pad 3, but i'm not sure about other devices right now.
We are waiting for  new statistic from crashlytics

**Comment by DanAlbert** [comment] 2019-01-07 21:08
Based on your report, this is either a bug with that specific device or perhaps with android-24, not the NDK. This worked in older NDK releases because libandroid_support used to includes its own implementation of vsnprintf. That implementation was the source of countless other bugs, so it is no longer used.

Even if we were to bring that back, libandroid_support is not used for 21+ since it by design overrides system behavior and increases the size of your application, which is generally undesirable.

I'd be curious if this affects other android-24 devices or just that one device.

**Comment by alexcohn** [comment] 2019-01-14 08:11
> I'd be curious if this affects other android-24 devices or just that one device.

I tried this on a Chinese 7.0 device, same test case passed smoothly.

**Comment by DanAlbert** [comment] 2019-01-14 18:59
Thanks for the verification. Sounds like this tablet has a broken OS.

As noted above, fixing this in the NDK would increase the size of _every_ NDK app on _every_ device, so we won't be fixing this in the NDK. If you want to work around this in your application, in the same way you did on previous NDKs, you could bundle the implementation from the older NDK. Note that it has other bugs though (which will affect all devices), so that may not be what you want.

**Comment by formatCvt** [comment] 2019-01-23 12:11
According to latest statistics from crashlytics affected devices: 
- Xiaomi Mi PAD 3 (Android 7.0.0, API 24)
- TCT (Alcatel) Alcatel 1X (U5A_PLUS_4G), Android 8.1
- Xiaomi Redmi 6A (cactus), Android 8.1
- Xiaomi Redmi 6 (cereus), Android 8.1
- Huawei Honor 7A (HWDUA-M), Android 8.1

I agree, this list is too short to be fixed in the NDK
We are switched to fmtlib and this bug is gone.

**Comment by enh** [comment] 2019-01-25 20:59
actually, although this isn't a NDK issue, i will add a CTS test for this...

**Closed** 2020-04-14 00:41 UTC
Labels: bug
