### ISSUE TITLE
[Bug]: Template specialization out of line definition error

### ISSUE THREAD

**Issue by RedBrumbler** [android/ndk#1941] opened 2023-09-27 17:24 UTC
### Description

Attempting to define a method for a templated class specialization leads to the error `out-of-line definition of 'method' from class 'Bar<T>' without definition`. 
This is not the case on stock clang version 17.0.1, but is the case on NDK r26 clang 17.0.2 (Android 10087095, based on r487747c)

Code example
```c++
template<typename T>
concept Foo = true;

template<typename T>
class Bar;

template<Foo T>
class Bar<T> {
    void method();
};

template<Foo T>
void Bar<T>::method() {} // error: out-of-line definition of 'method' from class 'Bar<T>' without definition
```
Attached is [TestCase.zip](https://github.com/android/ndk/files/12741376/TestCase.zip) containing a test case. In the example clang++ bundled with ndk r26 is executed to compile main.cpp, but this yields the error mentioned before.

if the clang executed is replaced with the one from llvm/llvm-project (version 17.0.1) this error does not occur and compilation succeeds

In the following godbolt link this same problem is showcased to occur on clang 16.0.0 from the llvm project, so the fix for this problem has to have been implemented sometime between clang 16.0.0 and clang 17.0.1 https://godbolt.org/z/6Tf98xfsW

Since it doesn't matter which target you compile for, it seems to be a frontend issue

### Affected versions

r26

### Host OS

Linux, Windows

### Host OS version

Windows 10, WSL Ubuntu 22.04

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

**Comment by appujee** [comment] 2023-09-27 19:56
seems like this is fixed in clang-17 but i'm yet to find out which patch fixed it.

A related issue which went the opposite direction (not in clang-16 but occurs in clang-17) https://github.com/llvm/llvm-project/issues/56482

**Comment by DanAlbert** [comment] 2023-09-27 19:56
It looks like this is not a regression (using your godbolt link, clang 13 and 14 also fail), so the fix will come in r27.

**Comment by DanAlbert** [comment] 2023-09-27 19:58
In fact, this is already fixed with the compiler that's currently in r27:

```
$ android-ndk-r27-canary/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ foo.cpp -std=gnu++20 -target aarch64-linux-android21 -shared
```

Works.

**Closed by DanAlbert** 2023-09-27 19:58 UTC
Labels: bug

**Comment by appujee** [comment] 2023-09-27 22:45
Pirama mentioned https://reviews.llvm.org/D145034 could have fixed this bug. Adding it here only for tracking purposes.
