### ISSUE TITLE
[Bug]: llvm-ar.exe error "unknown command"

### ISSUE THREAD

**Issue by MarcoCiaramella** [android/ndk#1815] opened 2022-12-08 18:38 UTC
### Description

Building of shaderc lib with the command
`ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk \ APP_STL:=c++_static APP_ABI=all libshaderc_combined`
exits with error
```
"[arm64-v8a] Combine: libshaderc_combined.a <= libglslang.a libOGLCompiler.a libOSDependent.a libshaderc.a libshaderc_util.a libSPIRV.a libHLSL.a libSPIRV-Tools.a libSPIRV-Tools-opt.a"
C:/Users/Marco/AppData/Local/Android/Sdk/ndk/25.1.8937393/build/../toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe: error: script line 1: unknown command: "create
make: *** [Android.mk:77: obj/local/arm64-v8a/libshaderc_combined.a] Error 1
```

### Affected versions

r23, r25

### Host OS

Windows

### Host OS version

10 Home 22H2

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

**Comment by DanAlbert** [comment] 2023-01-17 21:45
Was able to confirm this issue is Windows specific. I don't know anything more than that yet. Based on the error message it looks like one of the static libraries might actually be a linker script, and not one that's valid for this configuration.

Another question is why our tests don't catch this, because this library is covered by a test.

**Comment by jfgoog** [comment] 2023-01-19 20:18
Repro instructions for the pedantic:
* On windows, download a build of the NDK.
* cd sources\third_party\shaderc (If installed with Android Studio, this will be in C:\Users\<USERNAME>\AppData\Local\Android\Sdk\ndk\<VERSION)
* `<NDK_PATH>\build\ndk-build.cmd NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk \ APP_STL:=c++_static APP_ABI=all libshaderc_combined`

**Comment by DanAlbert** [comment] 2023-01-19 21:17
As mentioned (and totally overlooked by me originally... oops) in the OP, this isn't a regression. I did a bit of digging to try to figure out why this is happening (see below), but nothing obvious so far so we're going to punt from r25c (this bug is the last thing prevent its release).

https://cs.android.com/android/kernel/superproject/+/common-android-mainline:prebuilts/ndk-r23/sources/third_party/shaderc/Android.mk;l=45-56;drc=e7e2c3176647e71bfddc9303a62511415f197c40 is the code that's causing the problem. It's a custom build rule, so there isn't anything broken with ndk-build itself, just the shaderc rules.

That code hasn't been changed since 2016 when this library was first introduced, so this has likely been broken on Windows forever, though it's possible that it has only been broken since we switched to llvm-ar.

That code is using https://llvm.org/docs/CommandGuide/llvm-ar.html#mri-scripts. The llvm-ar docs sure make it sound like that should be host OS agnostic, but maybe the docs are wrong and the input language is assumed to be msvc flavored for that host? Would need to dive into the llvm-ar source to figure that out. I suppose it could also be an encoding issue? win32 shells write UTF-16 for file redirection by default...

**Comment by DanAlbert** [comment] 2023-01-19 21:29
That's probably what digit meant when he described the windows echo as "too weird"? https://cs.android.com/android/platform/superproject/+/master-ndk:ndk/sources/host-tools/toolbox/echo_win.c;l=36-38;drc=df2273f8f4c7854f753665e68bb305a221f010a9

**Comment by DanAlbert** [comment] 2023-01-19 21:31
Yes, that's it.

bash and powershell:

```
$ echo "foo"
foo
```

cmd:

```
> echo "foo"
"foo"
```

**Comment by DanAlbert** [comment] 2023-01-19 21:59
@dneto0 that rule needs to use `$(HOST_ECHO)` instead of `echo`, or better yet https://www.gnu.org/software/make/manual/html_node/File-Function.html.

Although we now know the problem, this still isn't going to make r25c, because we need to get the fix upstreamed to shaderc and then merged back down to Android.

**Comment by DanAlbert** [comment] 2023-01-19 22:03
Tested it to be sure. Here's the better rule:

```makefile
$(1)/combine.ar: $(addprefix $(1)/, $(ALL_LIBS))
	$(file >$(1)/combine.ar,create libshaderc_combined.a)
	$(foreach lib,$(ALL_LIBS),
		$(file >>$(1)/combine.ar,addlib $(lib))
	)
	$(file >>$(1)/combine.ar,save)
	$(file >>$(1)/combine.ar,end)
```

**Comment by abwood** [comment] 2023-01-20 12:08
Can confirm that the above fix by @DanAlbert works on my Windows machine. For those that want to do a local patch rather than rollback ndk, this update goes into Android.mk in `sources/third_party/shaderc/Android.mk`, replacing the combine.ar step on line 45.

Thanks for the fix!

**Comment by DanAlbert** [comment] 2023-04-20 22:10
@dneto0 ping

**Comment by DanAlbert** [comment] 2023-08-07 19:04
This was fixed upstream (https://github.com/google/shaderc/issues/1321) but doesn't appear to have made it to us yet.  Not a regression, so won't chase that for r26 (better to ship the bugs we know than update shaderc late in the cycle), but should be in r27.

**Comment by DanAlbert** [comment] 2024-04-25 20:03
Sorry for the lack of feedback here. I had to wait for the plan to fall into place before I could talk about it :)

The reason the upstream fix hasn't made it to the NDK yet is that our cross-compiling pipeline for Windows is no longer capable of building newer versions of the shader compiler. That proved difficult to fix, which caused the folks responsible to rethink why we're doing this anyway.

The plan now is to stop shipping these components in the NDK (I'm always a fan of that, coupling unrelated products like this just makes it hard for developers to use up-to-date tools) in favor of just getting the Vulkan SDK straight from LunarG. I expect is what most people with a multi-target build pipeline are doing anyway, so you've got the same tools for each target. A similar thing was previously done with the Vulkan Validation Layers: https://github.com/android/ndk/issues/1374

I'm in no hurry to remove the tools from the NDK until we've got all the new workflow stuff sorted out. They'll stick around until then, but as we can't build newer versions with our existing pipeline, they won't be getting upgrades. I'll get a bug filed here to track the removal at some point.

Just to be clear: the above applies to the shader tools, that is, the shader compilers (both online and offline). `vulkan.h` will still be a part of the sysroot (though I expect you probably _can_ get that straight from LunarG if you want one that's more up-to-date than the NDK, but that's of limited value since most of the devices in the wild won't have the new APIs anyway).

**Closed by DanAlbert** 2024-04-25 20:03 UTC
Labels: bug
