### ISSUE TITLE
Is there any plans to bring the backtrace function to Android?

### ISSUE THREAD

**Issue by horaciojcfilho** [android/ndk#925] opened 2019-03-04 12:46 UTC
Hello,

Is there any plans to bring the backtrace (http://man7.org/linux/man-pages/man3/backtrace.3.html) function to Android? This is a very common function to retrieve the stack trace.

Thankfully.

**Comment by enh** [comment] 2019-03-04 16:32
@cferris1000 is plans to make this available in the NDK at some point.

**Comment by horaciojcfilho** [comment] 2019-03-04 18:01
@enh @cferris1000 Please, that would be pretty lovely :)

**Comment by gpakosz** [comment] 2019-06-03 11:33
What's the difficulty in exposing `backtrace`. Last time I discussed it was in 2017 and it seems the heavy work landed then, see https://groups.google.com/d/msg/android-ndk/hhUv1mg3c_A/rOeW2woGBAAJ

**Comment by DanAlbert** [comment] 2019-06-03 20:46
AIUI the expected issues (I don't think @cferris1000 has had time to look yet) are that the new library has only ever been built against the latest API level (`minSdkVersion 28` is a dealbreaker, and I suspect there's some porting involved), and that it depends on some other non-NDK libraries (https://android.googlesource.com/platform/system/core/+/0c615194f499c6c197fec43ea038dad625da8f98/libunwindstack/Android.bp#128), which we'll need to find some solution for.

We'll also want to make sure we've tested it very thoroughly, and make sure that new libraries using the new unwinder can still interop with the old one so we don't repeat the same pain caused by libgcc -> libunwind incurred by ARM32 libc++.

None of those things are particularly challenging, but they do take time and no one has had the time yet.

**Comment by gpakosz** [comment] 2019-06-03 20:56
Thanks for the details @DanAlbert, appreciated 👍

**Comment by enh-google** [comment] 2022-05-09 23:57
fwiw, the <execinfo.h> header and its three functions were added to Android T (aka Android 13) in https://android-review.googlesource.com/c/platform/bionic/+/1863333

**Comment by DanAlbert** [comment] 2022-10-18 00:02
Closing since Android now has this API, and the libunwindstack source is usable by anyone that needs to backport that. There aren't any real plans (we'd love to, but realistically it's not getting prioritized) to provide a trivially imported version of the library for apps (an AAR). If we're underestimating the importance of providing an AAR for this, please let us know :)

**Closed by DanAlbert** 2022-10-18 00:02 UTC
