### ISSUE TITLE
Compiler crashes for clang version 7.0.2 when compling a template header

### ISSUE THREAD

**Issue by qtiuto** [android/ndk#848] opened 2018-11-15 15:00 UTC
#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 18.1.5063045 
* Build system: ndk-build
* Host OS: Windows
* Compiler: Clang 
* ABI:all
* STL:c++_static
* NDK API level:14
* Device API level:

A file like this can cause a compiler crash
```c++
#ifndef LUADROID_TLS_H
#define LUADROID_TLS_H

#include "pthread.h"

template <typename T,bool release=false>
class ThreadLocal{
    pthread_key_t key;

    typedef void(*ReleaseFunc)(void*);
    template <bool re>
    struct Release{
        static constexpr inline ReleaseFunc get(){
            return nullptr;
        }
    };

    template <>
    struct Release<true>{
        static void deconstruct(void* p){
            delete (T*)p;
        }
        static inline ReleaseFunc get(){
            return deconstruct;
        }
    };
public:
    ThreadLocal() {
         pthread_key_create(&key, Release<release>::get());
    }

    void set(T* newValue){
        T* old=(T*)pthread_getspecific(key);
        if(old!= nullptr){
            delete old;
        }
        pthread_setspecific(key,newValue);
    }

    T *safe_get(){
        T* ret=(T*)pthread_getspecific(key);
        if(ret== nullptr){
            ret=new T();
            pthread_setspecific(key,ret);
        }
        return ret;
    }

    T *get(){
        return (T*)pthread_getspecific(key);
    }

    ~ThreadLocal(){
        pthread_key_delete(key);
    }

    ThreadLocal& operator=(T* other){
        set(other);
        return *this;
    }
    friend bool operator==(T* p1,ThreadLocal& p2){
        return p2.get()==p1;
    }
    friend bool operator!=(T* p1,ThreadLocal& p2){
        return p2.get()!=p1;
    }
    friend bool operator==(ThreadLocal& p2,T* p1){
        return p2.get()==p1;
    }
    friend bool operator!=(ThreadLocal& p2,T* p1){
        return p2.get()!=p1;
    }
    T& operator*(){
        return *get();
    }

    operator T*(){
        return get();
    }

    T* operator->(){
        return get();
    }


};
#endif //LUADROID_TLS_H
```

However, this version works fine.

```c++
#ifndef LUADROID_TLS_H
#define LUADROID_TLS_H

#include "pthread.h"
template <typename T,bool release=false>
class ThreadLocal{
    pthread_key_t key;

    typedef void(*ReleaseFunc)(void*);
    template <typename Tp,bool re>
    struct Release{
        static constexpr inline ReleaseFunc get(){
            return nullptr;
        }
    };

    template <typename Tp>
    struct Release<Tp,true>{
        static void deconstruct(void* p){
            delete (Tp*)p;
        }
        static inline ReleaseFunc get(){
            return deconstruct;
        }
    };
public:
    ThreadLocal() {
         pthread_key_create(&key, Release<T,release>::get());
    }

    void set(T* newValue){
        T* old=(T*)pthread_getspecific(key);
        if(old!= nullptr){
            delete old;
        }
        pthread_setspecific(key,newValue);
    }

    T *safe_get(){
        T* ret=(T*)pthread_getspecific(key);
        if(ret== nullptr){
            ret=new T();
            pthread_setspecific(key,ret);
        }
        return ret;
    }

    T *get(){
        return (T*)pthread_getspecific(key);
    }

    ~ThreadLocal(){
        pthread_key_delete(key);
    }

    ThreadLocal& operator=(T* other){
        set(other);
        return *this;
    }
    friend bool operator==(T* p1,ThreadLocal& p2){
        return p2.get()==p1;
    }
    friend bool operator!=(T* p1,ThreadLocal& p2){
        return p2.get()!=p1;
    }
    friend bool operator==(ThreadLocal& p2,T* p1){
        return p2.get()==p1;
    }
    friend bool operator!=(ThreadLocal& p2,T* p1){
        return p2.get()!=p1;
    }
    T& operator*(){
        return *get();
    }

    operator T*(){
        return get();
    }

    T* operator->(){
        return get();
    }
};
#endif //LUADROID_TLS_H

```
If you don't want to solve it, ignore it, cause I still have a correct version to work.

[clang++.exe-7289c0.zip](https://github.com/android-ndk/ndk/files/2585801/clang%2B%2B.exe-7289c0.zip)

**Comment by stephenhines** [comment] 2018-11-27 08:17
This doesn't reproduce given the instructions above, although I haven't tried it on Windows. Can you provide preprocessed source that fails and/or the actual emitted crash message? Using compiler explorer, this doesn't reproduce with Clang 7.0.0, nor any of the other available versions (including TOT). I also tried using the available Clangs from within Android, and similarly could not reproduce a failure.

**Comment by stephenhines** [comment] 2018-11-27 08:17
https://godbolt.org/z/GNfsrJ is an example you can mess around with.

**Comment by stephenhines** [comment] 2018-11-28 05:33
Thanks, Ryan. I stupidly only tried with the default `ThreadLocal<int>`, not thinking about it, and figured it would be better to get some more info.

**Comment by rprichard** [comment] 2018-11-28 05:34
No problem.

For posterity, here's a Godbolt link with my reduced test case: https://godbolt.org/z/k8aTST

**Comment by rprichard** [comment] 2021-10-29 20:56
The upstream bug (llvm.org/PR39817) doesn't reproduce anymore and was closed. My reduced test case on that bug stopped failing as of upstream Clang 9.0. The repro test case in this GitHub issue stopped failing as of NDK r21.

I think we can close this issue now, unless we want to find the Clang commit that fixed it.

**Closed by rprichard** 2021-10-29 20:56 UTC
Labels: clang
