### ISSUE TITLE
[BUG] C++17 STL <charconv> implementation missing floating point functions

### ISSUE THREAD

**Issue by Didgy74** [android/ndk#1574] opened 2021-08-29 11:44 UTC
#### Description

In NDK r23, trying to use any of the float-based functions from <charconv> will result in a compiler error. From looking in the file `Sdk\ndk\23.0.7599858\sources\cxx-stl\llvm-libc++\include\charconv`, it's clear that this file only contains implementation for the integral types,

To clarify more, from the [https://en.cppreference.com/w/cpp/utility/to_chars](https://en.cppreference.com/w/cpp/utility/to_chars) page, the current implementation only contains functions 1 and 2. From the [https://en.cppreference.com/w/cpp/utility/from_chars](https://en.cppreference.com/w/cpp/utility/from_chars) page, the current implementation only contains function 1.

Test case:

Include <charconv> and try to use any of the float based function:
```cpp
#include <charconv>

char str[10];
std::from_chars_result result = std::to_chars(&str[0], &str[10], 10.f); // Compiler error, no matching candidate found.
```

#### Environment Details

* NDK Version: 23.0.7599858

**Comment by DanAlbert** [comment] 2021-08-31 03:19
At a glance (not sure if I'm reading the enable-ifs correctly) it looks like this is still the case upstream, so this probably requires more than just a libc++ update.

**Comment by Zingam** [comment] 2022-09-10 11:45
https://en.cppreference.com/w/cpp/17

**Comment by DanAlbert** [comment] 2023-02-27 20:32
Duplicate of #1530

(these were added upstream a while back, we just need an update)

**Closed by DanAlbert** 2023-02-27 20:32 UTC
Labels: bug
