### ISSUE TITLE
[Bug]: Lambda segfaults in Clang

### ISSUE THREAD

**Issue by FireBurn** [android/ndk#2035] opened 2024-06-26 20:05 UTC
### Description

This bug has caused segfaults compiling Android projects using lambdas and affects the whole 18.1 series

I've got a version of the patch that applies cleanly to 18.1.8 https://github.com/FireBurn/PortageStuff/blob/master/patches/sys-devel/clang/0001-Tweak-tryCaptureVariable-for-unevaluated-lambdas-932.patch

### Upstream bug

https://github.com/llvm/llvm-project/issues/67260

### Commit to cherry-pick

https://github.com/vedantparanjape-amd/llvm-project/commit/251b29d7a40a247c913e999ade839748ae350a6f

### Affected versions

r27

### Host OS

Linux

### Host OS version

Gentoo

### Affected ABIs

arm64-v8a, x86_64

**Comment by DanAlbert** [comment] 2024-06-26 20:43
Thanks. We'll check the test case in the PR to see if this is a regression from r26. If not, it'll be fixed in r28 for sure, but it'd probably wait for r27b (we'll see though, we're already respinning for a regression fix, so might be able to pick this up too).

**Comment by pirama-arumuga-nainar** [comment] 2024-06-26 20:47
https://github.com/llvm/llvm-project/issues/67260 says this regressed due to an LLVM change in september so it is likely a regression in r27.  Will try to cherry-pick the fix.

**Comment by DanAlbert** [comment] 2024-06-26 20:55
Ah, thanks. I'd skimmed it but missed that bit.

**Comment by appujee** [comment] 2024-06-27 20:52
Picked in: https://android-review.googlesource.com/c/toolchain/llvm_android/+/3148958

**Comment by FireBurn** [comment] 2024-06-27 21:17
Thanks

**Comment by pirama-arumuga-nainar** [comment] 2024-06-27 21:21
> Picked in: https://android-review.googlesource.com/c/toolchain/llvm_android/+/3148958

That's a different cherry-pick.  The fix for this bug hasn't been cherry-picked yet.

**Comment by FireBurn** [comment] 2024-07-03 12:55
Is there anything I need to do with this?

**Comment by pirama-arumuga-nainar** [comment] 2024-07-03 16:25
> > Picked in: https://android-review.googlesource.com/c/toolchain/llvm_android/+/3148958
> 
> That's a different cherry-pick. The fix for this bug hasn't been cherry-picked yet.

Actually @appujee is correct.  The same fix is cherry-picked as part of #2023.   The fix will be included as part of r27 to be released later this month.

**Comment by DanAlbert** [comment] 2024-07-09 22:54
> Is there anything I need to do with this?

No, you're just waiting for the release to be ready. Can subscribe to https://groups.google.com/g/android-ndk-announce or the releases on this github project if you want to be notified.

**Comment by DanAlbert** [comment] 2024-07-10 22:52
Closing as a duplicate of https://github.com/android/ndk/issues/2023. I don't think it's strictly a dup, but the same upstream change fixed several related bugs (in any case, the fix has been cherry-picked and will be in r27 Very Soon TM).

**Closed by DanAlbert** 2024-07-10 22:52 UTC
Labels: bug

**Comment by FireBurn** [comment] 2024-07-17 16:11
Thanks that it all fixed
