### ISSUE TITLE
[BUG] LLVM_AR is not set to a proper value on macOS if -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=OFF is given

### ISSUE THREAD

**Issue by leleliu008** [android/ndk#1887] opened 2023-05-17 07:26 UTC
### Description

**step1**: create the CMakeLists.txt

```cmake
cmake_minimum_required(VERSION 3.0)

project(android-cmake-test-case C)

message("CMAKE_AR = ${CMAKE_AR}")
```

**step2**: run following command on macOS

```bash
cmake \
    -S . \
    -B build.d \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
    -DANDROID_TOOLCHAIN=clang \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_PLATFORM=21 \
    -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=OFF
```

you will see `CMAKE_AR = /usr/bin/ar`

if you run above on GNU/Linux, you will see `CMAKE_AR = /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar`

here is a full test case using github actions: https://github.com/leleliu008/android-cmake-test-case/actions/runs/5000476974/

### Affected versions

r25

### Host OS

macOS

### Host OS version

macOS-11 and macOS-12

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Build system

CMake

### minSdkVersion

nothing to do with this

### Device API level

nothing to do with this

**Comment by DanAlbert** [comment] 2023-05-17 19:11
We'll look at this for r26 if we have time, but as you can probably tell from the defaults, I can't really recommend using that flag. The legacy toolchain is still the default because the other option has a lot of problems.

**Comment by DanAlbert** [comment] 2023-05-17 21:55
You should just remove the flag and let the defaults happen.

**Comment by DanAlbert** [comment] 2023-06-06 19:25
Duplicate of #1698

**Closed by DanAlbert** 2023-06-06 19:25 UTC
Labels: bug
