### ISSUE TITLE
[BUG] NDK 21.3 to 22.0 leads to huge size increase

### ISSUE THREAD

**Issue by Tolriq** [android/ndk#1402] opened 2020-12-15 09:58 UTC
#### Description

Switching from NDK 21.3 to 22.0 generate much much bigger .so

ARMV8 ; Bin 223448 -> 310056 bytes
ARMv7: Bin 120552 -> 173688 bytes
X86: Bin 223004 -> 302312 bytes
X86_64: Bin 248312 -> 324112 bytes

#### Environment Details

```
LOCAL_CPPFLAGS += -ffunction-sections -fdata-sections -fvisibility=hidden -fvisibility-inlines-hidden -Os -D_REENTRANT -fomit-frame-pointer -fno-exceptions
LOCAL_CFLAGS   += -ffunction-sections -fdata-sections -fvisibility=hidden -fvisibility-inlines-hidden -Os -D_REENTRANT -fomit-frame-pointer -fno-exceptions
LOCAL_LDFLAGS  += -Wl,--gc-sections, -Bsymbolic
```

* NDK Version: 21.3.6528147 and 22.0.7026061
* Build system: ndk-build
* Host OS: Windows
* ABI: armeabi-v7a arm64-v8a x86 x86_64
* NDK API level: 21

**Comment by rprichard** [comment] 2020-12-15 23:28
I wonder if the switch to LLD is involved. Can you trying linking with `-fuse-ld=bfd` or `-fuse-ld=gold` and see if that affects the size? If it does affect things, then it would be interesting to see the before-and-after output of:
```
$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf -lS $ELF_FILE
```
(Prior to r22, the default NDK linker was ld.bfd for arm64 and ld.gold for every other architecture. r22 switched the default to ld.lld.)

**Comment by Tolriq** [comment] 2020-12-16 08:07
@rprichard It does not seems to be impacted by the linker

```
ARMV8  BFD : Bin 223448 -> 313568 bytes
ARMV8  GOLD : Bin 223448 -> 313840 bytes
ARMV8  LLD : Bin 223448 -> 310056 bytes
```

The readelf results :
- NDK 21.3
```
There are 26 section headers, starting at offset 0x36258:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .note.gnu.build-id NOTE           0000000000000200 000200 000024 00   A  0   0  4
  [ 2] .hash             HASH            0000000000000228 000228 0009c0 04   A  4   0  8
  [ 3] .gnu.hash         GNU_HASH        0000000000000be8 000be8 000a04 00   A  4   0  8
  [ 4] .dynsym           DYNSYM          00000000000015f0 0015f0 0021a8 18   A  5   3  8
  [ 5] .dynstr           STRTAB          0000000000003798 003798 001739 00   A  0   0  1
  [ 6] .gnu.version      VERSYM          0000000000004ed2 004ed2 0002ce 02   A  4   0  2
  [ 7] .gnu.version_r    VERNEED         00000000000051a0 0051a0 000040 00   A  5   2  8
  [ 8] .rela.dyn         RELA            00000000000051e0 0051e0 007728 18   A  4   0  8
  [ 9] .rela.plt         RELA            000000000000c908 00c908 0006c0 18  AI  4  21  8
  [10] .plt              PROGBITS        000000000000cfd0 00cfd0 0004a0 10  AX  0   0 16
  [11] .text             PROGBITS        000000000000d470 00d470 01d1ac 00  AX  0   0  4
  [12] .rodata           PROGBITS        000000000002a620 02a620 003519 00   A  0   0 16
  [13] .eh_frame_hdr     PROGBITS        000000000002db3c 02db3c 000ed4 00   A  0   0  4
  [14] .eh_frame         PROGBITS        000000000002ea10 02ea10 004118 00   A  0   0  8
  [15] .gcc_except_table PROGBITS        0000000000032b28 032b28 00039c 00   A  0   0  4
  [16] .note.android.ident NOTE          0000000000032ec4 032ec4 000098 00   A  0   0  4
  [17] .init_array       INIT_ARRAY      0000000000033fa8 032fa8 000008 08  WA  0   0  8
  [18] .fini_array       FINI_ARRAY      0000000000033fb0 032fb0 000010 08  WA  0   0  8
  [19] .data.rel.ro      PROGBITS        0000000000033fc0 032fc0 002b08 00  WA  0   0  8
  [20] .dynamic          DYNAMIC         0000000000036ac8 035ac8 000220 10  WA  5   0  8
  [21] .got              PROGBITS        0000000000036ce8 035ce8 000318 08  WA  0   0  8
  [22] .data             PROGBITS        0000000000037000 036000 000080 00  WA  0   0  8
  [23] .bss              NOBITS          0000000000037080 036080 000510 00  WA  0   0 16
  [24] .comment          PROGBITS        0000000000000000 036080 0000dc 01  MS  0   0  1
  [25] .shstrtab         STRTAB          0000000000000000 03615c 0000fb 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), l (large)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)

Elf file type is DYN (Shared object file)
Entry point 0xd470
There are 8 program headers, starting at offset 64

Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  LOAD           0x000000 0x0000000000000000 0x0000000000000000 0x032f5c 0x032f5c R E 0x1000
  LOAD           0x032fa8 0x0000000000033fa8 0x0000000000033fa8 0x0030d8 0x0035e8 RW  0x1000
  DYNAMIC        0x035ac8 0x0000000000036ac8 0x0000000000036ac8 0x000220 0x000220 RW  0x8
  NOTE           0x000200 0x0000000000000200 0x0000000000000200 0x000024 0x000024 R   0x4
  NOTE           0x032ec4 0x0000000000032ec4 0x0000000000032ec4 0x000098 0x000098 R   0x4
  GNU_EH_FRAME   0x02db3c 0x000000000002db3c 0x000000000002db3c 0x000ed4 0x000ed4 R   0x4
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10
  GNU_RELRO      0x032fa8 0x0000000000033fa8 0x0000000000033fa8 0x003058 0x003058 R   0x1

 Section to Segment mapping:
  Segment Sections...
   00     .note.gnu.build-id .hash .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .plt .text .rodata .eh_frame_hdr .eh_frame .gcc_except_table .note.android.ident
   01     .init_array .fini_array .data.rel.ro .dynamic .got .data .bss
   02     .dynamic
   03     .note.gnu.build-id
   04     .note.android.ident
   05     .eh_frame_hdr
   06
   07     .init_array .fini_array .data.rel.ro .dynamic .got
   None   .comment .shstrtab
```

- NDK 22
```
There are 27 section headers, starting at offset 0x4b430:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .note.android.ident NOTE          0000000000000238 000238 000098 00   A  0   0  4
  [ 2] .note.gnu.build-id NOTE           00000000000002d0 0002d0 000024 00   A  0   0  4
  [ 3] .dynsym           DYNSYM          00000000000002f8 0002f8 0036f0 18   A  8   1  8
  [ 4] .gnu.version      VERSYM          00000000000039e8 0039e8 000494 02   A  3   0  2
  [ 5] .gnu.version_r    VERNEED         0000000000003e7c 003e7c 000040 00   A  8   2  4
  [ 6] .gnu.hash         GNU_HASH        0000000000003ec0 003ec0 000e24 00   A  3   0  8
  [ 7] .hash             HASH            0000000000004ce4 004ce4 001258 04   A  3   0  4
  [ 8] .dynstr           STRTAB          0000000000005f3c 005f3c 004844 00   A  0   0  1
  [ 9] .rela.dyn         RELA            000000000000a780 00a780 0086b8 18   A  3   0  8
  [10] .rela.plt         RELA            0000000000012e38 012e38 000ae0 18   A  3  22  8
  [11] .rodata           PROGBITS        0000000000013920 013920 003899 00 AMS  0   0 16
  [12] .gcc_except_table PROGBITS        00000000000171bc 0171bc 000be4 00   A  0   0  4
  [13] .eh_frame_hdr     PROGBITS        0000000000017da0 017da0 001474 00   A  0   0  4
  [14] .eh_frame         PROGBITS        0000000000019218 019218 005b8c 00   A  0   0  8
  [15] .text             PROGBITS        000000000001eda4 01eda4 028548 00  AX  0   0  4
  [16] .plt              PROGBITS        00000000000472f0 0472f0 000760 00  AX  0   0 16
  [17] .data.rel.ro      PROGBITS        0000000000048a50 047a50 003058 00  WA  0   0  8
  [18] .fini_array       FINI_ARRAY      000000000004baa8 04aaa8 000010 00  WA  0   0  8
  [19] .init_array       INIT_ARRAY      000000000004bab8 04aab8 000008 00  WA  0   0  8
  [20] .dynamic          DYNAMIC         000000000004bac0 04aac0 0001e0 10  WA  8   0  8
  [21] .got              PROGBITS        000000000004bca0 04aca0 000118 00  WA  0   0  8
  [22] .got.plt          PROGBITS        000000000004bdb8 04adb8 0003b8 00  WA  0   0  8
  [23] .data             PROGBITS        000000000004d170 04b170 0000a0 00  WA  0   0  8
  [24] .bss              NOBITS          000000000004d210 04b210 000550 00  WA  0   0 16
  [25] .comment          PROGBITS        0000000000000000 04b210 00011b 01  MS  0   0  1
  [26] .shstrtab         STRTAB          0000000000000000 04b32b 000104 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), l (large)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)

Elf file type is DYN (Shared object file)
Entry point 0x1eda4
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset   VirtAddr           PhysAddr           FileSiz  MemSiz   Flg Align
  PHDR           0x000040 0x0000000000000040 0x0000000000000040 0x0001f8 0x0001f8 R   0x8
  LOAD           0x000000 0x0000000000000000 0x0000000000000000 0x047a50 0x047a50 R E 0x1000
  LOAD           0x047a50 0x0000000000048a50 0x0000000000048a50 0x003720 0x003720 RW  0x1000
  LOAD           0x04b170 0x000000000004d170 0x000000000004d170 0x0000a0 0x0005f0 RW  0x1000
  DYNAMIC        0x04aac0 0x000000000004bac0 0x000000000004bac0 0x0001e0 0x0001e0 RW  0x8
  GNU_RELRO      0x047a50 0x0000000000048a50 0x0000000000048a50 0x003720 0x0045b0 R   0x1
  GNU_EH_FRAME   0x017da0 0x0000000000017da0 0x0000000000017da0 0x001474 0x001474 R   0x4
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x0
  NOTE           0x000238 0x0000000000000238 0x0000000000000238 0x0000bc 0x0000bc R   0x4

 Section to Segment mapping:
  Segment Sections...
   00
   01     .note.android.ident .note.gnu.build-id .dynsym .gnu.version .gnu.version_r .gnu.hash .hash .dynstr .rela.dyn .rela.plt .rodata .gcc_except_table .eh_frame_hdr .eh_frame .text .plt
   02     .data.rel.ro .fini_array .init_array .dynamic .got .got.plt
   03     .data .bss
   04     .dynamic
   05     .data.rel.ro .fini_array .init_array .dynamic .got .got.plt
   06     .eh_frame_hdr
   07
   08     .note.android.ident .note.gnu.build-id
   None   .comment .shstrtab
```

**Comment by stephenhines** [comment] 2020-12-16 10:12
So according to that description, there's already a 45KB increase in text segment alone (from 116KB -> 161KB). Are you using the same compiler flags? Can you share the files (or at least a reduced version of one of the files) that shows a large increase in size? I don't think we've seen a case where anything jumped nearly ~50% in size, so it is suspicious.

**Comment by Tolriq** [comment] 2020-12-16 10:18
I change nothing but the path to NDK in my build script:
```SET NDK_HOME=D:\Android\sdk\ndk\21.3.6528147```
to
```SET NDK_HOME=D:\Android\sdk\ndk\22.0.7026061```

I can send the file privately (There's only one as I have not yet tried to build ExoPlayer ffmepg with it seeing that)
You can contact me at my name at gmail.com.

**Comment by Tolriq** [comment] 2021-01-13 09:41
Small bump :)

**Comment by DanAlbert** [comment] 2021-01-26 21:06
@Tolriq I'm not the one investigating this, but at a guess the toolchain folks can't do anything without a repro case. Like @stephenhines said we haven't seen this anywhere else.

**Comment by stephenhines** [comment] 2021-01-26 21:11
He did send me a repro case, but I just don't have the time to dig deeper right now (and unfortunately probably not soon either). Q1 is very time-constrained.

**Comment by DanAlbert** [comment] 2021-01-26 22:30
Okay, moving to r22c then, since we're trying to ship r22b soon.

**Comment by enh-google** [comment] 2021-06-01 23:36
https://issuetracker.google.com/189354198 was another report of this, but also without a repro case.

**Comment by Tolriq** [comment] 2021-06-02 06:12
Again this one have a small complete repro sent by mail and received by @stephenhines.

**Comment by Tolriq** [comment] 2021-08-17 13:26
Bin 231640 -> 321840 bytes

Still the case with 23.0.7599858

Any info on timing on this? Seems 23 is the new LTS and linked things may migrate to it.

**Comment by stephenhines** [comment] 2021-08-17 17:43
I created an internal issue so that we can chase this a bit easier on our side (http://b/196979899). Hopefully this will speed up our ability to understand why this code size has increased so much.

**Comment by Tolriq** [comment] 2021-12-14 17:13
Bin 227544 -> 324680 bytes

Still the case with 24.0 RC2 anyway to have some feedback on this? It's a deal breaker to update.

**Comment by Tolriq** [comment] 2022-02-25 06:11
Bin 227544 -> 325624 bytes

Still the case with 25 RC1, what is needed to have some feedback on this?

**Comment by pirama-arumuga-nainar** [comment] 2022-02-25 06:34
Just pasting some comments from the internal bug for posterity:

srhines@:
```
There's a lot more libc++ symbols in r22, as compared to r21.3. Dan, was there a large libc++ upgrade around that time? Did we change default flags somehow that would cause this to pull in more bloat directly from libc++?
```

danalbert@:
```
r22 was the last time we were able to update libc++. If the change really is just an increase in the number of libc++ symbols present I doubt there's anything to actually do here. The only changes I found that could account for a change in the number of symbols exported were all things that should reduce the number of exports (better extern template use, which moves the specializations into libc++.so).

https://github.com/llvm/llvm-project/commit/288a1436392f1fbee2e647cb057086fe700f9c7e could maybe account for it, but I don't think that actually reduced the exported symbols, just froze them so nothing new was accidentally exported. At least one of the symbols in your list is listed in the export list (I only spot checked one).

Failing those options, it seems pretty likely to be just a source change that caused a bunch of other code to be pulled in because the stdlib sucks at "pay for what you use".

I don't have anything concrete to back up any of that though.
```

**Comment by pirama-arumuga-nainar** [comment] 2022-02-25 06:46
https://github.com/android/ndk/issues/1408 is another issue that `std::string` functions are not inlined.

**Comment by Tolriq** [comment] 2022-02-25 06:55
Thank for the update even if I fear there won't be solutions :( 

On my main app size matters a lot as a lot of users on low end devices dedicated to it.

- Is there any risks in the near future that changes to Android core will require an update of NDK? (That code part won't require updates to support new Android SDK entry points).
- Is there any risks to have 1 .so compiled with an old NDK and another with a more recent one ?

**Comment by DanAlbert** [comment] 2022-02-25 23:36
> Is there any risks in the near future that changes to Android core will require an update of NDK? (That code part won't require updates to support new Android SDK entry points).

None that I'm aware of, not that I'd necessarily be able to say if there were. That'd almost certainly be a wider announcement sent from above my pay grade :)

The most obvious thing that _requires_ you to upgrade things in apps are `targetSdkVersion` changes, but that isn't affected by your NDK version.

> Is there any risks to have 1 .so compiled with an old NDK and another with a more recent one ?

We would consider it a bug if there was an unexpected break in compatibility, but those bugs can't always be fixed unless they are caught _before_ the break ships (reverting breaking changes doesn't remove the break, it introduces a second break). We do our best but it's impossible to guarantee.

**Comment by Hsilgos** [comment] 2022-03-12 18:44
> Bin 227544 -> 325624 bytes
> 
> Still the case with 25 RC1, what is needed to have some feedback on this?

In my case size significantly increased only of armeabi-v7a after migrating to Android Gradle Plugin 7.1.0 (NDK before and after was 23.0)

**Comment by DanAlbert** [comment] 2022-10-18 00:05
@jfgoog, you'd taken the internal bug. Were you able to find anything?

Do we know if the problem still exists in r25?

**Comment by Tolriq** [comment] 2022-10-18 07:13
With 25.1.8937393

v8a : Bin 227544 -> 320232 bytes
v7a: Bin 120552 -> 183528 bytes
x86: Bin 223004 -> 299348 bytes
x86_64: Bin 248312 -> 326680 bytes

**Comment by jfgoog** [comment] 2022-10-18 13:48
I was looking at the size of the NDK itself, not the size of the code it generates.

Tolriq, are you passing -Oz to both versions, as @Hsilgos suggested?

**Comment by Tolriq** [comment] 2022-10-18 15:09
There's 2 years of history and a full repro sent by mail. I'm compiling with Os that gives better result for me than Oz

-> 25.1.8937393

v8a : Bin 227544 -> 320232 bytes (-Os) | 321752 bytes (-Oz)
v7a: Bin 120552 -> 183528 bytes (-Os) | 183156 bytes (-Oz)
x86: Bin 223004 -> 299348 bytes (-Os) | 301596 bytes (-Oz)
x86_64: Bin 248312 -> 326680 bytes (-Os) | 327896 bytes (-Oz)

**Comment by jfgoog** [comment] 2022-10-18 16:52
I did a bit more investigation. One thing I noticed is that while the .so file is larger in NDK 25, the object files are usually *smaller*. The versions of libc++abi.a and libc++_static.a included with NDK 25 are smaller as well.

**Comment by jfgoog** [comment] 2022-10-18 19:20
When I compile with -g and look at it with `bloaty -d compileunits`, it looks like NDK 25 is dragging in a bunch of stuff from std::string:

```
21
    FILE SIZE        VM SIZE
 --------------  --------------
  59.7%   935Ki  62.1%   147Ki    /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_demangle.cpp
  14.1%   221Ki   6.0%  14.3Ki    /usr/local/google/home/jamesfarrell/bugs/196979899/jni/libyatse.cpp
   3.9%  61.0Ki   6.1%  14.5Ki    /usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-dw2.c
   3.7%  58.4Ki   3.0%  7.21Ki    /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/private_typeinfo.cpp
   2.8%  43.8Ki   3.5%  8.27Ki    /usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgcc/unwind-dw2-fde-dip.c
   2.4%  37.6Ki   3.1%  7.48Ki    /usr/local/google/home/jamesfarrell/bugs/196979899/jni/unzip.c
   1.9%  30.0Ki   3.2%  7.72Ki    /usr/local/google/home/jamesfarrell/bugs/196979899/jni/aes.cpp
   1.9%  29.5Ki   1.5%  3.47Ki    /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_exception.cpp
   1.8%  28.3Ki   1.8%  4.28Ki    /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_personality.cpp
   1.4%  22.2Ki   5.5%  13.0Ki    [30 Others]
   1.0%  14.9Ki   0.9%  2.25Ki    /buildbot/src/android/ndk-release-r21/external/libcxx/src/new.cpp
   0.9%  13.6Ki   0.0%       0    [section .debug_loc]
   0.8%  12.6Ki   0.7%  1.59Ki    /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/fallback_malloc.cpp
   0.6%  9.68Ki   0.4%     912    /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_default_handlers.cpp
   0.6%  9.39Ki   0.4%     875    /usr/local/google/home/jamesfarrell/bugs/196979899/jni/ioapi.c
   0.6%  9.35Ki   0.4%     973    /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_handlers.cpp
   0.5%  8.01Ki   0.3%     807    /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_exception_storage.cpp
   0.5%  7.73Ki   0.4%  1.05Ki    /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/stdlib_typeinfo.cpp
   0.5%  7.12Ki   0.6%  1.40Ki    /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/stdlib_exception.cpp
   0.2%  3.69Ki   0.0%       0    [Unmapped]
   0.2%  3.35Ki   0.0%       0    [section .symtab]
 100.0%  1.53Mi 100.0%   237Ki    TOTAL

25
     FILE SIZE        VM SIZE
 --------------  --------------
  44.1%   842Ki  49.4%   157Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/cxa_demangle.cpp
  23.7%   453Ki  17.0%  54.2Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/src/string.cpp
  10.0%   191Ki   3.7%  11.8Ki    /usr/local/google/home/jamesfarrell/bugs/196979899/jni/libyatse.cpp
   3.4%  65.2Ki   9.5%  30.1Ki    [33 Others]
   3.0%  56.7Ki   2.3%  7.21Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/private_typeinfo.cpp
   2.2%  42.0Ki   2.0%  6.47Ki    /usr/local/google/home/jamesfarrell/bugs/196979899/jni/unzip.c
   1.7%  31.6Ki   2.3%  7.47Ki    /usr/local/google/home/jamesfarrell/bugs/196979899/jni/aes.cpp
   1.5%  29.5Ki   1.4%  4.49Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/cxa_personality.cpp
   1.5%  28.3Ki   1.1%  3.37Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/cxa_exception.cpp
   1.2%  23.1Ki   0.7%  2.18Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/src/stdexcept.cpp
   0.9%  18.1Ki   0.8%  2.60Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/stdlib_stdexcept.cpp
   0.9%  17.6Ki   0.5%  1.71Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/src/charconv.cpp
   0.9%  16.6Ki   0.8%  2.53Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/src/new.cpp
   0.8%  16.2Ki   5.1%  16.2Ki    [section .text]
   0.8%  16.0Ki   0.0%       0    [section .debug_loc]
   0.6%  11.4Ki   0.3%    1016    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/cxa_default_handlers.cpp
   0.6%  11.0Ki   0.3%  1.02Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/cxa_handlers.cpp
   0.6%  11.0Ki   1.3%  4.19Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/stdlib_typeinfo.cpp
   0.6%  10.8Ki   1.1%  3.46Ki    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/fallback_malloc.cpp
   0.5%  9.24Ki   0.2%     735    /usr/local/google/home/jamesfarrell/bugs/196979899/jni/ioapi.c
   0.4%  8.47Ki   0.1%     283    /buildbot/src/android/ndk-r25-release/toolchain/llvm-project/libcxx/src/vector.cpp
 100.0%  1.87Mi 100.0%   318Ki    TOTAL
```

**Comment by jfgoog** [comment] 2022-10-18 19:56
After looking through the source code, I'm actually surprised that NDK 21 manages to *not* include a bunch of stuff from std::string.

**Comment by jfgoog** [comment] 2022-10-18 20:25
I tend to agree with Pirama that this is the same issue as https://github.com/android/ndk/issues/1408

**Comment by DanAlbert** [comment] 2022-10-18 21:14
@Tolriq Thanks for confirming. I suspected the answer was yes, but wanted to be sure.

FWIW, yes, we got a repro case, but with instructions to not share it widely. If we can't pass the bug report to upstream LLVM it's going to go _very_ slowly, because they're the ones that do almost all the work.

Duplicate of #1408 

(if that's not the case we can reopen, but it seems likely)

**Closed by DanAlbert** 2022-10-18 21:14 UTC
Labels: bug

**Comment by Tolriq** [comment] 2022-10-19 06:42
It's not to be shared **publicly**. Even if the version you have does not contains some of the parts, it includes some security measures for anti tampering that are to this day still uncracked, preventing distribution of modified APK.

If the code can stay private within trusted people then it's OK to share to have large issue like this fixed.

About "very slowly" it's already been 2 years ;)

**Comment by DanAlbert** [comment] 2022-10-19 21:37
That's exactly it. We can't share it publicly with LLVM.

**Comment by ankurvdev** [comment] 2023-02-14 04:45
+1

**Comment by DanAlbert** [comment] 2023-02-15 00:21
@ankurvdev a few posts above yours is the link to the bug that this is a dup of. File a new bug (with a repro case, or we can't help) if the duplicate bug does not describe the issue you're seeing.
