### ISSUE TITLE
[BUG] uses VFP register arguments, output does not

### ISSUE THREAD

**Issue by Laganer** [android/ndk#1326] opened 2020-07-29 07:19 UTC
LOCAL_PATH := $(call my-dir)
this is Android.mk file! error is:uses VFP register arguments, output does not
include $(CLEAR_VARS)
LOCAL_MODULE :=libobjectbox
LOCAL_SRC_FILES := $(LOCAL_PATH)/libs/$(TARGET_ARCH_ABI)/libobjectbox.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := blurLap
LOCAL_SRC_FILES := native-lib.cpp\
				   lapls.cpp
				   #include/flatcc-src/builder.c
				   #include/flatcc-src/emitter.c
				   #include/flatcc-src/refmap.c

LOCAL_C_INCLUDES += $(LOCAL_PATH)/
LOCAL_C_INCLUDES += $(LOCAL_PATH)/
LOCAL_C_INCLUDES += $(LOCAL_PATH)/include/
LOCAL_C_INCLUDES += $(LOCAL_PATH)/include/flatcc/

LOCAL_LDLIBS := -lz
LOCAL_LDLIBS += -L$(SYSROOT)/usr/lib

LOCAL_ARM_NEON := true
LOCAL_SHARED_LIBRARIES += libobjectbox

LOCAL_CFLAGS +=  -O3 -mfpu=vfp   -D_NDK_MATH_NO_SOFTFP=1 -march=armv7-a   -mfloat-abi=softfp

include $(BUILD_SHARED_LIBRARY)

**Comment by stephenhines** [comment] 2020-07-29 07:45
This needs more info to be actionable. Please attach source files and clearly state what you expected that is different with the output. The bug title could mean any number of things, but it isn't obvious without seeing the input source files.

**Comment by Laganer** [comment] 2020-07-29 07:57
Thank you for reply .Does ndk support for  building libraries with (-mhard-float )or(-mfloat-abi=hard) ?

**Comment by DanAlbert** [comment] 2020-07-29 19:58
The short answer: the defaults are correct and you don't need to worry about it.

The long answer: the 32-bit Arm ABI for Android is softfp. This only affects the calling convention, not the instructions available to apps. Your apps use hard float math, but can't use the floating point registers for passing arguments to functions. Since the system ABI is softfp, you cannot use `-mfloat-abi=hard` without breaking that interface. Any other libraries you use are also going to be softfp, so you'd be breaking your interface to them as well. If there are functions in your own code (aside from the JNI interface) that would benefit from the hard float calling convention you can annotate them individually with `__attribute__((pcs("aapcs-vfp")))` (https://gcc.gnu.org/onlinedocs/gcc-6.1.0/gcc/ARM-Function-Attributes.html#ARM-Function-Attributes), but you should definitely be using a profiler to guide that.

But I'm honestly not sure if that addresses the bug you filed, because it's not clear what the problem is. What is the actual error message you saw and where did it come from? What version of the NDK are you using? We need the information that was in the bug template.

**Comment by DanAlbert** [comment] 2020-12-17 00:06
Closing for lack of information. We'll reopen if we get the information we need to proceed.

**Closed by DanAlbert** 2020-12-17 00:06 UTC
Labels: bug, needs-info
