### ISSUE TITLE
PGO on Android

### ISSUE THREAD

**Issue by agpfrick** [android/ndk#881] opened 2019-01-03 10:55 UTC
Hello.
Does NDK support PGO on Android apps? Because I've added -fprofile-generate to my compile and linking flags and when the app started, it crashes just like the error described in [here](https://stackoverflow.com/questions/50043650/clang-profiling-with-instrumentation-on-android).

To make sure it links correctly, I remove the flag in the linking step. At this time it would have linking error of unresolved reference. And then I linked the libs manually. The link time error went away but unsatisfied link error in runtime still persists.

I use NDK 17b.

Thank you.

**Comment by agpfrick** [comment] 2019-01-04 03:51
Two more infos.
First, the symbol in question (`__start___llvm_prf_vnds`) is listed as d (defined) in my native lib.
Second, it doesn't crash with erros I mentioned in ARMv7 ABI.
Did I miss anything?

Ah also, what do I have to do to make the apps generate the .prof file? Do I have to call something before exiting? Because I already ran (the ARMv7 one, not the ARMv8 because the above error) it and no files are generated.

**Comment by pirama-arumuga-nainar** [comment] 2019-01-04 07:53
@agpfrick What ABI is this failing for?  Based on what I could find, these symbols should be generated/used for Linux and not Android (for e.g., http://lists.llvm.org/pipermail/llvm-dev/2017-July/115833.html).  Can you post the link command (including the linker invocation by passing '-v' to the Clang link command)?

> Ah also, what do I have to do to make the apps generate the .prof file?

Android apps don't go through the atexit() exit handlers, which is how the profile files get written.  You should call `__llvm_profile_write_file` to write the .profdata profile.

**Comment by pirama-arumuga-nainar** [comment] 2019-01-04 07:56
Also, https://android-review.googlesource.com/c/platform/system/extras/+/854812 is a small static library I wrote for triggering profile write with SIGUSR1/SIGUSR2 signals.

**Comment by pirama-arumuga-nainar** [comment] 2019-01-06 22:18
Can you create a smaller repro, if possible?  Just a way to produce a problematic .so should be fine.  The instrumentation-enabled .sos in the platform don't retain a dependency on this symbol.  I'll also investigate next week.

**Comment by agpfrick** [comment] 2019-01-07 02:01
> Can you create a smaller repro, if possible? Just a way to produce a problematic .so should be fine. The instrumentation-enabled .sos in the platform don't retain a dependency on this symbol. I'll also investigate next week.

I can repro this using the Activity+JNI template project in Android Studio. The `-fprofile-generate` flag is added to `CMakeLists.txt`. The project file is attached.

Thank you for your help.
[PGOTest.zip](https://github.com/android-ndk/ndk/files/2731159/PGOTest.zip)

**Comment by agpfrick** [comment] 2019-01-31 06:36
One of my colleagues reported that the error goes away if we use LTO.

**Comment by pirama-arumuga-nainar** [comment] 2019-10-18 18:12
I was able to reproduce this a while ago.  Oddly enough, this doesn't happen when PGO is enabled for the platform.

I'll prioritize it considering a second report of the issue at #1103.

**Comment by DanAlbert** [comment] 2020-04-14 00:29
@pirama-arumuga-nainar anything to do here?

**Comment by pirama-arumuga-nainar** [comment] 2020-04-15 16:59
Not sure if the issue still reproduces.  (Although I don't have any reason to believe this was fixed by unrelated changes).  Unfortunately I haven't had the cycles to look into this yet.

Tagging @stephenhines as FYI.

**Comment by pirama-arumuga-nainar** [comment] 2020-05-27 17:49
I'm apologise for the long delay in investigating this.  This seems to be a bug in ld.bfd which may have been fixed in https://sourceware.org/bugzilla/show_bug.cgi?id=24857.  To verify, run `readelf -aW` on the problematic shared library.  In my repro, the `sh_info` for `.dynsym` is 3 whereas there are at least 11 `LOCAL` symbols.

If I change the linker to `gold` or `lld`, the repro works fine.  Please reopen if your particular repro doesn't work with `gold` or `lld`.

PS: IIUC `lld` is going to be the default linker starting r22.

**Closed by pirama-arumuga-nainar** 2020-05-27 17:49 UTC

**Comment by Xiaotian0726** [comment] 2020-08-18 03:38
> > @agpfrick What ABI is this failing for? Based on what I could find, these symbols should be generated/used for Linux and not Android (for e.g., http://lists.llvm.org/pipermail/llvm-dev/2017-July/115833.html). Can you post the link command (including the linker invocation by passing '-v' to the Clang link command)?
> > > Ah also, what do I have to do to make the apps generate the .prof file?
> > 
> > 
> > Android apps don't go through the atexit() exit handlers, which is how the profile files get written. You should call `__llvm_profile_write_file` to write the .profdata profile.
> 
> The crash happens if I compile for armv8 ABI. This is the linking command as recorded by clang:
> 
> ```
> "C:/Development/Android/android-ndk-r17b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin\\ld" --sysroot=C:/Development/Android/android-ndk-r17b/platforms/android-21/arch-arm64 --eh-frame-hdr -m aarch64linux -shared -o "libSomething.so" -LC:/Development/Android/android-ndk-r17b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -LC:/Development/Android/android-ndk-r17b/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/6.0.2/lib/linux -LC:/Development/Android/android-ndk-r17b/platforms/android-21/arch-arm64/usr/lib -L./../../../../../../externals/SomeFrameworkConfig/build/generated/ARMV8/Release/StaticLibs "-LC:\\Development\\Android\\android-ndk-r17b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\6.0.2\\lib\\linux\\aarch64" -LC:/Development/Android/android-ndk-r17b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x -LC:/Development/Android/android-ndk-r17b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/../lib64 -LC:/Development/Android/android-ndk-r17b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib -LC:/Development/Android/android-ndk-r17b/platforms/android-21/arch-arm64/usr/lib -soname libSomething.so --build-id -z noexecstack --no-undefined -z relro -z now -rpath-link=C:/Development/Android/android-ndk-r17b/platforms/android-21/arch-arm64/usr/lib --whole-archive ./../../../../../../externals/SomeFrameworkConfig/build/generated/ARMV8/Release/StaticLibs/libAndroid_CPP.a ./../../../../../../externals/SomeFrameworkConfig/build/generated/ARMV8/Release/StaticLibs/libAndroid_C.a --no-whole-archive -lsomelib -lsomelib2 C:/Development/Android/android-ndk-r17b/platforms/android-21/arch-arm64/usr/lib/crtbegin_so.o C:/Development/Android/android-ndk-r17b/platforms/android-21/arch-arm64/usr/lib/crtend_so.o -llog -lc -lm -lz -ldl -lc++_static -lc++abi -lGLESv3 -landroid -lOpenSLES -lEGL -lgcc -u__llvm_profile_runtime "C:\\Development\\Android\\android-ndk-r17b\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\6.0.2\\lib\\linux\\libclang_rt.profile-aarch64-android.a"
> ```
> 
> *I have to edit some things because of privacy reasons.
> 
> Where is this `__llvm_profile_write_file` defined? Is it available in NDK distributions?
> Thank you for your help.
> 
> Ah okay I'm getting the hang of it. Looks like I also need to set the filename, otherwise it won't dump the profiling files.
> I still don't know why the ARMv8 build has unlinked error in runtime though.

I got the same problem...Could you please tell me how to set the filename? By adding some flags?
