### ISSUE TITLE
[Bug]: Compiler Crash

### ISSUE THREAD

**Issue by gerum100** [android/ndk#2045] opened 2024-07-16 16:50 UTC
### Description

[bug_report.zip](https://github.com/user-attachments/files/16253992/bug_report.zip)

The attachment contains the backtrace, the preprocessed source, and associated run script for the crash. Additionally it contains the dockerfile that was used to create the build environment.

### Affected versions

r26

### Host OS

Linux

### Host OS version

Ubuntu 24.04 Container

### Affected ABIs

armeabi-v7a

**Comment by pirama-arumuga-nainar** [comment] 2024-07-24 05:56
It doesn't reproduce in r27, which is the new LTS.  So closing this.

**Comment by DanAlbert** [comment] 2024-07-24 22:46
r26 is still supported. There aren't any more planned r26 releases (nothing qualifies for one yet), but let's reopen this in case that changes (I haven't looked closely enough at this one yet to see if it qualifies).

**Comment by DanAlbert** [comment] 2024-08-19 23:01
@gerum100 I don't suppose you know if this is a regression from r25? I tried to determine that myself, but the preprocessed source file isn't actually compatible with r25 anyway (I can't quite tell why, but I think the libc++ in r26 requires a newer version of clang for the template feature it uses?)

**Comment by gerum100** [comment] 2024-08-20 06:18
No, I have never tried compiling it with an older ndk.

**Comment by DanAlbert** [comment] 2024-08-20 19:33
Alright. It looks like it's probably not a regression, seeing as the code isn't even valid with r25's compiler, but it's hard to tell. This late in the support cycle, and after r27 is out, a new minor release of r26 is only going to happen for regressions, and probably only a widespread one at that. We'll see what we can do but I'm not optimistic that we'd even be able to make this release happen before the support window closes.

Are you able to upgrade to r27? @pirama-arumuga-nainar said above that it already has the fix.

**Comment by gerum100** [comment] 2024-08-23 13:24
I use a Qt-based build so I think I am stuck with that version for now (https://doc.qt.io/qt-6/android-getting-started.html#android-ndk), but I was able to modify the code so that it is working,

**Comment by DanAlbert** [comment] 2024-09-10 19:45
There weren't any other regressions filed for r26 in the meantime, and there's only one week left in the support window. It takes longer than that to get an updated Clang released, so closing.

**Closed by DanAlbert** 2024-09-10 19:45 UTC
Labels: bug
