### ISSUE TITLE
[Bug]: error: undefined reference to 'typeinfo for XXX'

### ISSUE THREAD

**Issue by bog-dan-ro** [android/ndk#1713] opened 2022-05-09 07:19 UTC
### Description

LLVM is not discarding the unused stuff when linking.
I created a super simple project [test_unused_typeinfo.tar.gz](https://github.com/android/ndk/files/8649502/test_unused_typeinfo.tar.gz) which works perfectly with gcc, but it fails with llvm.

### Affected versions

r21
r22
r23
r24

### Host OS

Linux

### Host OS version

Debian testing

### Affected ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

**Comment by DanAlbert** [comment] 2022-05-09 21:07
> Affected versions
> r21
> r22
> r23
> r24

r25 not listed because the bug has been fixed, or because it wasn't tested?

**Comment by bog-dan-ro** [comment] 2022-05-10 05:29
> > Affected versions
> > r21
> > r22
> > r23
> > r24
> 
> r25 not listed because the bug has been fixed, or because it wasn't tested?

Wasn't tested, I didn't know that there is an r25 :).

But, as long as r21 and r23 are long term support, I'm expecting the fix to land also on those two ...

**Comment by bog-dan-ro** [comment] 2022-05-16 08:39
> > But, as long as r21 and r23 are long term support
> 
> r21 support ended about a year ago. r23 support ends in August and our (supposedly) final spin of that toolchain completed a few weeks ago.

I hope that at least one LTS NDK to have it fixed ...

**Comment by enh-google** [comment] 2022-05-16 15:33
> > r21 support ended about a year ago. r23 support ends in August and our (supposedly) final spin of that toolchain completed a few weeks ago.
> 
> I hope that at least one LTS NDK to have it fixed ...

yeah, sorry, i almost followed up to what danalbert said last week with "btw, r25 is the _next_ LTS". it is mentioned if you know where to look (https://github.com/android/ndk/wiki#ndk-r25) but i don't think we've done a good job of saying this in places like "next to download links", so i suspect most people won't have noticed...

(even if Studio showed people the release notes, it's not actually mentioned in the release notes :-) )

**Comment by jfgoog** [comment] 2022-05-16 17:04
I grabbed test_unused_typeinfo.tar.gz and did the following, with both NDK 24 and builtin /usr/bin/clang:

`mkdir build && cd build && cmake .. && make`

In both cases, the example compiles, although it does included the supposedly unused symbol.

`nm -gD libtest_typeinfo.so` says:

```
                 U __cxa_atexit@GLIBC_2.2.5
                 w __cxa_finalize@GLIBC_2.2.5
                 U __dynamic_cast@CXXABI_1.3
                 w __gmon_start__
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
0000000000001250 T _Z12usedFunctionv
00000000000011b0 T _Z14unusedFunctionP15UnusedBaseClass
00000000000011a0 T _Z4testv
                 U _ZNSolsEPFRSoS_E@GLIBCXX_3.4
                 U _ZNSt8ios_base4InitC1Ev@GLIBCXX_3.4
                 U _ZNSt8ios_base4InitD1Ev@GLIBCXX_3.4
                 U _ZSt4cout@GLIBCXX_3.4
                 U _ZSt4endlIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_@GLIBCXX_3.4
                 U _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc@GLIBCXX_3.4
                 U _ZTI11UnusedClass
                 U _ZTI15UnusedBaseClass
```

Only the addresses differ between the two compilers.

Should I be doing something different to reproduce this issue?

**Comment by DanAlbert** [comment] 2022-05-16 19:27
> i almost followed up to what danalbert said last week with "btw, r25 is the next LTS"

Yes, just to be clear, there will never not be an active LTS. Each LTS is supported for a minimum of one year. Support lasts longer if the next LTS is not available yet. This is documented here: https://github.com/android/ndk/wiki/NDK-Release-Process#lts-release

**Comment by DanAlbert** [comment] 2022-05-17 18:22
Closing not reproducible. Will reopen if we get the info we need.

**Comment by bog-dan-ro** [comment] 2022-05-18 06:10
Sorry for the slow reply, I packed an older version which doesn't contain
 `string(APPEND CMAKE_SHARED_LINKER_FLAGS " -Wl,--no-undefined")` to `CMakeLists.txt` .

Adding it will reproduce this issue, sadly it reproduce it also with gcc (I'll file a bug report to gcc as well)., as I don't think the final .so fle should contain any `UnuseXXXX` stuff.

**Comment by bog-dan-ro** [comment] 2022-05-19 10:08
I don't know if needed, but here https://sourceware.org/bugzilla/show_bug.cgi?id=29157 you can find the binutils/ld bug report.

**Comment by jfgoog** [comment] 2022-05-19 17:08
OK, I was calling cmake incorrectly.

When I do:

``mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=~/Android/Sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 .. && make``

I get:

```
[ 16%] Building CXX object CMakeFiles/liba.dir/liba.cpp.o
[ 33%] Linking CXX static library libliba.a
[ 33%] Built target liba
[ 50%] Building CXX object CMakeFiles/libb.dir/libb.cpp.o
[ 66%] Linking CXX static library liblibb.a
[ 66%] Built target libb
[ 83%] Building CXX object CMakeFiles/test_typeinfo.dir/libc.cpp.o
[100%] Linking CXX shared library libtest_typeinfo.so
ld: error: undefined symbol: typeinfo for UnusedBaseClass
>>> referenced by libb.cpp:8 (/usr/local/google/home/jamesfarrell/bugs/unused-typeinfo/test_unused_typeinfo/libb.cpp:8)
>>>               libb.cpp.o:(unusedFunction(UnusedBaseClass*)) in archive liblibb.a
>>> referenced by libb.cpp:8 (/usr/local/google/home/jamesfarrell/bugs/unused-typeinfo/test_unused_typeinfo/libb.cpp:8)
>>>               libb.cpp.o:(unusedFunction(UnusedBaseClass*)) in archive liblibb.a

ld: error: undefined symbol: typeinfo for UnusedClass
>>> referenced by libb.cpp:8 (/usr/local/google/home/jamesfarrell/bugs/unused-typeinfo/test_unused_typeinfo/libb.cpp:8)
>>>               libb.cpp.o:(unusedFunction(UnusedBaseClass*)) in archive liblibb.a
>>> referenced by libb.cpp:8 (/usr/local/google/home/jamesfarrell/bugs/unused-typeinfo/test_unused_typeinfo/libb.cpp:8)
>>>               libb.cpp.o:(unusedFunction(UnusedBaseClass*)) in archive liblibb.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/test_typeinfo.dir/build.make:98: libtest_typeinfo.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/test_typeinfo.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

According to `make -n` the failing command is:

`/usr/bin/cmake -E cmake_link_script CMakeFiles/test_typeinfo.dir/link.txt --verbose=`

link.txt contains:

`/usr/local/google/home/jamesfarrell/Android/Sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --sysroot=/usr/local/google/home/jamesfarrell/Android/Sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions -frtti -stdlib=libc++ -O2 -g -DNDEBUG -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Qunused-arguments -Wl,--no-undefined -shared -Wl,-soname,libtest_typeinfo.so -o libtest_typeinfo.so CMakeFiles/test_typeinfo.dir/libc.cpp.o  liblibb.a  -static-libstdc++ -latomic -lm`

I'm not sure this is a bug, though. `libb.cpp` includes `liba.h`, so according to the source code, libb depends on liba. But that dependency is not declared in CMakeLists.txt.

libc may not actually depend on liba, but we don't know that when compiling libb, So I would expect to have to preserve the dependency until the linker, we hope, can sort it out and remove the unused function.

**Comment by bog-dan-ro** [comment] 2022-05-19 19:36
The problem is that libb adds the references of Unused XXXX to libc even libc is not using them and it fails to link it.

**Comment by jfgoog** [comment] 2022-05-19 19:43
OK, I will investigate that some more. But I do think we need to agree that libb depends on liba, and this needs to be declared in CMakeLists.txt, by uncommenting `target_link_libraries(libb liba)`.

**Comment by jfgoog** [comment] 2022-05-19 19:57
OK, after further discussion, this is not a bug.

It is not the case that libc.h defines the API of libtest_typeinfo.so, so it would be incorrect for the compiler to remove references to unusedFunction().

As a well-known example, if you `#include <cstdio>`, that's basically just a wrapper that does `#include <stdio.h>`. But the compiler can't remove the `printf` function just because it's defined in stdio.h and not cstdio.

**Closed by jfgoog** 2022-05-19 19:57 UTC
Labels: bug, needs-info

**Comment by DanAlbert** [comment] 2022-05-19 20:01
A bit more info: the linker (as you've seen, this isn't just LLD, this is how binutils behaves as well) handles static libraries one .o at a time. You're using `-ffunction-sections` and `--gc-sections` and are probably expecting that to do the pruning for you, but that happens at a later stage of linking. If a .o file is used (and it is, because `usedFunction` and `unusedFunction` are in the same .o file), the whole file has to be linkable. It isn't because of the missing dependency. If you split the functions into separate .o files what you're doing will work fine (though I still don't recommend it; it's much better to tell the build system about dependencies that definitely exist in source and letting the linker figure out what isn't needed at runtime).
