### ISSUE TITLE
[BUG] Windows console output broken with r21

### ISSUE THREAD

**Issue by Tolriq** [android/ndk#1106] opened 2019-10-21 11:05 UTC
### Description

When building from command line with ndk-build.cmd the console output is now completely broken and gives this
```
[ C y
[ C y
[ C y
[ C y
[ S l
[ I l
[ C y
[ C y
[ C y
[ C y
[ S l
[ I l
[ C y
[ C y
[ C y
[ C y
[ S l
[ I l
[ C y
[ C y
[ C y
[ C y
[ S l
[ I l
```

Compilation is working properly beside that. Maybe there's a new flag to disable coloring ansi escape codes or use supported ones?

#### Environment Details

Ndk r21 final / Windows 10 / Normal command line and Powershell.

**Comment by DanAlbert** [comment] 2019-10-21 17:29
I didn't see this issue on any of the windows machines I used for testing. Could you run winver?

**Comment by Tolriq** [comment] 2019-10-21 18:18
![image](https://user-images.githubusercontent.com/932609/67231231-358c1280-f43f-11e9-9e47-f5e0626f3742.png)

Using a simple cmd script

```
@ECHO OFF
SET NDK_HOME=D:\Android\sdk\ndk-bundle
SET DT=%date:~6,4%%date:~3,2%%date:~0,2%%time:~0,2%%time:~3,2%%time:~6,2%
cd %~dp0
start /B /wait "" cmd /c %NDK_HOME%\ndk-build NDK_PROJECT_PATH=%~dp0..\XXXX\src\main NDK_APP_OUT=%~dp0..\XXXX\build clean
```

But directly running it does the same

```
PS D:\_Gradle\XXXXXX> D:\Android\sdk\ndk-bundle\ndk-build.cmd NDK_PROJECT_PATH=D:\_Gradle\XXXXX\XXXXXX\src\main NDK_APP_OUT=D:\_Gradle\XXXXXX\build clean
Android NDK: WARNING: APP_PLATFORM android-21 is higher than android:minSdkVersion 1 in D:\_Gradle\XXXXX\XXXXXXX\src\main/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-21. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.
[ C a
[ C c
[ C c
[ C c
[ C u
[ C y
[ C c
[ C c
[ C c
[ C y
[ C a
[ C c
[ C c
[ C c
[ C y
[ C c
[ C c
[ C c
[ C y

```

**Comment by rprichard** [comment] 2019-10-21 21:20
I can reproduce this on my Windows laptop.

**Comment by rprichard** [comment] 2019-10-21 21:40
The NDK's `echo.exe` looks broken:

```
C:\src\mess\ndktest>c:\src\android-ndk-r21-beta1\prebuilt\windows-x86_64\bin\echo.exe Aaa Bbb "Two Word" Ccc
A B T C

C:\src\mess\ndktest>c:\src\android-ndk-r20\prebuilt\windows-x86_64\bin\echo.exe Aaa Bbb "Two Word" Ccc
Aaa Bbb Two Word Ccc
```

ndk/sources/host-tools/toolbox/echo_win.c has this line:

```
TCHAR** argv = CommandLineToArgvW(GetCommandLine(), &argc);
```

`TCHAR` is a typedef that either uses 8-bit `char` or 16-bit `wchar_t`, depending on whether `_UNICODE` is defined.

Maybe we stopped defining `_UNICODE` somewhere.

**Comment by DanAlbert** [comment] 2019-10-21 22:43
I'm also seeing this now as well. No idea why that didn't show up in earlier testing...

**Comment by enh-google** [comment] 2019-10-21 22:45
(i think it's hilarious that they all start with `[` --- i assumed these were escape sequences!)

**Comment by rprichard** [comment] 2019-10-22 00:07
> Maybe we stopped defining _UNICODE somewhere.

The macro is defined at the top of the file, so that's not it.

It looks like the NDK's echo.exe is built with these commands:

```
$ /x/ndk$ python3 ndk/sources/host-tools/toolbox/build.py --host windows64
...
x86_64-w64-mingw32-gcc -c -o /x/ndk/out/toolbox/echo_win.o /x/ndk/ndk/sources/host-tools/toolbox/echo_win.c -I/x/ndk/ndk/sources/host-tools/toolbox -funwind-tables
...
x86_64-w64-mingw32-g++ -s /x/ndk/out/toolbox/echo_win.o -o /x/ndk/ndk/host-tools/bin/echo.exe
```

The behavior of `%s` and `%S` in the mingw prebuilt gcc seems to have flipped between NDK r20 and NDK r21. I think the new behavior matches POSIX and Linux, but the old behavior matches MSVC docs. Using `%ls` instead should be portable.

```c++
#include <stdio.h>
#include <wchar.h>

int main() {
  wprintf(L"narrow argument ===");
  wprintf(L"\narg %%s:  [%s]",  "arg");
  wprintf(L"\narg %%S:  [%S]",  "arg");
  wprintf(L"\narg %%hs: [%hs]", "arg");
  wprintf(L"\narg %%hhs: [%hhs]", "arg");

  wprintf(L"\n\nwide argument ===");
  wprintf(L"\narg %%s:  [%s]",  L"arg");
  wprintf(L"\narg %%S:  [%S]",  L"arg");
  wprintf(L"\narg %%ls: [%ls]", L"arg");
  wprintf(L"\narg %%lS: [%lS]",  L"arg");

  wprintf(L"\n");
  return 0;
}
```

```
$ gcc test.c && ./a.out   (on my Linux machine)
narrow argument ===
arg %s:  [arg]
arg %S:  [?]
arg %hs: [arg]
arg %hhs: [arg]

wide argument ===
arg %s:  [a]
arg %S:  [arg]
arg %ls: [arg]
arg %lS: [arg]
```

```
$ /x/ndk-release-r20/prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/bin/x86_64-w64-mingw32-gcc test.c && wine ./a.exe
narrow argument ===
arg %s:  [
arg %S:  [arg]
arg %hs: [arg]
arg %hhs: [arg]

wide argument ===
arg %s:  [arg]
arg %S:  [a]
arg %ls: [arg]
arg %lS: [arg]
```

```
$ /x/ndk/prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/bin/x86_64-w64-mingw32-gcc test.c && wine ./a.exe
narrow argument ===
arg %s:  [arg]
arg %S:  [
arg %hs: [arg]
arg %hhs: [arg]

wide argument ===
arg %s:  [a]
arg %S:  [arg]
arg %ls: [arg]
arg %lS: [arg]
```

https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2019:

> Type character | Argument | Output format
> --- | --- | ---
> s | String | When used with printf functions, specifies a single-byte or multi-byte character string; when used with wprintf functions, specifies a wide-character string. Characters are displayed up to the first null character or until the precision value is reached.
> S | String | When used with printf functions, specifies a wide-character string; when used with wprintf functions, specifies a single-byte or multi-byte character string. Characters are displayed up to the first null character or until the precision value is reached.


https://pubs.opengroup.org/onlinepubs/7908799/xsh/fwprintf.html:

> s
> If no l (ell) qualifier is present, the argument must be a pointer to a character array containing a character sequence beginning in the initial shift state. Characters from the array are converted as if by repeated calls to the mbrtowc() function, with the conversion state described by an mbstate_t object initialised to zero before the first character is converted, and written up to (but not including) the terminating null wide-character. If the precision is specified, no more than that many wide-characters are written. If the precision is not specified or is greater than the size of the array, the array must contain a null wide-character. If an l (ell) qualifier is present, the argument must be a pointer to an array of type wchar_t. Wide characters from the array are written up to (but not including) a terminating null wide-character. If no precision is specified or is greater than the size of the array, the array must contain a null wide-character. If a precision is specified, no more than that many wide-characters are written.

> S
> Same as ls.

**Comment by rprichard** [comment] 2019-10-22 00:57
The MSVC on rextester (MSVC 2015?) recommends `%hs` and `%lS` via compiler warnings, and `%hhs` didn't work. https://rextester.com/OCQHN86784

**Comment by rprichard** [comment] 2019-10-22 02:30
Uploaded https://android-review.googlesource.com/c/platform/ndk/+/1147694

**Comment by rprichard** [comment] 2019-10-22 23:28
I see two flags that seem to apply here:

 * mingw-w64's headers recognize a macro, `__USE_MINGW_ANSI_STDIO`, that selects either mingw's own printf implementation or the one from the MS crt (msvcrt or ucrt).

 * If `__USE_MINGW_ANSI_STDIO` is non-zero, mingw provides the C/POSIX standard %s/%S behavior.

 * If `__USE_MINGW_ANSI_STDIO` is zero, then a `wprintf` call is forwarded to `wprintf` (msvcrt) or to `__stdio_common_vfwprintf` (ucrt), which takes a list of options as its first argument.

Some ucrt options are listed in a [mingw-w64 header](https://github.com/mirror/mingw-w64/blob/4fc998e614d745cb8be8c15c6d659b71bde81b2d/mingw-w64-headers/crt/stdio.h#L140). I verified that `__stdio_common_vfwprintf` follows the C/POSIX standards by default (when the options are 0), but the %s/%S specifiers switch back to the old MSVC behavior with the `UCRTBASE_PRINTF_LEGACY_WIDE_SPECIFIERS` option.

It looks like the upstream mingw-w64 project decided a couple of months ago that the legacy behavior should be the default. (Both commits were commited on 2019-08-31, but the second one has an author date from 2017.) See:
 * https://github.com/mirror/mingw-w64/commit/cd485c6cffe7c4df9e5a2c0f437878817391ded2#diff-aa0d6dce99cd264052e14e4f8d5bd84a
 * https://github.com/mirror/mingw-w64/commit/0a1d495478d8ed1a94fc77b9dbb428b7e0372588#diff-0a70e647bf5756310c64af8297794026

Mozilla and Tor have also hit this bug:
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1577872
 * https://trac.torproject.org/projects/tor/ticket/31567

I'm still not sure what behavior MSVC is defaulting to. Given that mingw-w64 switched back to the legacy behavior, maybe MSVC didn't switch to the standard behavior?

I see various recommendations to use `%ls` (instead of `%lS`), and the Linux man pages say, "don't use %S", so maybe I'll switch that.

**Comment by rprichard** [comment] 2019-10-23 03:41
The fix should be in the next r21 beta.

I don't know if we want to switch the wprintf %s/%S behavior back. I think we would switch back if we merged in the current mingw-w64 master. If we want to switch it back before then, we can open a separate issue.

**Closed by rprichard** 2019-10-23 03:41 UTC
Labels: bug, high

**Comment by mstorsjo** [comment] 2019-10-23 10:32
So I presume that the NDK mingw-w64 build changed from using msvcrt.dll to ucrt recently, hence this bug?

> I see two flags that seem to apply here:
> 
> * mingw-w64's headers recognize a macro, `__USE_MINGW_ANSI_STDIO`, that selects either mingw's own printf implementation or the one from the MS crt (msvcrt or ucrt).
> * If `__USE_MINGW_ANSI_STDIO` is non-zero, mingw provides the C/POSIX standard %s/%S behavior.
> * If `__USE_MINGW_ANSI_STDIO` is zero, then a `wprintf` call is forwarded to `wprintf` (msvcrt) or to `__stdio_common_vfwprintf` (ucrt), which takes a list of options as its first argument.

Another non-obvious point worth knowing wrt this, is that libstdc++ headers implicitly define `__USE_MINGW_ANSI_STDIO` in certain cases. So if one is using libstdc++, one more or less has to manually define `__USE_MINGW_ANSI_STDIO` as well, to be sure to get consistent behaviour. But that's not the case here I presume (as you use libc++ nowadays, and the broken application was plain C).

> Some ucrt options are listed in a [mingw-w64 header](https://github.com/mirror/mingw-w64/blob/4fc998e614d745cb8be8c15c6d659b71bde81b2d/mingw-w64-headers/crt/stdio.h#L140). I verified that `__stdio_common_vfwprintf` follows the C/POSIX standards by default (when the options are 0), but the %s/%S specifiers switch back to the old MSVC behavior with the `UCRTBASE_PRINTF_LEGACY_WIDE_SPECIFIERS` option.
> 
> It looks like the upstream mingw-w64 project decided a couple of months ago that the legacy behavior should be the default. (Both commits were commited on 2019-08-31, but the second one has an author date from 2017.) See:
> 
> * [mirror/mingw-w64@cd485c6#diff-aa0d6dce99cd264052e14e4f8d5bd84a](https://github.com/mirror/mingw-w64/commit/cd485c6cffe7c4df9e5a2c0f437878817391ded2#diff-aa0d6dce99cd264052e14e4f8d5bd84a)
> * [mirror/mingw-w64@0a1d495#diff-0a70e647bf5756310c64af8297794026](https://github.com/mirror/mingw-w64/commit/0a1d495478d8ed1a94fc77b9dbb428b7e0372588#diff-0a70e647bf5756310c64af8297794026)
> 
> Mozilla and Tor have also hit this bug:
> 
> * https://bugzilla.mozilla.org/show_bug.cgi?id=1577872
> * https://trac.torproject.org/projects/tor/ticket/31567
> 
> I'm still not sure what behavior MSVC is defaulting to. Given that mingw-w64 switched back to the legacy behavior, maybe MSVC didn't switch to the standard behavior?

Correct - back when the second commit was originally made in 2017 and brought up for discussion, we concluded that it would be better for mingw-w64 to align with MSVC's behaviour even if it was a change to how it used to be when using msvcrt.dll. But neither of us in the discussion actually doublechecked what MSVC does by default back then, and now in 2019 I noticed that MSVC still does maintain the old legacy behaviour by default (but it can be overridden in a number of ways).

(It's kind of interesting that MSVC does maintain this non-standard legacy behaviour by default, even though they claim conformance to newer standards like C99, which iirc do specify how wchar_t should behave wrt stdio.)

So with those commits, the behaviour should be consistent between MSVC (with no custom settings), mingw-w64 with msvcrt.dll and mingw-w64 with ucrt - as long as `__USE_MINGW_ANSI_STDIO` isn't defined.

> I see various recommendations to use `%ls` (instead of `%lS`), and the Linux man pages say, "don't use %S", so maybe I'll switch that.

Yes, that's probably the safest thing to do, to avoid the case that has varying behaviour.

**Comment by rprichard** [comment] 2019-10-23 22:12
Thanks for looking at this.

> So I presume that the NDK mingw-w64 build changed from using msvcrt.dll to ucrt recently, hence this bug?

Yeah, we had switched our Windows Clang binaries (and LLVMgold.dll) over to ucrt a while ago (e.g. 6-12 months ago or so?). For the recent NDK r21 beta, we had a problem where `ar.exe` (not using ucrt) failed, because it was loading the `LLVMgold.dll` plugin (using ucrt) and sharing file descriptors between the two.

The fix was to enable ucrt by default in mingw-w64:
https://android-review.googlesource.com/c/toolchain/mingw/+/1138140/

That change also switched `echo.exe` and `cmp.exe` over to ucrt, which were using `wprintf(L"%s")` with wide string arguments.

> Another non-obvious point worth knowing wrt this, is that libstdc++ headers implicitly define __USE_MINGW_ANSI_STDIO in certain cases. So if one is using libstdc++, one more or less has to manually define __USE_MINGW_ANSI_STDIO as well, to be sure to get consistent behaviour. But that's not the case here I presume (as you use libc++ nowadays, and the broken application was plain C).

I think the Android platform's host tools (e.g. adb/fastboot) and LLVM are built using Clang and libc++. I think gdb and gold are built with g++ and libstdc++. Maybe they don't care about `wprintf("%s")`, though. (I did see `swprintf` and `__vfwprintf` calls in gdb-8.3 that probably expect `%s` to be a multibyte string, but I'm not sure the NDK's `gdb.exe` would reach those call sites.)

> Correct - back when the second commit was originally made in 2017 and brought up for discussion, we concluded that it would be better for mingw-w64 to align with MSVC's behaviour even if it was a change to how it used to be when using msvcrt.dll. But neither of us in the discussion actually doublechecked what MSVC does by default back then, and now in 2019 I noticed that MSVC still does maintain the old legacy behaviour by default (but it can be overridden in a number of ways).
> 
> (It's kind of interesting that MSVC does maintain this non-standard legacy behaviour by default, even though they claim conformance to newer standards like C99, which iirc do specify how wchar_t should behave wrt stdio.)
> 
> So with those commits, the behaviour should be consistent between MSVC (with no custom settings), mingw-w64 with msvcrt.dll and mingw-w64 with ucrt - as long as __USE_MINGW_ANSI_STDIO isn't defined.

That makes sense.
